### PR TITLE
Add CNAME record for zoho mail verification

### PR DESCRIPTION
**Pull request by ItsNiceCraft**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [X] The file is in the `domains` folder and is in the JSON format.
- [X] You have completed your website. 
- [X] The website is reachable.  
- [X] You're not using Vercel or Netlify.  
- [X] The CNAME record doesn't contain `https://` or `/`.  
- [X] There is sufficient information at the `owner` field.

### CODE REVIEW

**Comment by ItsNiceCraft** [comment]
According to [the workflow](https://github.com/is-a-dev/register/actions/runs/4194026306/jobs/7271653377) ("Run tests", line 51), the CNAME record is poorly configured, but I didn't make any changes to it in this pr. Is there something else wrong?

**Review by wdhdev — CHANGES_REQUESTED** [review]
Sorry, we don't support verification of domains.

**Comment by ItsNiceCraft** [comment]
@WilliamDavidHarrison is there an alternate way to send and receive images using a .is-a.dev subdomain?

**Comment by WilliamDavidHarrison** [comment]
> @WilliamDavidHarrison is there an alternate way to send and receive images using a .is-a.dev subdomain?

What do you mean by sending and receiving images? Do you mean email?

**Comment by ItsNiceCraft** [comment]
Of course, sorry, I don't know why I said images
------- Original Message -------
William Harrison ***@***.***> schrieb am Freitag, 17. Februar 2023 um 23:11:

**Comment by WilliamDavidHarrison** [comment]
If you want to receive emails you can use ImprovMX.

**Pull request closed without merging**
