### PR TITLE
Register z.is-a.dev

### PR DESCRIPTION
**Pull request by jvideo-sk**
Register z.is-a.dev with CNAME record pointing to jvideo.is-a.dev.

### CODE REVIEW

**Comment by jakeharrison90** [comment]
how many domains will fulfill your needs, kid

**Review by iostpa — CHANGES_REQUESTED** [review]
Limit for one letter subdomains is one. You have reached that limit so I won't merge this PR.

**Comment by CuteDog5695** [comment]
> how many domains will fulfill your needs, kid

?

**Comment by jakeharrison90** [comment]
> > how many domains will fulfill your needs, kid
> 
> ?

I have checked his profile he is already having many domains that's what i said

**Pull request closed without merging**
