### PR TITLE
remove `fonts.json`

### PR DESCRIPTION
**Pull request by TheBotlyNoob**
It doesn't work, and I don't want to clutter up the `domains` dir (even tho it already is cluttered)

### CODE REVIEW

**Review by mtgsquad — DISMISSED** [review]
Yeah, we tried :(

**Comment by TheBotlyNoob** [comment]
wait, don't merge yet, I have to commit something

**Review by hackermondev — DISMISSED** [review]

**Comment by mtgsquad** [comment]
> wait, don't merge yet, I have to commit something

Okay

**Comment by TheBotlyNoob** [comment]
I lied, there will be fonts

**Comment by TheBotlyNoob** [comment]
nvm, ill reopen when GitHub works

**Pull request closed without merging**
