### PR TITLE
Create plushhh

### PR DESCRIPTION
**Pull request by Authiesz**
To make our job easier, please spend time to review your application before submitting. 

- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: plushhh.github.io
- [x] The website is reachable.
- [x] The CNAME record doesn't contain any slash.
- [x] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.

### CODE REVIEW

**Comment by LogSkele** [comment]
u have to complete your website smh

**Review by TheBotlyNoob — CHANGES_REQUESTED** [review]
you have an incomplete website.

**Comment by LogSkele** [comment]
i dont get it, if you have a incompleted website, why did u check the " You have completed your website, there's no type of placeholder at the website. This requirement can be raised if the domain you're registering is for emails" requirement

**Comment by Authiesz** [comment]
Hello. Can you please delete this pull request since it has my personal information and is a threat to my security.

**Pull request closed without merging**
