### PR TITLE
BETA: Register smartlinuxcoder.is-a.dev

### PR DESCRIPTION
**Pull request by Smartlinuxcoder**
Added `smartlinuxcoder.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Comment by Smartlinuxcoder** [comment]
could you please remove this pr

**Comment by Smartlinuxcoder** [comment]
contains private info

**Comment by Smartlinuxcoder** [comment]
could you close this pr and delete this branch?

**Comment by phenax** [comment]
@Smartlinuxcoder Created a ticket with github. This pr will be removed soon.

**Pull request closed without merging**
