### PR TITLE
Domain registration is-a.dev 

### PR DESCRIPTION
**Pull request by hung319**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://hung319.github.io/hung319/

### CODE REVIEW

**Review by hung319 — COMMENTED** [review]
test

**Review by iostpa — CHANGES_REQUESTED** [review]
The h4rs website doesn't really seem to be complete for me, the hung319 website is complete though.

**Comment by hung319** [comment]
> The h4rs website doesn't really seem to be complete for me, the hung319 website is complete though.

I left the H4RS page.

**Comment by hung319** [comment]
> ## Requirements
> Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.
> 
> Please note that we reserve the rights not to accept any domain at our own discretion.
> 
> * [x]  The file is in the `domains` folder and is in the JSON format.
> * [x]  The file's name is all lowercased and alphanumeric.
> * [x]  You have completed your website.
> * [x]  The website is reachable.
> * [x]  The CNAME record doesn't contain `https://` or `/`.
> * [x]  There is sufficient information at the `owner` field.
> 
> ## Website Link/Preview
> https://hung319.github.io/hung319/

**Comment by hung319** [comment]
> ## Requirements
> Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.
> 
> Please note that we reserve the rights not to accept any domain at our own discretion.
> 
> * [x]  The file is in the `domains` folder and is in the JSON format.
> * [x]  The file's name is all lowercased and alphanumeric.
> * [x]  You have completed your website.
> * [x]  The website is reachable.
> * [x]  The CNAME record doesn't contain `https://` or `/`.
> * [x]  There is sufficient information at the `owner` field.
> 
> ## Website Link/Preview
> https://hung319.github.io/hung319/

**Review by iostpa — APPROVED** [review]
Seems good to me now

**Pull request merged**
