### PR TITLE
Create srv1.winter.is-a.dev

### PR DESCRIPTION
**Pull request by virtualWinter**
Added srv1.winter.is-a.dev because i have plans on getting 1 more server.

### CODE REVIEW

**Comment by virtualWinter** [comment]
yep, i really did this

**Comment by virtualWinter** [comment]
more planned infrastructure

**Comment by virtualWinter** [comment]
adding sso because i realized there are a lot of features and i cba to remember a lot of different passwords

**Comment by virtualWinter** [comment]
images will be used as dashboard for sharex uploader thing
cdn will be the link used to view the images

**Comment by virtualWinter** [comment]
yep, you already know what i'll use this one for

**Review by DEV-DIBSTER — APPROVED** [review]

**Pull request merged**
