### PR TITLE
Create avileforsure

### PR DESCRIPTION
**Pull request by Ewufie23**

### CODE REVIEW

**Comment by AvileForsure** [comment]
I have not twitter and i dont really want to share my email yet

**Review by MaskDuck — APPROVED** [review]
well, i think you should come back when you have a completed website.

we don't accept incomplete website, sowwy

**Review by MaskDuck — CHANGES_REQUESTED** [review]
i meant... request changes

you can share any other thing you want eg discord

**Comment by AvileForsure** [comment]
Sure, ill finish it soon

**Pull request closed without merging**
