### PR TITLE
abhint

### PR DESCRIPTION
**Pull request by abhint**

### CODE REVIEW

**Review by omsenjalia — CHANGES_REQUESTED** [review]
https://abhint.github.io is not a valid repo url. A repo url is https://github.com/name/repo. Also you need to input an email

**Review by mtgsquad — DISMISSED** [review]
If you don't want to add your email address, add some sort of way we can contact you, such as discord/twitter.

**Comment by mtgsquad** [comment]
> https://abhint.github.io is not a valid repo url. A repo url is https://github.com/name/repo. Also you need to input an email

Mate, repo URL doesn't matter + email is not necessary only discord or twitter will also work.

**Comment by omxpro** [comment]
> > https://abhint.github.io is not a valid repo url. A repo url is https://github.com/name/repo. Also you need to input an email
> 
> Mate, repo URL doesn't matter + email is not necessary only discord or twitter will also work.

Didn't know that

**Review by abhint — COMMENTED** [review]
add repo link and Twitter  link

**Review by MaskDuck — CHANGES_REQUESTED** [review]
not that *haiyaa*... you create a new field in the `owner` field such as `"twitter": "your-twitter-^s3rn@m3"`

**Review by abhint — COMMENTED** [review]
twitter

**Review by abhint — COMMENTED** [review]
email

**Review by MaskDuck — APPROVED** [review]

**Pull request merged**
