### PR TITLE
BETA: Update oxmc.is-a.dev

### PR DESCRIPTION
**Pull request by oxmc**
Updated `oxmc.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please use a valid record.

**Comment by oxmc** [comment]
What records do you need? and I'm not that well versed in this field.

**Comment by WilliamDavidHarrison** [comment]
https://docs.is-a.dev

**Comment by oxmc** [comment]
Alright, i believe i have it all set up correctly.

**Review by oxmc — COMMENTED** [review]
only have oxmc.json

**Pull request closed without merging**
