### PR TITLE
Create ziari.json

### PR DESCRIPTION
**Pull request by AMIRPARSAZIARI**

### CODE REVIEW

**Review by mtgsquad — APPROVED** [review]

**Review by mtgsquad — CHANGES_REQUESTED** [review]
You cannot have a protocol in a  CNAME url and you do not need to add a path as well. GitHub Pages will automatically configure it.

**Comment by AMIRPARSAZIARI** [comment]
is it ok now?

**Comment by mtgsquad** [comment]
By protocol, I mean the https:// part. Please remove it.

**Comment by mtgsquad** [comment]
Oh wait, seems to be fixed by TheBotlyNoob.

**Review by mtgsquad — APPROVED** [review]

**Review by TheBotlyNoob — APPROVED** [review]

**Pull request merged**
