### PR TITLE
Create jeremie.json

### PR DESCRIPTION
**Pull request by 0xw01f**
## Requirements
- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Link to Website

https://w01f.fr/

### CODE REVIEW

**Review by omsenjalia — CHANGES_REQUESTED** [review]
Please make your repo public

**Review by wdhdev — CHANGES_REQUESTED** [review]
404

**Comment by 0xw01f** [comment]
Which repo ? 
This repository is public https://github.com/0xw01f/link-tree
(which is linked to the domain name https://w01f.fr/)

**Comment by WilliamDavidHarrison** [comment]
> Which repo ?
> This repository is public https://github.com/0xw01f/link-tree
> (which is linked to the domain name https://w01f.fr/)

The repo that will be linked to your is-a.dev domain. As in the repo field in the file it currently says `oxw01f/isadev.github.io`.

**Comment by 0xw01f** [comment]
I see. It should be good now, sorry.

**Comment by WilliamDavidHarrison** [comment]
> I see. It should be good now, sorry.

I still can't seem to reach it. Please try moving your website into a repo called `oxw01f.github.io` and update the repo field.

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
