### PR TITLE
Create qwerty.json

### PR DESCRIPTION
**Pull request by QwertyIsCoding**

### CODE REVIEW

**Review by phenax — CHANGES_REQUESTED** [review]
CNAME has to be a host name. If you want a URL redirection, use URL instead of CNAME. If you want a CNAME record, remove everything but the host name.

**Comment by QwertyIsThinking** [comment]
But what do you mean by use URL instead of CNAME? Isn't my CNAME already the URL? Sorry if this message is stupid but I honestly don't know how this works.

**Comment by QwertyIsThinking** [comment]
Currently the redirect page isn't working because according to the docs, I have to set it to my new domain.

**Comment by QwertyIsCoding** [comment]
> CNAME has to be a host name. If you want a URL redirection, use URL instead of CNAME. If you want a CNAME record, remove everything but the host name.

Oops, nevermind. I understood what you meant. I updated the file! Please inform me if it is fine now.

**Review by phenax — CHANGES_REQUESTED** [review]
As I said, CNAME has to be a **host name** and not a url. If you mean to use github pages, `qwertyiscoding.github.io` is the host name. Go through the [github pages docs](https://docs.github.com/en/pages) if you need help with github pages

**Comment by QwertyIsCoding** [comment]
> As I said, CNAME has to be a **host name** and not a url. If you mean to use github pages, `qwertyiscoding.github.io` is the host name. Go through the [github pages docs](https://docs.github.com/en/pages) if you need help with github pages

I see. I'm sorry. I didn't exactly know what you meant.

**Comment by QwertyIsCoding** [comment]
I hope it is correct now.

**Comment by phenax** [comment]
Btw, I saw your index.html and it seems like you're using the CNAME to redirect to a netlify page. If that is your use-case then you can redirect it directly from here to netlify if you want by using `URL` record type instead of `CNAME` and giving it your redirection url. Let me know if you want to keep this or not and I'll merge it in.

**Comment by QwertyIsCoding** [comment]
> Btw, I saw your index.html and it seems like you're using the CNAME to redirect to a netlify page. If that is your use-case then you can redirect it directly from here to netlify if you want by using `URL` record type instead of `CNAME` and giving it your redirection url. Let me know if you want to keep this or not and I'll merge it in.

I guess that should do it! I just want something to redirect to my personal website and i want that redirect page's domain to be short and good.

**Review by phenax — APPROVED** [review]

**Pull request merged**
