### PR TITLE
Create KoshikKumar17.json

### PR DESCRIPTION
**Pull request by KoshikKumar17**
To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [ ] You're not using Vercel or Netlify.
- [ ] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [ ] The website is reachable.
- [ ] The CNAME record doesn't contain any slash.
- [ ] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

### CODE REVIEW

**Review by MaskDuck — CHANGES_REQUESTED** [review]

**Review by KoshikKumar17 — COMMENTED** [review]
Done

**Review by VaibhavSys — CHANGES_REQUESTED** [review]
The name of the file is invalid. It must be lowercased, alphanumeric and each component must be more than 2 characters long.

**Comment by KoshikKumar17** [comment]
Done

**Review by MaskDuck — APPROVED** [review]
would not recommend "please wait" prompt on website, but yeah, btw sorry for late reply

**Comment by KoshikKumar17** [comment]
> would not recommend "please wait" prompt on website, but yeah, btw sorry for late reply

No problem sir...

**Pull request merged**
