### PR TITLE
Register Subdomain: ztz

### PR DESCRIPTION
**Pull request by ZTzTopia**
Added the domain: ztz

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
404?

**Comment by ZTzTopia** [comment]
> 404?

I haven't put anything in there.

**Comment by WilliamDavidHarrison** [comment]
> > 404?
> 
> I haven't put anything in there.

You need a website to get a subdomain.

**Comment by ZTzTopia** [comment]
> > > 404?
> > 
> > 
> > I haven't put anything in there.
> 
> You need a website to get a subdomain.

I've added a web server but I haven't made the page just a 404 not found page, is that ok?

**Comment by WilliamDavidHarrison** [comment]
You need to have an actual website.

**Review by wdhdev — APPROVED** [review]

**Review by MaskDuck — APPROVED** [review]

**Pull request merged**
