### PR TITLE
Update albinpraveen.json

### PR DESCRIPTION
**Pull request by ALBINPRAVEEN**
## Requirements
Unless explicitly specified otherwise by a **maintainer**, your domain must pass **all** of the indicated requirements below.
Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.

### CODE REVIEW

**Comment by ALBINPRAVEEN** [comment]
- Why it is showing error.like this Cannot acess page``
albinpraveen.is-a.dev normally uses encryption to protect your information. When Chrome tried to connect to albinpraveen.is-a.dev this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be albinpraveen.is-a.dev or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Chrome stopped the connection before any data was exchanged.

You cannot visit albinpraveen.is-a.dev right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

**Review by omsenjalia — CHANGES_REQUESTED** [review]
CNAME cannot contain /

**Comment by ALBINPRAVEEN** [comment]
Can cancel contain vercel websites

**Comment by ALBINPRAVEEN** [comment]
Closed

**Comment by TerraPlayz** [comment]
> Can cname contain vercel websites

No

**Comment by ALBINPRAVEEN** [comment]
Ok thnkz

**Comment by TerraPlayz** [comment]
Vercel and Netlify isn't supported. Host on https://pages.cloudflare.com it's fast and supported

**Comment by TerraPlayz** [comment]
Read [docs](https://is-a.dev/docs) it probably has a tutorial

**Pull request closed without merging**
