### PR TITLE
BETA: Register live.is-a.dev

### PR DESCRIPTION
**Pull request by tomgxz**
Added `live.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Review by triach-rold — CHANGES_REQUESTED** [review]
Website is empty, but reachable.

**Comment by tomgxz** [comment]
This is just how railway manages it's CNAME records. 
The same thing happened with #6429 and #10795
Railway waits for a DNS update before hosting on the given url.

**Comment by CuteDog5695** [comment]
> This is just how railway manages it's CNAME records. The same thing happened with #6429 and #10795 Railway waits for a DNS update before hosting on the given url.

could i see a preview of your website please?

**Comment by tomgxz** [comment]
image

**Review by DEV-DIBSTER — APPROVED** [review]

**Pull request merged**
