### PR TITLE
Register school.klent.is-a.dev

### PR DESCRIPTION
**Pull request by kleeiny**
Register school.klent.is-a.dev with CNAME record pointing to ghs.google.com.

### CODE REVIEW

**Review by kleeiny — COMMENTED** [review]
i forgot to remove it mb

**Review by triach-rold — CHANGES_REQUESTED** [review]
404. Website is unreachable.

**Review by iostpa — DISMISSED** [review]
can you give me a preview of the blogpost website? (considering CNAME has ghs.google.com)

**Comment by kleeiny** [comment]
https://klentdaniel.blogspot.com/ — The website was initially at klent.is-a.dev I just want to transfer it to a sub-subdomain because I already have plans for klent.is-a.dev

**Review by MaskDuck — APPROVED** [review]

**Pull request merged**
