### PR TITLE
Register hleb.is-a.dev

### PR DESCRIPTION
**Pull request by cyberbread-ru**
Register hleb.is-a.dev with A record pointing to 195.133.30.245.

### CODE REVIEW

**Review by wdhdev — APPROVED** [review]

**Comment by wdhdev** [comment]
@cyberbread-ru Can we get a preview of your website

**Comment by cyberbread-ru** [comment]
Yes. It's on https://cyberbread.ru 
It's basically just a bio of me

31 октября 2024 г. 01:29:10 UTC, William Harrison ***@***.***> пишет:

**Comment by cyberbread-ru** [comment]
But why?

**Comment by wdhdev** [comment]
The link to your file download website.

**Comment by cyberbread-ru** [comment]
Will it be fine if I remove it on is-a.dev?

1 ноября 2024 г. 04:43:53 UTC, William Harrison ***@***.***> пишет:

**Comment by wdhdev** [comment]
Unfortunately not as this time.

**Pull request closed without merging**
