### PR TITLE
Idk what Im doing 😔

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by iostpa — CHANGES_REQUESTED** [review]
Need site preview

**Review by ghost — COMMENTED** [review]
Ok

**Review by ghost — COMMENTED** [review]
Reviewed

**Comment by itsFatlum** [comment]
> Need site preview

Are you looking for this https://docs-git-main-fatlum.vercel.app/? Im really lost rn

**Comment by itsFatlum** [comment]
Im not sure what else you mean by site preview

**Comment by SkyExploreWasTaken** [comment]
@itsFatlum you need to give a preview of your website that's going to run on the domain, like a picture or a link of the website, but on another domain.

**Comment by itsFatlum** [comment]
Isn't the Vercel link enough?

**Comment by CuteDog5695** [comment]
Yes, i just needed the link to the vercel website

**Review by iostpa — CHANGES_REQUESTED** [review]
This is a template...
Can you at least change it so that it talks about yourself?

**Comment by CuteDog5695** [comment]
You can just make simple changes, like your name and a basic instruction (doesn't have to be complicated)

**Comment by itsFatlum** [comment]
I changed some things like the homepage, etc.

**Review by iostpa — APPROVED** [review]
Should be fine now

**Pull request merged**
