### PR TITLE
Create coder100.json

### PR DESCRIPTION
**Pull request by cursorweb**

### CODE REVIEW

**Review by MaskDuck — APPROVED** [review]
nice

**Comment by cursorweb** [comment]
thank you!

**Comment by cursorweb** [comment]
it's been more than 24 hours, is there a way to troubleshoot why the domain isn't working?
image

**Comment by MaskDuck** [comment]
looks like a railway issue, or have you properly configure railway yet

**Comment by cursorweb** [comment]
ah oops lol

**Pull request merged**
