### PR TITLE
Update hari.json

### PR DESCRIPTION
**Pull request by harishnkr**

### CODE REVIEW

**Review by phenax — DISMISSED** [review]

**Review by phenax — APPROVED** [review]
You should check the Enforce HTTPS checkbox in your github pages repo settings

**Comment by Haritronic909** [comment]
I have a doubt. Suppose I have a file in my repo that I have to download
with the link on my webpage. How can I download it with a .is-a.dev custom
domain? Is it possible?

**Comment by phenax** [comment]
If your file is at `/path/somefile` in the `github.com/haritronic909/haritronic909.github.io` repo, then you can download the file at `https://hari.is-a.dev/path/somefile`. Because this is a dns record, the only thing that changes is the hostname.

**Comment by Haritronic909** [comment]
Yeah it was a mistake on my part. Thanks for helping me out though.

**Pull request merged**
