### PR TITLE
Update records for redirecting to https://okinea.dev

### PR DESCRIPTION
**Pull request by okineadev**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview
image

### CODE REVIEW

**Review by omsenjalia — DISMISSED** [review]
Email invalid. Please have either a valid discord field so we can easily contact you. you cannot have a noreply email from GitHub as you cant recive anything from it. Update it!

**Comment by okineadev** [comment]
> Email invalid. Please have either a valid discord field so we can easily contact you. you cannot have a noreply email from GitHub as you cant recive anything from it. Update it!

Who are you anyway???

**Comment by okineadev** [comment]
I see you are not a member

**Comment by okineadev** [comment]
You are clearly a spammer

**Comment by vintheweirdass** [comment]
@okineadev 
image
image
image
He is in fact, can merge things, even though he isn't a member of the repo. He's the codeowner

https://github.com/is-a-dev/register/pull/17219
https://github.com/is-a-dev/register/pull/17208
Here's the recent Pull Requests that he merged

Or just see the complete list that he helps
https://github.com/is-a-dev/register/issues?q=label%3A%22r%3A+om.senjalia%22+is%3Aclosed

**Comment by okineadev** [comment]
I don't trust him.

Better call a real member...

**Comment by okineadev** [comment]
I will never give you a real e-mail and Discord, the data I gave you will be enough.

**Comment by okineadev** [comment]
And tell me why you have never asked me for this before, there have never been such demands

**Comment by CuteDog5695** [comment]
> > Email invalid. Please have either a valid discord field so we can easily contact you. you cannot have a noreply email from GitHub as you cant recive anything from it. Update it!
> 
> Who are you anyway???

Hes a member of our staff team. Calling one of our staff team a spammer is a dick move.

**Review by iostpa — APPROVED** [review]
Removed the email line since it isn't necessary anymore. Other then that, seems good to me

**Comment by okineadev** [comment]
> > > Email invalid. Please have either a valid discord field so we can easily contact you. you cannot have a noreply email from GitHub as you cant recive anything from it. Update it!
> > 
> > Who are you anyway???
> 
> Hes a member of our staff team. Calling one of our staff team a spammer is a dick move.

You said absolutely nothing about Discord and email before

**Comment by omsenjalia** [comment]
Got called a scammer 💀

**Comment by omsenjalia** [comment]
Spammer*

**Comment by CuteDog5695** [comment]
> > > > Email invalid. Please have either a valid discord field so we can easily contact you. you cannot have a noreply email from GitHub as you cant recive anything from it. Update it!
> > > 
> > > 
> > > Who are you anyway???
> > 
> > 
> > Hes a member of our staff team. Calling one of our staff team a spammer is a dick move.
> 
> You said absolutely nothing about Discord and email before

Oh trust me, we did, a WHILE ago.
Before we moved to Cloudflare DNS, email field was necessary. You could either add a email for leave it blank and add a social (like discord, twitter, telegram etc.). But since we moved our DNS to Cloudflare, our social part is more lenient, where email line isn't necessary anymore.

**Comment by okineadev** [comment]
I thought that it was some random dude who made a review and said that more data was needed, and also put "!" That I do it as soon as possible

A real email is too much in my opinion, and a simple person is unlikely to ask for it

Telegram is enough

**Comment by CuteDog5695** [comment]
> I thought that it was some random dude who made a review and said that more data was needed, and also put "!" That I do it as soon as possible
> 
> A real email is too much in my opinion, and a simple person is unlikely to ask for it
> 
> Telegram is enough

Yea Telegram is enough, email field isn't necessary anymore.

**Comment by CuteDog5695** [comment]
@okineadev Now thinking about it, maybe one of our staff members (who usually merges invalid PRs) merged your PR without asking about the no-reply email (which usually we didn't merge). If thats the case, then sorry for the confusion.

**Comment by okineadev** [comment]
> maybe one of our staff members

Probably you

**Comment by CuteDog5695** [comment]
Actually wasn't me :/

**Comment by CuteDog5695** [comment]
Keep in mind that we have like 9 maintainers in total.

**Comment by okineadev** [comment]
> > > Email invalid. Please have either a valid discord field so we can easily contact you. you cannot have a noreply email from GitHub as you cant recive anything from it. Update it!
> > 
> > Who are you anyway???
> 
> Hes a member of our staff team. Calling one of our staff team a spammer is a dick move.

How was I supposed to know that he is a member (at least) of this organization

**Comment by okineadev** [comment]
I didn't see the member badge

**Comment by CuteDog5695** [comment]
I don't think he made this org public on his profile, but @vintheweirdass did tell you beforehand that it was a maintainer. Plus only maintainers can add labels.

**Pull request merged**
