### PR TITLE
Create discordbots.semant.json

### PR DESCRIPTION
**Pull request by s3mant**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
You have no website...

**Comment by s3mant** [comment]
> You have no website...

its discord dashboard'

**Comment by WilliamDavidHarrison** [comment]
> > You have no website...
> 
> its discord dashboard, i gotta get the domain first to verify discord auth

Ok.

**Review by wdhdev — APPROVED** [review]
Tell me when it is up.

**Comment by s3mant** [comment]
> Tell me when it is up.

no
its supposed to be private

**Comment by s3mant** [comment]
> yeah it's a backend one, @s3mant ig it's like HTTP interaction bot right?

maybe, pls dont spam

**Pull request merged**
