### PR TITLE
Register Subdomain: _github-pages-challenge-lucifer1708.sumit

### PR DESCRIPTION
**Pull request by lucifer1708**
Added the domain: _github-pages-challenge-lucifer1708.sumit

### CODE REVIEW

**Review by omsenjalia — CHANGES_REQUESTED** [review]
I do not think this is allowed

**Comment by TerraPlayz** [comment]
> > I do not think this is allowed
> 
> it's allowed

Alright 👍

**Review by omsenjalia — APPROVED** [review]
👍👍

**Review by wdhdev — CHANGES_REQUESTED** [review]
sumit.is-a.dev isn't registered so you cannot register a verification record for it.

Please register sumit.is-a.dev first.

**Pull request closed without merging**
