### PR TITLE
feat(validation): acme challenge support

### PR DESCRIPTION
**Pull request by wdhdev**
This PR will allow users to add `_acme-challenge` records to their subdomains to be able to generate SSL certificates using DNS verification.

In future, we should add a cleanup workflow which runs every week or so, so old challenge records are deleted.

I am waiting for at least 5 approvals by our staff team (at least 3 maintainers and 2 helpers) to approve this PR as I would like to get their thoughts on the change.

### CODE REVIEW

**Review by VaibhavSys — APPROVED** [review]

**Review by mtgsquad — APPROVED** [review]

**Review by andrewstech — DISMISSED** [review]
William is female

**Comment by wdhdev** [comment]
They would still need to open a PR and get it approved

**Review by andrewstech — APPROVED** [review]

**Comment by wdhdev** [comment]
@is-a-dev/helpers Andrew and I would like to know what you think of this as well.

**Comment by andrewstech** [comment]
@Wizqdev thoughts

**Review by NicoGaming77 — APPROVED** [review]

**Review by Stef-DP — APPROVED** [review]

**Review by DEV-DIBSTER — APPROVED** [review]

**Pull request merged**
