### PR TITLE
Create aayush.json V2

### PR DESCRIPTION
**Pull request by aayushxr**

### CODE REVIEW

**Comment by MaskDuck** [comment]
please do not make duplicate prs, it makes us hard to manage.

**Comment by Aayush-Rajagopalan** [comment]
i couldnt find my pr earlier so i made a new one, sorry. Is the domain created?

**Comment by MaskDuck** [comment]
no

**Comment by MaskDuck** [comment]
lemme approve it

**Review by MaskDuck — APPROVED** [review]
the author is still too sussy

**Comment by Aayush-Rajagopalan** [comment]
ok,

**Comment by Aayush-Rajagopalan** [comment]
> the author is still too sussy

why tho

**Comment by MaskDuck** [comment]
@Aayush-Rajagopalan sorry for the delay but your pr is merged.

now you need to config your domain. idk what your host is, but make sure to inlude `aayush.is-a.dev` in your installed ssl!

dont forget to give this project a star if you havent!

if you need help feel free to join our discord (link in readme) or create a new gh issue.

**Comment by Aayush-Rajagopalan** [comment]
Thank you :)

**Comment by Aayush-Rajagopalan** [comment]
The domain still redirects to the main site tho

**Comment by MaskDuck** [comment]
have you config as noted in the docs yet

**Comment by MaskDuck** [comment]
it is not redirect to the main site for me
(maybe cookie things)

**Comment by MaskDuck** [comment]
is your installed ssl contain `aayush.is-a.dev`?

**Comment by MaskDuck** [comment]
WAIT IT IS NETLIFY
image

(sorry, for some reason vercel and netlify isnt woworking with this service 😭 )

**Comment by Aayush-Rajagopalan** [comment]
so wait, i cant add this domain?

**Comment by MaskDuck** [comment]
you could try [railway](https://railway.app)

**Comment by Aayush-Rajagopalan** [comment]
how can i update the domain in this same pr
if i try changing it, it tells to open a new pr

**Comment by MaskDuck** [comment]
open a new pr.

**Pull request merged**
