### PR TITLE
Create kira272921.json

### PR DESCRIPTION
**Pull request by 0xMukesh**
I need this cool sub-domain for my [portfolio](https://kira272921.netlify.app/) website

### CODE REVIEW

**Comment by Kira272921** [comment]
@TheBotlyNoob Hey, could you please review this ?

**Comment by Kira272921** [comment]
@TheBotlyNoob, @mtgsquad Hey, could you review this PR ?

**Review by phenax — CHANGES_REQUESTED** [review]
CNAME cannot be a URL. If you meant to have a URL redirection, use URL instead of CNAME.

**Comment by Kira272921** [comment]
@phenax I have made the required changes.

**Comment by phenax** [comment]
Unfortunately, netlify has some problems with our service and in its current state, cannot be used. You can try [railway](https://railway.app/)

**Pull request closed without merging**
