### PR TITLE
Create hari.json

### PR DESCRIPTION
**Pull request by harishnkr**

### CODE REVIEW

**Comment by shajanjp** [comment]
Hi @Haritronic909 
It will be good if you can change the CNAME to lower case.

**Comment by phenax** [comment]
> It will be good if you can change the CNAME to lower case.
Wrong cased cnames should be fine. I'm merging it in for now.

Also, @shajanjp, thanks a lot for helping out with these reviews! I really appreciate it.

**Review by phenax — APPROVED** [review]

**Comment by Haritronic909** [comment]
thanks for helping me out, is the cname case sensitive?? Idk that's y I'm
asking

**Comment by shajanjp** [comment]
@Harikrishnan6336 Its not case sensitive, but same cased would be better right ?
Anyway, your chages are merged.
Thanks for contributing. :+1:

**Pull request merged**
