### PR TITLE
Update verification after accidentally deleting domain

### PR DESCRIPTION
**Pull request by leahanderson1**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.

### CODE REVIEW

**Review by wdhdev — APPROVED** [review]

**Review by wdhdev — CHANGES_REQUESTED** [review]
I cannot confirm you as the owner of this domain.

**Comment by OtterCodes101** [comment]
I still have access to the oliver.anderson4435@gmail.com email. Can I use that to verify?

**Comment by wdhdev** [comment]
Can you please send an email to `william@williamharrison.dev` from that email.

**Comment by OtterCodes101** [comment]
alright!

**Comment by OtterCodes101** [comment]
finished

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
