### PR TITLE
Register jdev082.is-a.dev

### PR DESCRIPTION
**Pull request by jdev082**
Added `jdev082.is-a.dev` using the [CLI](https://www.npmjs.com/package/@is-a-dev/cli).

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
I can't reach your website.

**Comment by jdev082** [comment]
@WilliamDavidHarrison fixed

**Review by wdhdev — APPROVED** [review]

**Comment by jdev082** [comment]
the domain redirects to https://www.is-a.dev/

**Comment by jdev082** [comment]
nvm fixed

**Pull request merged**
