### PR TITLE
Update joshatticus.json

### PR DESCRIPTION
**Pull request by JoshAtticus**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview
https://sites.google.com/view/joshatticuswebsite/home

Note to maintainers: the domain needs to be verified with the TXT record added before Google Sites gives me the cname record to add

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Sorry, we don't support TXT verification. You could just use a redirect instead though.

**Comment by JoshAtticus** [comment]
> Sorry, we don't support TXT verification. You could just use a redirect instead though.

Ah, ok, I'll see if there's CNAME verification

**Comment by JoshAtticus** [comment]
Screenshot 2023-04-08 at 1 51 28 pm
Is it possible to add this?

**Comment by WilliamDavidHarrison** [comment]
Unfortunately not.

**Comment by JoshAtticus** [comment]
Damn, I might just make my GitHub pages site embed my new one

**Pull request closed without merging**
