### PR TITLE
Added email forwarding records.

### PR DESCRIPTION
**Pull request by ipuppyyt**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

image

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
We don't support CNAME's with other records.

**Comment by ipuppyyt** [comment]
I don't know what this validation issue is. Please let me know what to do. I've just updated the json file with MX and TXT records for my email forwarding via improvmx.

**Comment by ipuppyyt** [comment]
> We don't support CNAME's with other records.

So what do you propose I do in order to get my email forwarding active

**Comment by WilliamDavidHarrison** [comment]
Try using GitHub Pages with A records. That should work.

**Comment by ipuppyyt** [comment]
> Try using GitHub Pages with A records. That should work.

Is there any documentation on how to do that ? Idk how to do that.

**Comment by WilliamDavidHarrison** [comment]
https://www.is-a.dev/docs

**Comment by ipuppyyt** [comment]
> https://www.is-a.dev/docs

I don't understand how to implement that. Can you please help me with it. Thanks

**Comment by WilliamDavidHarrison** [comment]
Have you deployed your site with GitHub Pages?

**Comment by ipuppyyt** [comment]
> Have you deployed your site with GitHub Pages?

yes. i've used github pages to host.
==> https://ipuppyyt.github.io/

**Review by wdhdev — APPROVED** [review]

**Comment by WilliamDavidHarrison** [comment]
Create a file called `CNAME` in your repository and add the content `ipuppyyt.is-a.dev`

**Pull request merged**
