### PR TITLE
Added nikita via is-a-dev-cli

### PR DESCRIPTION
**Pull request by nikitacontreras**
Added nikita via the CLI

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please use a valid CNAME

**Review by wdhdev — CHANGES_REQUESTED** [review]
It asks for microphone usage, this is a security risk. Please fix it.

**Comment by nikitacontreras** [comment]
Commented "audio-api.js".
Can it be reimplemented later? as its intended for animation purposes
imagen

**Comment by WilliamDavidHarrison** [comment]
> Commented "audio-api.js". Can it be reimplemented later? as its intended for animation purposes imagen

What does it do?

**Comment by WilliamDavidHarrison** [comment]
> _*hopefully*_, it's supposed to animate some background waves

Ok, I will merge your pull request.

Please note if your website records and saves that data your domain will be removed without notice.

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
