### PR TITLE
Create donut.json

### PR DESCRIPTION
**Pull request by donut6150**
### Requirements
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [x] The website is reachable.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### Link to Website

donut2008.github.io

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
I can't seem to reach your website

**Comment by donut2008** [comment]
> I can't seem to reach your website

There's no index.html currently, I removed all the placeholder code

**Comment by WilliamDavidHarrison** [comment]
> > I can't seem to reach your website
> 
> There's no index.html currently, I removed all the placeholder code

Please make a website, so then we can give you the domain.

**Comment by donut2008** [comment]
> > > I can't seem to reach your website
> > 
> > 
> > There's no index.html currently, I removed all the placeholder code
> 
> Please make a website, so then we can give you the domain.

Alright I made an index.html

**Review by wdhdev — APPROVED** [review]

**Review by MaskDuck — APPROVED** [review]

**Pull request merged**
