### PR TITLE
Register tornfoolery.is-a.dev

### PR DESCRIPTION
**Pull request by Tornfoolery**
Register torn.is-a.dev with CNAME record pointing to https://github.com/Tornfoolery.

### CODE REVIEW

**Comment by cupglassDEV** [comment]
You clearly didnt understand what i said in the past https://github.com/is-a-dev/register/pull/16860#issuecomment-2441645526

If you want a cname, make a github page first. And this is **NOT** a github page

But if you want a simple URL that redirects to your github link (like this), you will want to change it to "URL" instead of "CNAME"

**Comment by cupglassDEV** [comment]
@Tornfoolery

**Comment by Tornfoolery** [comment]
ohh yep, mb i was still a bit clueless. I get it know though thanks

**Comment by cupglassDEV** [comment]
Np, if you have any question, you can dm me on discord

Im in the is-a.dev server also

**Comment by Tornfoolery** [comment]
alright! thanks

**Comment by cupglassDEV** [comment]
Ah, this is good 👌

We'll wait for the maintainer to come in

**Comment by cupglassDEV** [comment]
@CuteDog5695

**Review by iostpa — CHANGES_REQUESTED** [review]
Needs more content, you can quickly just say some basic info about yourself.

**Comment by Tornfoolery** [comment]
Alright, i've updated my github page

**Review by iostpa — APPROVED** [review]
Now it seems good to me

**Pull request merged**
