### PR TITLE
Create deploywithshubham.json

### PR DESCRIPTION
**Pull request by deploywithshubham**
To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [x] The website is reachable.
- [x] The CNAME record doesn't contain any slash.
- [x] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

### CODE REVIEW

**Comment by WilliamDavidHarrison** [comment]
You cannot have a coming soon page. You must have an actual website.

**Comment by deploywithshubham** [comment]
The website is under development, when my website is ready I'll update on here.

**Comment by WilliamDavidHarrison** [comment]
Well to first get the subdomain you need to have the website.

**Comment by deploywithshubham** [comment]
Now, the website is ready and the updated JSON file with new website URL.

**Comment by deploywithshubham** [comment]
Hey, how many days may it take to set up a CNAME record on your DNS? Everything is done from my side and I updated JSON file, So please look out for it. Thanks!

**Comment by WilliamDavidHarrison** [comment]
@deploywithshubham They need to merge the PR and then the records should be updated quickly.

**Comment by deploywithshubham** [comment]
Take too much time!

**Pull request closed without merging**
