### PR TITLE
BETA: Register porant.is-a.dev

### PR DESCRIPTION
**Pull request by porant**
Added `porant.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Review by triach-rold — CHANGES_REQUESTED** [review]
Website is reachable, but pretty incomplete.

**Comment by porant** [comment]
Done, now it is complete the page idea is like visit card, Links above name are now clikable and going to coresponding pages.

**Comment by porant** [comment]
> Website is reachable, but pretty incomplete.

Done, now it is complete the page idea is like visit card, Links above name are now clikable and going to coresponding pages.

**Review by porant — COMMENTED** [review]
Done, now it is complete the page idea is like visit card, Links above name are now clikable and going to coresponding pages.

**Review by iostpa — APPROVED** [review]

**Pull request merged**
