### PR TITLE
Added husain via is-a-dev-cli

### PR DESCRIPTION
**Pull request by snsnf**
Added husain via the CLI

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
What is this server being used for?

**Comment by H-Killer** [comment]
> What is this server being used for?

it's for build dev website as CV

**Comment by WilliamDavidHarrison** [comment]
> > What is this server being used for?
> 
> it's for build dev website as CV

Can you send me a preview of your site?

**Comment by H-Killer** [comment]
> > > What is this server being used for?
> > 
> > 
> > it's for build dev website as CV
> 
> Can you send me a preview of your site?

I didn't build it yet, I will first grab the subdomain and then start building but you can check my other website it could be like this https://itsinfinity.dev

**Review by wdhdev — APPROVED** [review]

**Comment by H-Killer** [comment]
Hi, the subdomain still not working why?

**Comment by WilliamDavidHarrison** [comment]
> Hi, the subdomain still not working why?

Please open an issue

**Pull request merged**
