### PR TITLE
Create chiragnahata.json

### PR DESCRIPTION
**Pull request by chiragnahata**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.

### CODE REVIEW

**Review by DEV-DIBSTER — APPROVED** [review]

**Review by wdhdev — APPROVED** [review]

**Comment by chiragnahata** [comment]
image

Please help

**Comment by WilliamDavidHarrison** [comment]
Are you trying to set it up on a server? You are currently using is-a.dev hosting.

**Comment by chiragnahata** [comment]
Yes. So how to do that ?

**Comment by chiragnahata** [comment]
I wanted to know how to create subdomains from it also ?

**Comment by WilliamDavidHarrison** [comment]
> Yes. So how to do that ?

You can't set it up on your server if your subdomain doesn't point to it.

**Comment by WilliamDavidHarrison** [comment]
> I wanted to know how to create subdomains from it also ?

You can create nested subdomains by creating a file like your main one with a different file name. For example, `blog.example.json`.

**Comment by chiragnahata** [comment]
Please can you point it to my server ?
 "records": {
        "A": ["129.213.151.29"]

**Comment by chiragnahata** [comment]
How to do it on my server ?

**Comment by chiragnahata** [comment]
Btw you are very helpful and you answer so fast. Thanks

**Comment by WilliamDavidHarrison** [comment]
> How to do it on my server ?

Unfortunately you cannot create subdomains using your server, you will need to create a new file for each one.

**Comment by WilliamDavidHarrison** [comment]
> "A": ["129.213.151.29"]

You will need to update your file and open a new PR.

**Pull request merged**
