### PR TITLE
Create rnss.json

### PR DESCRIPTION
**Pull request by xrnss**
<3

### CODE REVIEW

**Comment by TheBotlyNoob** [comment]
ermm

**Comment by TheBotlyNoob** [comment]
you need to look at the [docs](https://github.com/is-a-dev/register/blob/main/docs/domains-json.md)

**Comment by xrnss** [comment]
i might have realised that after i made the pr but i didn't know how to undo the pr so um

**Comment by hackermondev** [comment]
editing your fork (https://github.com/xrnss/register) will edit the PR

**Comment by TheBotlyNoob** [comment]
closing because of inactivity

**Pull request closed without merging**
