### PR TITLE
Create youssef-lmouden.json

### PR DESCRIPTION
**Pull request by Y0usaf3**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ yes] The file is in the `domains` folder and is in the JSON format.
- [ yes] The file's name is all lowercased and alphanumeric. 
- [ yes, just some light commit] You have completed your website. 
- [ yeah] The website is reachable.  
- [yep ] The CNAME record doesn't contain `https://` or `/`.  
- [ yeah chatgot help me] There is sufficient information at the `owner` field.  

## Website Link/Preview
[](https://github.com/YoussefDevPro/Youssef_Portfolio)

### CODE REVIEW

**Comment by YoussefDevPro** [comment]
https://github.com/YoussefDevPro/Youssef_Portfolio

**Comment by YoussefDevPro** [comment]
um

**Comment by YoussefDevPro** [comment]
https://github.com/YoussefDevPro/Youssef_Portfolio

**Comment by YoussefDevPro** [comment]
i think i make a mistake when i crate the json file

**Comment by YoussefDevPro** [comment]
i think this time will work

**Review by Stef-DP — DISMISSED** [review]

**Review by Stef-DP — APPROVED** [review]

**Pull request merged**
