### PR TITLE
[DNM/WIP] Create yafes.json

### PR DESCRIPTION
**Pull request by yafesdot**
Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [x] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

[yaf.es](https://yaf.es)

### CODE REVIEW

**Comment by yafesdot** [comment]
The site is at a rough draft stage. That's why I opened a draft pr, will turn it into a pr when the time comes.

**Comment by mtgsquad** [comment]
@yafesdot We do not have an issue with you creating a draft PR, however, I do want to make you aware that this does not reserve you the right to this domain. Anybody can still create a fully complete and valid PR, and it will get merged for this very domain.

**Comment by yafesdot** [comment]
> @yafesdot We do not have an issue with you creating a draft PR, however, I do want to make you aware that this does not reserve you the right to this domain. Anybody can still create a fully complete and valid PR, and it will get merged for this very domain.

Alright! Either way, at least this PR will be a reminder for me, so no problem.

**Comment by WilliamDavidHarrison** [comment]
@yafesdot I will close this PR, but when you are ready just open a new PR.

**Comment by yafesdot** [comment]
aight

**Pull request closed without merging**
