### PR TITLE
Add hashnode setup docs

### PR DESCRIPTION
**Pull request by mtgsquad**
Create some documentation for setting up hashnode blogs with is-a.dev subdomains

### CODE REVIEW

**Review by hackermondev — DISMISSED** [review]

**Review by phenax — COMMENTED** [review]
Looks good! Can you also link this file inside `docs/README.md`? Also, we should link to their official documentation before our guide.

**Comment by mtgsquad** [comment]
@phenax, i added the link to `docs/README.md`, if there are any other changes you want, tell me please!

**Comment by phenax** [comment]
@mtgsquad, I think adding a link to official hashnode docs/guide will be a good idea for users to find more resources in case they get stuck.

**Comment by mtgsquad** [comment]
@phenax, i get it, i think i can link that as well.

**Review by phenax — APPROVED** [review]

**Comment by phenax** [comment]
Thanks!

**Pull request merged**
