### PR TITLE
updated joker.json (CNAME)

### PR DESCRIPTION
**Pull request by JoKeRxTD**

### CODE REVIEW

**Review by TheBotlyNoob — CHANGES_REQUESTED** [review]
The `CNAME` cannot be an array

**Comment by mtgsquad** [comment]
Hello, I don't think you understand how is-a.dev provides subdomains, it is a part of our terms that we do not allow nameservers on subdomains, however you can set your CNAME to a string and then you can use it with cloudflare pages & etc.

**Comment by JoKeRxTD** [comment]
> Hello, I don't think you understand how is-a.dev provides subdomains, it is a part of our terms that we do not allow nameservers on subdomains, however you can set your CNAME to a string and then you can use it with cloudflare pages & etc.

Hmm I have the Webspace. Just need the domain. I will have to google it. The IP I placed before is the Shared IP for my webhosting ns1.gtxgaming.co.uk is the nameserver for it

**Comment by Danix421** [comment]
> > Hello, I don't think you understand how is-a.dev provides subdomains, it is a part of our terms that we do not allow nameservers on subdomains, however you can set your CNAME to a string and then you can use it with cloudflare pages & etc.
> 
> Hmm I have the Webspace. Just need the domain. I will have to google it. The IP I placed before is the Shared IP for my webhosting ns1.gtxgaming.co.uk is the nameserver for it

I'll repeat what @mtgsquad said: is-a.dev doesn't allow namespaces, so you can't use them (I think).

**Comment by JoKeRxTD** [comment]
Updated.

**Review by hackermondev — APPROVED** [review]

**Review by TheBotlyNoob — APPROVED** [review]

**Pull request merged**
