### PR TITLE
Added Email Forwarding Using ImproveMX

### PR DESCRIPTION
**Pull request by Dheirya**
Added email forwards from my domain to my email using the ImproveMX site; let me know if there's anything wrong and I need to change/fix!

### CODE REVIEW

**Comment by GoodBoyNeon** [comment]
You cannot have both CNAME and MX in one domain

**Review by wdhdev — CHANGES_REQUESTED** [review]
You can't use CNAME and other records together.

**Comment by Dheirya** [comment]
Oh ok so I can't have both a website and forwarding email?

**Comment by WilliamDavidHarrison** [comment]
You can, just not with a CNAME.

**Comment by Dheirya** [comment]
Oh so I have to use "URL" in record? Doesn't that just redirect that to the original site? If so I don't want to add email forwarding from this domain...

**Pull request closed without merging**
