### PR TITLE
Switch to Cloudflare Pages and add Google Search Console

### PR DESCRIPTION
**Pull request by HeroGamers**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://portfolio-4cw.pages.dev/

### CODE REVIEW

**Comment by HeroGamers** [comment]
I don't know why the test doesn't pass, it mentions that the CNAME record should be a hostname, but it is. The stacktrace seems to show it's something else causing the issue.

**Review by wdhdev — APPROVED** [review]
I've removed the TXT record as we don't support TXT verification.

**Comment by HeroGamers** [comment]
Ah okay, is that a technical thing with the TXT record not being supported, or due to not wanting the verification records on?

I actually added it because I was looking through others on the repo to see if Cloudflare Pages would work, and saw that others had the Google search console record on it.

TXT is listed as a valid property on the docs though. But either way, at the end of the day it doesn't really matter to me, was just curious.

**Comment by WilliamDavidHarrison** [comment]
We don't support TXT verification due to sometimes with TXT verification it verifies the entire is-a.dev domain, which would mean other users can't use that service. We do support TXT records for other things like for email, etc.

Also, CNAME records can't mix with TXT records due to DNS requirements.

**Pull request merged**
