### PR TITLE
Run Publish Records on push

### PR DESCRIPTION
**Pull request by TheBotlyNoob**

### CODE REVIEW

**Comment by mtgsquad** [comment]
I don't know a damn thing about github actions, so i'm going to leave this to @phenax and the rest of the team.

**Review by Codeize — DISMISSED** [review]

**Review by phenax — CHANGES_REQUESTED** [review]
This is nice! You'll have to confirm 2 things with this before we can merge this -
1. Does the push event have access to github secrets?
2. Can a forked repo change the contents of the workflow?

The second one is really important as that could pose a security risk. Create a fake github user and try it out. You can use [is-a-dev/test-project](https://github.com/is-a-dev/test-project) to experiment with it.

**Comment by TheBotlyNoob** [comment]
> This is nice! You'll have to confirm 2 things with this before we can merge this -
> 
> 1. Does the push event have access to github secrets?
> 2. Can a forked repo change the contents of the workflow?
> 
> The second one is really important as that could pose a security risk. Create a fake github user and try it out. You can use [is-a-dev/test-project](https://github.com/is-a-dev/test-project) to experiment with it.

@phenax:
push does have access to github secrets, and im not really sure what you mean by `2. Can a forked repo change the contents of the workflow`.

**Comment by TheBotlyNoob** [comment]
@phenax, to clarify, `push` _**does**_ have access to GitHub secrets, and pushing has nothing to do with prs. So unless we merge anything, no pr/fork can inject malicious code

**Comment by hackermondev** [comment]
For this, wouldn't it be easier to like create another GitHub account with minimal permissions and use a personal access token to automatically send the publish records in the pull request when it is merged? It wouldn't rely on Github Actions and it would be fast and easy and could be running on something like [replit](https://replit.com)

**Comment by TheBotlyNoob** [comment]
@phenax, couldent find any documentation that clearly states that `push` has access to secrets but [this workflow](https://github.com/TheBotlyNoob-ALT/test-project/runs/2568564264) shows that it does. And im not really sure how to test it.

**Comment by phenax** [comment]
@TheBotlyNoob, I'll try to test this out this weekend and if all goes well, we'll merge this in.

**Comment by TheBotlyNoob** [comment]
Ok!

**Comment by TheBotlyNoob** [comment]
@phenax Anything new?

**Comment by phenax** [comment]
@TheBotlyNoob, couldn't make time for it. Will update once I've tested it.

**Comment by TheBotlyNoob** [comment]
@phenax if you are too paranoid about the workflow running on `push`, do you want to run it every 24 hours?

**Review by phenax — APPROVED** [review]
@TheBotlyNoob, sorry for the late reply. I tried with a push event and it seems safe to the attack I had in mind. We'll go ahead with this. Try to keep an eye on prs for any workflow related change.

**Pull request merged**
