### PR TITLE
improvmx

### PR DESCRIPTION
**Pull request by boolean44-repos**

### CODE REVIEW

**Comment by hackermondev** [comment]
If you don't mind, I've added a random CNAME there because the validator requires there by a CNAME record or an A record.

**Comment by boolean44-repos** [comment]
ok

**Review by hackermondev — APPROVED** [review]

**Comment by boolean44-repos** [comment]
i tried to check but it failed

**Comment by hackermondev** [comment]
> i tried to check but it failed

It will take a few hours to fully update.

**Comment by boolean44-repos** [comment]
it still hasn't gone through

**Pull request merged**
