### PR TITLE
new domain approval

### PR DESCRIPTION
**Pull request by AshC1ty**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://ashc1ty.github.io/test-toyo/

### CODE REVIEW

**Comment by AshC1ty** [comment]
hi, this domain is for a pet project of mine. I am a great fan of toyota and request you approve this domain :)

**Review by Stef-DP — CHANGES_REQUESTED** [review]
Can't accept your domain cause of possible copyright from toyota

**Comment by AshC1ty** [comment]
> Can't accept your domain cause of possible copyright from toyota

If possible can I use it for a maximum of two weeks and later delete the domain, if not feasible. I shall rename the file 😊

**Comment by 21Z** [comment]
> If possible can I use it for a maximum of two weeks and later delete the domain

why

**Comment by AshC1ty** [comment]
> > If possible can I use it for a maximum of two weeks and later delete the domain
> 
> why
> 

Well, it is for a mini project of mine, I just wanna show my friends and my teachers, I felt that if I had a custom domain, it would look cooler. I can assure you that it isn't for any commercial purpose. I won't misuse it

**Comment by AshC1ty** [comment]
hello, I have submitted a different pull request without the toyota name, hope that is fine if this pull request cannot be approved

**Pull request closed without merging**
