### PR TITLE
Register nextcloud.banana.is-a.dev

### PR DESCRIPTION
**Pull request by BANanaD3V**
Added `nextcloud.banana.is-a.dev` using the [CLI](https://www.npmjs.com/package/@is-a-dev/cli).

### CODE REVIEW

**Comment by BANanaD3V** [comment]
first done, alot more to be

**Comment by BANanaD3V** [comment]
wait, i can do only one pull request? sheesh, gonna take long...

**Comment by BANanaD3V** [comment]
i forgot about more than one commit in one push request lol, gonna do it when you accept this

**Review by wdhdev — APPROVED** [review]
I've removed the wildcard since we don't support them.

**Pull request merged**
