### PR TITLE
zishan.json

### PR DESCRIPTION
**Pull request by NotZishan**

### CODE REVIEW

**Review by AbubakarKang — COMMENTED** [review]
You need to add email in owner section. If you would not like to leak out your email, then you can leave it as an empty string. Also, try to remove the empty lines to save spaec.

**Comment by NotZishan** [comment]
Pls review my pull request again i have added my email now also removed the
spaces

**Comment by mtgsquad** [comment]
> You need to add email in owner section. If you would not like to leak out your email, then you can leave it as an empty string. Also, try to remove the empty lines to save spaec.

@AbubakarKang Just wanted to let you know, we don't require email, even as empty string. You can choose to put your discord or twitter.

**Comment by NotZishan** [comment]
> > You need to add email in owner section. If you would not like to leak out your email, then you can leave it as an empty string. Also, try to remove the empty lines to save spaec.
> 
> @AbubakarKang Just wanted to let you know, we don't require email, even as empty string. You can choose to put your discord or twitter.

Pls veiw my domain how much time it will take?

**Comment by MaskDuck** [comment]
@NotZishan please realize we do have life outside, and we are not paid or working on this full-time. we're trying to have all pr  merged in ~1 day, but it could take 5+ days (i waited 2 months for my domain, please be patient).

**Review by MaskDuck — APPROVED** [review]
fix the file format

**Pull request merged**
