### PR TITLE
delete other domains

### PR DESCRIPTION
**Pull request by wdhdev**
See #16340

### CODE REVIEW

**Comment by devashish2024** [comment]
@wdhdev Although I agree you should comply with the GitHub TOS, I'm sorry however I must have my email address back (hello@ashishagr.is-a.dev) that you have deleted in this PR.

If you look at my github repo for the website, I had wrote "12 years old" when I was about 12.8 (almost 13). Now I'm 13 so probably shouldn't be more wait for me, and yeah this is a misunderstanding that I didn't had updated that thing.

My email address is very valuable to me and I have used it in multiple places so please let me have it back.

Could you please unban me from the discord server (I don't know why is it a permanent ban...) and allow me to open a new PR for the domain? Discord: `nicec0re_`

**Comment by CuteDog5695** [comment]
I think what the confusion caused was in your about page you said you were 11, in your home page you said you was 12 and in your CV you said you were 13. I'd recommend updating your info to prevent misunderstandings in the future.

**Comment by wdhdev** [comment]
@devashish2024 So to confirm, you are 13? I'm assuming you were born in 2011?

As @CuteDog5695 said, we did have a misunderstanding due to your website saying you were 11 or 12.

I'll unban you once we clear this up.

**Comment by devashish2024** [comment]
> I think what the confusion caused was in your about page you said you were 11, in your home page you said you was 12 and in your CV you said you were 13. I'd recommend updating your info to prevent misunderstandings in the future.

Yeah I would, soon.


> @devashish2024 So to confirm, you are 13? I'm assuming you were born in 2011?
> 
> As @CuteDog5695 said, we did have a misunderstanding due to your website saying you were 11 or 12.
> 
> I'll unban you once we clear this up.

Yup, 2011.

**Comment by iostpa** [comment]
Are you 13 now?

**Comment by devashish2024** [comment]
Ofcourse.

**Pull request merged**
