### PR TITLE
Register wb.is-a.dev

### PR DESCRIPTION
**Pull request by davidctinescu**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview
https://156.67.25.171/ 
^^ this has a broken ssl configured for my previous is-a.dev subdomain

### CODE REVIEW

**Review by iostpa — APPROVED** [review]
Seems good to me

**Review by iostpa — CHANGES_REQUESTED** [review]
Nevermind, PR has merge conflicts

**Comment by davidctinescu** [comment]
> Nevermind, PR has merge conflicts

but im deleting a file (my old is a dev sub domain)

**Comment by CuteDog5695** [comment]
> > Nevermind, PR has merge conflicts
> 
> but im deleting a file (my old is a dev sub domain)

image
dont know if you noticed but

**Pull request closed without merging**
