### PR TITLE
Create gvl610.json

### PR DESCRIPTION
**Pull request by raspiduino**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

Link: https://giangvinhloc610.github.io

Screenshot:

image

Note: author of this PR is gvl610. I have two accounts. You can request proof if needed.

Thank you!

### CODE REVIEW

**Review by triach-rold — CHANGES_REQUESTED** [review]
404. Unreachable.

**Review by triach-rold — COMMENTED** [review]
You probably need to include [this](https://giangvinhloc610.github.io/) link in the CNAME instead of [this](gvl610.github.io) one.

**Comment by raspiduino** [comment]
Thank you for pointing that out! I have corrected it. thank you.

**Comment by raspiduino** [comment]
Thank you for the merge!

**Pull request merged**
