### PR TITLE
Register themadpunter.is-a.dev

### PR DESCRIPTION
**Pull request by familycomicsstudios**
Added `themadpunter` via the registration website.

### CODE REVIEW

**Comment by familycomicsstudios** [comment]
Use of CNAME is temporary, haven't set up port forwarding yet.

**Comment by familycomicsstudios** [comment]
When I put in the real IP, please note that I'm using the domain for SSH in addition to HTTPS.

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please make a website

**Comment by WilliamDavidHarrison** [comment]
> When I put in the real IP, please note that I'm using the domain for SSH in addition to HTTPS.

Ok, please update it when you can.

**Comment by WilliamDavidHarrison** [comment]
`

**Pull request closed without merging**
