### PR TITLE
Register Subdomain: sage

### PR DESCRIPTION
**Pull request by ghost**
Added the domain: sage

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Sorry, you can't have a coming soon page.

**Comment by SageDotExe** [comment]
Yeah thats mb i already have a home page but i forgot to push it

**Comment by SageDotExe** [comment]
I'll push it soon

**Comment by SageDotExe** [comment]
@WilliamDavidHarrison I've updated my index. Should be all goods now :+1:

**Review by wdhdev — APPROVED** [review]

**Comment by SageDotExe** [comment]
@WilliamDavidHarrison Just wondering, how long will it take to get my subdomain?

**Review by hackermondev — APPROVED** [review]

**Comment by i-df-k** [comment]
Hey, @WilliamDavidHarrison @hackermondev I was wondering if it was possible to remove my domain, and delete the sage.json file please :)

**Comment by WilliamDavidHarrison** [comment]
You can do so by forking the repository and going to your file directly and deleting it and opening a new PR.

**Pull request merged**
