### PR TITLE
Create kns.json

### PR DESCRIPTION
**Pull request by ItzCrazyKns**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [ ] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview
https://kns.is-a.dev

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please make a website

**Comment by ItzCrazyKns** [comment]
I Have The Website Ready

**Comment by WilliamDavidHarrison** [comment]
I still see the nginx welcome page.

**Comment by ItzCrazyKns** [comment]
ah but once you apporove the domain ill link it with the port im running the website on

**Comment by WilliamDavidHarrison** [comment]
> ah but once you apporove the domain ill link it with the port im running the website on
> 
> or do i need to provide you with the port too?

Can you send a preview of your site?

**Comment by ItzCrazyKns** [comment]
image

link:
http://129.153.126.170/

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
