### PR TITLE
Create smallhost.json

### PR DESCRIPTION
**Pull request by SmallHost**
smallhost.is-a.dev redirect to smallhost.us.to

### CODE REVIEW

**Review by phenax — CHANGES_REQUESTED** [review]
You are missing some fields. Please read the documentation and have a look at existing domain files for reference.

**Comment by SmallHost** [comment]
Thank you for emailing SmallHost! This is an autoreply that your message has been recieved. I will try to reply as soon as possible.

**Comment by mtgsquad** [comment]
@phenax, Come to maintainers discussion.

**Comment by mtgsquad** [comment]
@phenax, Come to maintainers discussion.

**Pull request closed without merging**
