### PR TITLE
Added muzammil.json

### PR DESCRIPTION
**Pull request by muzicode**

### CODE REVIEW

**Review by shajanjp — CHANGES_REQUESTED** [review]
Looks like `http://taqnar.github.io/` is not working.
Please refer https://pages.github.com

**Review by phenax — APPROVED** [review]

**Comment by taqnar** [comment]
Thank You

**Comment by taqnar** [comment]
I Loved the service

**Comment by taqnar** [comment]
I cannot get https://muzammil.is-a.dev/
It showing TLS certificate requesting error
I have attached the image of that error along with this
please help

repo used for hosting
https://github.com/taqnar/taqnar.github.io

**Comment by phenax** [comment]
Seems like you haven't checked the 'Enforce https' checkbox in your repo settings

**Comment by taqnar** [comment]
@phenax  Enforce https is in disabled format

**Comment by phenax** [comment]
@taqnar, can you create a new issue with the screenshot?

**Comment by taqnar** [comment]
ok

**Pull request merged**
