### PR TITLE
Register Subdomain: shadow

### PR DESCRIPTION
**Pull request by thewilloftheshadow**
Added the domain: shadow

### CODE REVIEW

**Comment by thewilloftheshadow** [comment]
Is this still pending intentionally? Am I missing a step I need to do?

**Comment by WilliamDavidHarrison** [comment]
> Is this still pending intentionally? Am I missing a step I need to do?

If you try to reach the CNAME it returns a 404.

**Comment by thewilloftheshadow** [comment]
That's odd. I just retriggered the action to deploy it, is it working now?

**Comment by WilliamDavidHarrison** [comment]
> That's odd. I just retriggered the action to deploy it, is it working now?

Still returns a 404. If you go to https://thewilloftheshadow.github.io

**Comment by WilliamDavidHarrison** [comment]
> Thats... not how a GitHub pages CNAME works.
> 
> GitHub's proxy is looking at the origin domain to determine what site to serve. Accessing it directly will look for https://github.com/thewilloftheshadow/thewilloftheshadow. My is-a.dev site is located at https://github.com/thewilloftheshadow/devsite, which would be https://thewilloftheshadow.github.io/devsite. However, because it's setup on the CNAME already, it redirects to https://shadow.is-a.dev, which has not been setup yet.

Actually it is how a GitHub Pages CNAME works. You need to have a website on https://thewilloftheshadow.github.io for us to merge it.

**Comment by thewilloftheshadow** [comment]
Why would I need a website for an unrelated thing? Can you explain how that works, am I just missing something?

**Comment by WilliamDavidHarrison** [comment]
> Why would I need a website for an unrelated thing? Can you explain how that works, am I just missing something?

It's just our requirements.

**Comment by thewilloftheshadow** [comment]
Where is that documented?

**Comment by WilliamDavidHarrison** [comment]
Docs

**Pull request closed without merging**
