### PR TITLE
Rename opulentloop.json to debjit.json

### PR DESCRIPTION
**Pull request by mystichronicle**
Domain name change from opulentloop.is-a.dev to debjit.is-a.dev
## Website Link/Preview
https://opulentloop.github.io

### CODE REVIEW

**Comment by cupglassDEV** [comment]
I cant see the preview, it redirects to https://is-a.dev

image

**Comment by opulentloop** [comment]
> I cant see the preview, it redirects to https://is-a.dev
> 
> image

Sorry for my mistake. Now the url is corrected.

**Comment by CuteDog5695** [comment]
This will be on standby since we are currently in a downtime, I'll approve it and will merge when downtime is finished.

**Review by iostpa — APPROVED** [review]

**Comment by cupglassDEV** [comment]
> This will be on standby since we are currently in a downtime, I'll approve it and will merge when downtime is finished.

but as i remember (again), my reply was before the downtime

correct me if im wrong

**Comment by opulentloop** [comment]
> > This will be on standby since we are currently in a downtime, I'll approve it and will merge when downtime is finished.
> 
> but as i remember (again), my reply was before the downtime
> 
> correct me if im wrong

No subdomains were redirecting to is-a.dev . Please approve this after the downtime is finished.

**Comment by mysticdebjit** [comment]
There was a mistake in my json code. I have fixed it now and created another pull request.

**Pull request closed without merging**
