### PR TITLE
added TXT record to badboy.json

### PR DESCRIPTION
**Pull request by s3mant**
**TXT** google verification

### CODE REVIEW

**Review by s3mant — COMMENTED** [review]
ok

**Review by s3mant — COMMENTED** [review]
ok nvm

**Review by MaskDuck — CHANGES_REQUESTED** [review]
unphoptulateny cname cant work with txt and txt cant work with cname

**Comment by MaskDuck** [comment]
*unfortunately

**Review by MaskDuck — COMMENTED** [review]
i wish i had power to merge it

**Review by MaskDuck — APPROVED** [review]

**Comment by Bad-Boy-Codes** [comment]
> i wish i had power to merge it

damn my api is down

**Review by TheBotlyNoob — APPROVED** [review]

**Pull request merged**
