### PR TITLE
Add my portfollio site

### PR DESCRIPTION
**Pull request by andrewstech**

### CODE REVIEW

**Review by MaskDuck — CHANGES_REQUESTED** [review]
the domain leads to a 404.

**Comment by andrewstech** [comment]
> the domain leads to a 404.

Sorry about that I have fixed it now.

**Review by MaskDuck — APPROVED** [review]
nice

**Comment by MaskDuck** [comment]
hi there @andrewstech, your pr have been merged!

now you have to config github pages. you can find instruction [here](https://github.com/is-a-dev/register/blob/main/docs/hosted-at/github-pages.md).

dont forget to leave this repo a star if you haven't!

if you need help, feel free to join our discord (link in readme) or open a github issue.

**Pull request merged**
