### PR TITLE
Register Subdomain: penguinmod

### PR DESCRIPTION
**Pull request by FreshPenguin112**
Added the domain: penguinmod

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
404

**Review by FreshPenguin112 — COMMENTED** [review]
change my email to "freshpenguin1@outlook.org"

**Comment by FreshPenguin112** [comment]
Can someone delete this?
It shows my personal email I don't want displayed to everyone

**Comment by FreshPenguin112** [comment]
I did the first commit it's still there

**Comment by FreshPenguin112** [comment]
Deleting this would get rid of this

**Comment by FreshPenguin112** [comment]
Wait you can't delete a pull request
WHY GH😭

**Pull request closed without merging**
