### PR TITLE
change username

### PR DESCRIPTION
**Pull request by iop3**
i changed my username :P

### CODE REVIEW

**Comment by LogSkele** [comment]
hold up,

```
[LogSkele.name]: The name of the file is invalid. It must be lowercased, alphanumeric and each component must be more than 2 characters long"
```
no wonder the check failed.

**Comment by mtgsquad** [comment]
Hi, @LogSkele. There's a bit of an issue with this PR, we need some sort of proof you owned the domain before, is there some sort of screenshot or way for us to verify this? @MaskDuck will try to assist you with this.

**Comment by LogSkele** [comment]
Look at my repos, for example https://github.com/LogSkele/diamondsword. Before I also had this and github will redirect you to the same site if you use my previous username https://github.com/iop3/diamondsword

**Comment by LogSkele** [comment]
And also my previous link, https://iop3.is-a.dev, works.
image

**Comment by LogSkele** [comment]
And if this helps too, #822

**Comment by MaskDuck** [comment]
@LogSkele pls send me an email to `maskduckuwu@gmail.com` using the email `iop3.is.epic@gmail.com`. 

the body of the email should content the link to this pr.

**Comment by LogSkele** [comment]
Sent.

**Review by hackermondev — APPROVED** [review]

**Pull request merged**
