### PR TITLE
BETA: Register _gitlab-pages-verification-code.meerkats.shays.is-a.dev

### PR DESCRIPTION
**Pull request by SHays24**
Added `_gitlab-pages-verification-code.meerkats.shays.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Comment by SHays24** [comment]
how come this isn't working, it should work right? its the same format for the domain as GH pages, is the GH pages format whitelisted or something?

**Review by wdhdev — APPROVED** [review]

**Comment by WilliamDavidHarrison** [comment]
> how come this isn't working, it should work right? its the same format for the domain as GH pages, is the GH pages format whitelisted or something?

It is because we don't support GitLab verification yet.
@phenax Can we add support for this?

**Comment by SHays24** [comment]
Keep alive pls

**Comment by wdhdev** [comment]
@phenax

**Pull request merged**
