### PR TITLE
add MX Support (willo.is-a.dev)

### PR DESCRIPTION
**Pull request by WilloIzCitron**
To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [ ] You're not using Vercel or Netlify.
- [ ] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [ ] The website is reachable.
- [ ] The CNAME record doesn't contain any slash.
- [ ] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

### CODE REVIEW

**Review by MaskDuck — DISMISSED** [review]
you can't use cname with mx, sorry :(

**Comment by WilloIzCitron** [comment]
oh i will create a domain again 😢

**Comment by WilloIzCitron** [comment]
i use url instead cname

**Comment by omxpro** [comment]
@WilloIzCitron you can use `A` ip's insted of `CNAME` as `A` supports `MX` records. to find your A ip join our discord server. Go to commands and do `/dig domain:willoizcitron.github.io` to find your `A` IP's. It will work with MX and i myself use it.

**Comment by WilloIzCitron** [comment]
image
i was dig my site, i check a ip on chrome at one and the result is 404

**Comment by WilloIzCitron** [comment]
ok done

**Review by mtgsquad — APPROVED** [review]

**Pull request merged**
