### PR TITLE
Registering my subdomain

### PR DESCRIPTION
**Pull request by AestraDev**
Anyone Please correct if I wrote something wrong...

### CODE REVIEW

**Comment by AbubakarKang** [comment]
You have to add a valid detail in CNAME. If you're going to add it later then might as well make a PR later.

**Comment by AestraDev** [comment]
Fine...

**Comment by AestraDev** [comment]
Adding CNAME

**Review by MaskDuck — CHANGES_REQUESTED** [review]
uh this is raising error + json structure is wrong

**Review by MaskDuck — DISMISSED** [review]
gud

**Review by MaskDuck — APPROVED** [review]
ci should pass rn

**Pull request merged**
