### PR TITLE
feat(domain): move to github pages

### PR DESCRIPTION
**Pull request by itsmenewbie03**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview
https://itsmenewbie03.github.io/

## NOTE
Sorry for the prank earlier now it's totally sfw
the source is available [here](https://github.com/itsmenewbie03/itsmenewbie03.github.io)

### CODE REVIEW

**Comment by 21Z** [comment]
You're permanently banned from using is-a.dev due to: Rickroll. jkjk

**Review by DEV-DIBSTER — APPROVED** [review]

**Comment by wdhdev** [comment]
Why was this approved? There is no site content, and before it literally redirected to a porn site. @DEV-DIBSTER @itsmenewbie03

**Comment by itsmenewbie03** [comment]
> Why was this approved? There is no site content, and before it literally redirected to a porn site. @DEV-DIBSTER @itsmenewbie03

I changed it to and sfw prank [source here](https://github.com/itsmenewbie03/itsmenewbie03.github.io/blob/main/index.html)

**Comment by wdhdev** [comment]
> > Why was this approved? There is no site content, and before it literally redirected to a porn site. @DEV-DIBSTER @itsmenewbie03
> 
> I changed it to an sfw prank [source here](https://github.com/itsmenewbie03/itsmenewbie03.github.io/blob/main/index.html?rgh-link-date=2024-06-17T23%3A28%3A37Z)

1. It's still a no content site.
2. Many of our maintainers (including me) are **minors**, and are NOT above the age to view that sort of content. It is not funny.

Your domain has been removed (ref: #14486) in violation of our terms of service and you will be blocked from our organisation.

**Pull request merged**
