### PR TITLE
Added parsa via is-a-dev-cli

### PR DESCRIPTION
**Pull request by xX-MoonWalker-Xx**
Added parsa via the CLI

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Server error

**Comment by xX-MoonWalker-Xx** [comment]
> Server error
yes the database got corrupted sadly, does it have to be fully functional?

**Comment by WilliamDavidHarrison** [comment]
> > Server error
> 
> yes the database got corrupted sadly, does it have to be fully functional?

Yes, unfortunately.

**Comment by xX-MoonWalker-Xx** [comment]
> > > Server error
> > 
> > 
> > yes the database got corrupted sadly, does it have to be fully functional?
> 
> Yes, unfortunately.

it is now fixed. can you please check?

**Review by wdhdev — DISMISSED** [review]

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
