### PR TITLE
madmusician.is-a.dev

### PR DESCRIPTION
**Pull request by dev-odf**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.

### CODE REVIEW

**Review by TheBotlyNoob — DISMISSED** [review]
fix your JSON.

also, some discrepancies: 
image
image
image
image

**Comment by TRIPLR1RRT** [comment]
Just add as it is

**Comment by TheBotlyNoob** [comment]
I can't. 
- A) You need to fix your JSON.
- B) Explain the discrepancies with the bot name and features

**Review by wdhdev — DISMISSED** [review]

**Comment by WilliamDavidHarrison** [comment]
> I can't.
> 
> * A) You need to fix the JSON.
> * B) Explain the discrepancies with the bot name and features.

I've fixed the JSON and the website is fine, I'm assuming they'll update it later.

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
