### PR TITLE
Remove yuko.json file and adding an email 

### PR DESCRIPTION
**Pull request by DreamLikeAmonster**
Screenshot_2024-09-18-06-10-51-131_com android chrome-edit

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.

### CODE REVIEW

**Comment by DreamLikeAmonster** [comment]
@DEV-DIBSTER

**Comment by DEV-DIBSTER** [comment]
Is there a reason you're deleting the domain file?

**Comment by DreamLikeAmonster** [comment]
cause u tell me to delete the file, maybe I am misunderstanding?

**Comment by DEV-DIBSTER** [comment]
Oh I already fix that for you.

**Comment by DreamLikeAmonster** [comment]
do i need to change/add something?

**Pull request closed without merging**
