### PR TITLE
Register Subdomain: muff

### PR DESCRIPTION
**Pull request by mansoor-roeen**
Added the domain: muff

### CODE REVIEW

**Comment by taha183** [comment]
I dont know if A record is correct but i prefer use CNAME if using github pages

**Review by MaskDuck — CHANGES_REQUESTED** [review]
your placeholder website seems to lead to an inaccessible webpage.

**Comment by lifeless-muffin** [comment]
> your placeholder website seems to lead to an inaccessible webpage.

Hey, sorry the site link that it had been hosted on was changed, though now it should be find

**Review by mansoor-roeen — COMMENTED** [review]
Placeholder site is now accessible

**Review by MaskDuck — APPROVED** [review]

**Pull request merged**
