### PR TITLE
Create this.json

### PR DESCRIPTION
**Pull request by DaInfLoop**
To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: https://haroon.repl.co/
- [x] The website is reachable.
- [ ] ~~The CNAME record doesn't contain any slash.~~
- [x] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

### CODE REVIEW

**Comment by taha183** [comment]
This name is valid for domain but ig replit will not be suitable for domain

**Comment by DaInfLoop** [comment]
> This name is valid for domain but ig replit will not be suitable for domain

I've used Replit on is-a.dev before (https://dainfloop.is-a.dev/). (I'm putting it as a URL record here because I've sent a PR to change that back to an email address #3322)

**Comment by DaInfLoop** [comment]
@is-a-dev/maintainers you guys have been merging other prs, but not both of my active ones

can i ask why?

**Review by wdhdev — APPROVED** [review]

**Comment by WilliamDavidHarrison** [comment]
> @is-a-dev/maintainers you guys have been merging other prs, but not both of my active ones
> 
> can i ask why?

Please don't mention maintainers.

**Review by MaskDuck — APPROVED** [review]

**Pull request merged**
