### PR TITLE
Create thomas-shelby.json

### PR DESCRIPTION
**Pull request by prbhanu**

### CODE REVIEW

**Review by hackermondev — DISMISSED** [review]

**Review by TheBotlyNoob — DISMISSED** [review]
There is nothing on the website...

**Comment by omxpro** [comment]
> There is nothing on the website...

It has all the contents now

**Comment by MouseMoosz** [comment]
> > There is nothing on the website...
> 
> It has all the contents now

The URL record still gives a 404

**Comment by prbhanu** [comment]
> > > There is nothing on the website...
> > 
> > 
> > It has all the contents now
> 
> The URL record still gives a 404

now it doesnt

**Review by hackermondev — APPROVED** [review]

**Pull request merged**
