### PR TITLE
Create samrat.json

### PR DESCRIPTION
**Pull request by ogsamrat**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.

### CODE REVIEW

**Review by iostpa — APPROVED** [review]
Seems fine to me I guess?

**Comment by ogsamrat** [comment]
> Seems fine to me I guess?

image
what's the issue?

**Comment by iostpa** [comment]
You need to connect the domain to your repository. You can go to [our documentation](https://docs.is-a.dev) to see how to connect it.

**Comment by ogsamrat** [comment]
check if [this](https://github.com/is-a-dev/register/pull/17940) works.

**Pull request merged**
