### PR TITLE
Pr To Remove Abusive Domains.

### PR DESCRIPTION
**Pull request by aloramiaa**

### CODE REVIEW

**Comment by orxngc** [comment]
leave the albinpraveen thing alone

**Comment by aloramiaa** [comment]
> leave the albinpraveen thing alone

https://albinpraveen.is-a.dev/portfolio2/projects.html 

Check this out. Provides Win 11 ISO , Phising Website Creator etc

**Comment by aloramiaa** [comment]
image

**Comment by orxngc** [comment]
ah i see

**Comment by orxngc** [comment]
i'll just merge this then

**Comment by orxngc** [comment]
@skysthelimitt @abidhasannir @ALBINPRAVEEN @BotolMehedi your domains have been removed for abuse

**Pull request merged**
