### PR TITLE
Added vivek.json

### PR DESCRIPTION
**Pull request by vivek-oraon**
To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [x] The website is reachable.
- [x] The CNAME record doesn't contain any slash.
- [x] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

### CODE REVIEW

**Comment by WilliamDavidHarrison** [comment]
@vivek-oraon If you are using GitHub pages, use a CNAME record instead. For example: vivek-oraon.github.io

**Comment by vivek-oraon** [comment]
I also want to add MX record and TXT record for email forwarding but as per documentation CNAME record will not support other records. What should I do? I followed this: #2950

**Comment by WilliamDavidHarrison** [comment]
> @WilliamDavidHarrison I also want to add MX record and TXT record for email forwarding but as per documentation CNAME record will not support other records. What should I do? I followed this: #2950

Use A records instead of a CNAME.

**Comment by vivek-oraon** [comment]
I am already using 'A' record. What else should I do?

**Comment by WilliamDavidHarrison** [comment]
You should be able to use MX and TXT records now.

**Comment by vivek-oraon** [comment]
Have you seen my PR? It have A , MX and TXT records.

**Comment by WilliamDavidHarrison** [comment]
> Have you seen my PR? It have A , MX and TXT records.

Oh, the  you'll be fine. There shouldn't be anything wrong with the PR.

**Review by MaskDuck — APPROVED** [review]

**Pull request merged**
