### PR TITLE
Create th.json

### PR DESCRIPTION
**Pull request by thaihwng**
## Requirements
All requirements listed must be met unless specified otherwise by a **maintainer**.
Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. (th.json)
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  
## Additional Information
I am using Cloudflare's NS records to enable custom domain configurations, specifically for setting up email services associated with my domain. This setup allows for better management of DNS settings and improved email handling capabilities, such as enhanced security, deliverability, and flexibility in configuring mail records.

## Website Link/Preview
thaihwng.github.io/h

### CODE REVIEW

**Comment by Satindar31** [comment]
Can't you simply use MX records? What does "better management of DNS settings and improved email handling capabilities" mean?

**Comment by thaihwng** [comment]
> Can't you simply use MX records?

So I can't use ns?

**Comment by Satindar31** [comment]
You can use NS records if you have a solid reason.

From your PR I saw that you only want to use email, which doesn't require NS records. You can use MX records for email. 

However if there is a specific use case which requires NS records. Briefly explain it here.

**Comment by thaihwng** [comment]
> You can use NS records if you have a solid reason.
> 
> From your PR I saw that you only want to use email, which doesn't require NS records. You can use MX records for email.
> 
> However if there is a specific use case which requires NS records. Briefly explain it here.

I know email only needs MX records, but using NS records makes it easier for me to manage everything. Besides email, I’m also using it for things like hosting a website - vercel.

**Comment by Satindar31** [comment]
- I don't want to create a pull request everytime I want to update my DNS records.
- Over 3,000 people have to, you can too.
From: [README](https://github.com/is-a-dev/register)

**Comment by thaihwng** [comment]
> * I don't want to create a pull request everytime I want to update my DNS records.
> * Over 3,000 people have to, you can too.
>   From: [README](https://github.com/is-a-dev/register)

I changed

**Comment by cupglassDEV** [comment]
> capabilities, such as enhanced security, deliverability, and flexibility in configuring mail records.

Btw if you want to know what, and whos going to get the NS permission:
1. Services that forcefully needed you to use NS for custom domains, like Aternos and playit.gg. Some, like cloudflare transform and cloudflare tunnel needed you to use a special NS with is-a.dev (because is-a.dev already listed on the Public Suffix List, so it treats *is-a.dev*, *co.kr*, *net.id* like the root of it)
OR
2. Some unsupported is-a.dev records that you desperately need it for your homeserver, like this https://github.com/is-a-dev/register/pull/16758

We don't accept responses like "oh, i want NS because it's easy to administer, than having to make a PR on Github", NO

We already made the https://registration.is-a.dev so the process can be a little bit easier, and it fails. Because some of y'all are sending invalid request to register the domain. Now you need to register using the manual one

**Comment by Stef-00012** [comment]
> I know email only needs MX records, but using NS records makes it easier for me to manage everything. Besides email, I’m also using it for things like hosting a website - vercel.

This isn't a good reason to get NS, anyway wait for @wdhdev's review

**Comment by Satindar31** [comment]
He isn't asking for NS records anymore. It's not just MX and TXT

**Comment by cupglassDEV** [comment]
We know, he changed to MX and TXT because from the startpoint, he tries to
use NS to do these all

**Comment by Satindar31** [comment]
With 55810a6318a6efb546249a2a0d6315be8a7a97ec you again went back to **NS** records...

**Pull request closed without merging**
