### PR TITLE
Create eviternal.json

### PR DESCRIPTION
**Pull request by EviternalOfficial**

### CODE REVIEW

**Review by mtgsquad — APPROVED** [review]

**Comment by EviternalOfficial** [comment]
dude wtf its pretty obvious you're literally trying to hog the domain after seeing me make it. bruh

**Comment by EviternalOfficial** [comment]
how is this even allowed bruh

**Comment by mtgsquad** [comment]
> dude wtf its pretty obvious you're literally trying to hog the domain after seeing me make it. bruh

first of all, i'm a maintainer, and i was waiting for checks to pass. are you dumb?

**Comment by mtgsquad** [comment]
your request is denied, appeal in the discord server: https://discord.gg/U3Z3dNhs

**Comment by EviternalOfficial** [comment]
> Yeah, I'm sorry about that my brother is an idiot.

**Comment by mtgsquad** [comment]
> > Yeah, I'm sorry about that my brother is an idiot.

Yeah, no. appeal in the discord.

**Comment by EviternalOfficial** [comment]
how to do that just appeal in #general?

**Comment by mtgsquad** [comment]
> how to do that just appeal in #general
Send it in help.

**Comment by mtgsquad** [comment]
Reopened after appeal: https://discord.com/channels/830872854677422150/946105325914828840/970007388054773770

**Review by mtgsquad — APPROVED** [review]
Approved again due to github being crap.

**Review by mtgsquad — APPROVED** [review]

**Pull request closed without merging**
