### PR TITLE
Create itsOmSarraf.json

### PR DESCRIPTION
**Pull request by itsOmSarraf**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://itsomsarraf.github.io

### CODE REVIEW

**Review by EtherealTheDev — CHANGES_REQUESTED** [review]
Remember to remove https:// from the URL record, and GitHub uses CNAME linking, a URL record just redirects to that URL

**Comment by EtherealTheDev** [comment]
```json
{
    "description": "My personal Website",
    "repo": "https://github.com/itsomsarraf/itsomsarraf.github.io",
    "owner": {
        "username": "itsOmSarraf",
        "email": "itsomsarraf@gmail.com"
    },
    "record": {
        "CNAME": "itsomsarraf.github.io"
    }
}
```

**Comment by itsOmSarraf** [comment]
thanks, though I had copied the format from someone's json ,which was merged a month back

**Comment by WilliamDavidHarrison** [comment]
You can use https://json-generator.is-a.dev to generate your JSON.

**Review by wdhdev — APPROVED** [review]

**Comment by itsOmSarraf** [comment]
Thank you

**Pull request merged**
