### PR TITLE
Create mrblockman.Json

### PR DESCRIPTION
**Pull request by MrBlockman**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

[mrblockman.github.io
](url)

### CODE REVIEW

**Review by iostpa — CHANGES_REQUESTED** [review]
Sorry but we don't support pirated sites. Even though its literally a old game.

**Comment by lungustefan** [comment]
If this gets accepted you might have Nintendo at your door

**Comment by lungustefan** [comment]
> If this gets accepted you might have Nintendo at your door

Pfew denied

**Comment by CuteDog5695** [comment]
> If this gets accepted you might have Nintendo at your door

#13650 v2

**Comment by Totallynotmwa** [comment]
💀💀💀

**Comment by Stef-00012** [comment]
> If this gets accepted you might have Nintendo at your door

fr

**Comment by lungustefan** [comment]
But wasn't it required?

**Comment by CuteDog5695** [comment]
When we used cPanel with our own scripts (?), yes. But now we use Cloudflare DNS via DNS Control, which is more lenient with the socials part.

**Comment by CuteDog5695** [comment]
For the email/discord part, I'm still not sure about that since William has merged PRs with just the username.

**Comment by lungustefan** [comment]
Got it

**Pull request closed without merging**
