### PR TITLE
BETA: Register yrrahevents.acronical.is-a.dev

### PR DESCRIPTION
**Pull request by AcronicalYT**
Added `yrrahevents.acronical.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Comment by orxngc** [comment]
Your site is empty.

**Comment by AcronicalYT** [comment]
Added some content, but I need to add mostly placeholder text until the events are announced

**Comment by triach-rold** [comment]
I can see some WIP text on the website now but it's still pretty barren, but it's reachable.

**Comment by AcronicalYT** [comment]
I've added all I can really add now, but it'll be more fleshed out in a few weeks

**Review by DEV-DIBSTER — APPROVED** [review]

**Pull request merged**
