### PR TITLE
Register haris.is-a.dev

### PR DESCRIPTION
**Pull request by HarisETH**
Added `haris` via the registration website.

### CODE REVIEW

**Review by wdhdev — APPROVED** [review]
We do not support Vercel, so I have updated your domain to redirect instead.

**Comment by HarisETH** [comment]
Can you redirect the site to https://haris.one instead ? please ?

**Comment by WilliamDavidHarrison** [comment]
> Can you redirect the site to https://haris.one instead ? please ?

Sure

**Comment by HarisETH** [comment]
Thanks alot !

**Pull request merged**
