### PR TITLE
Create aakashuuuu.json

### PR DESCRIPTION
**Pull request by itsAakashz**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.

### CODE REVIEW

**Comment by itsAakashz** [comment]
Anyone here?

**Review by iostpa — APPROVED** [review]
seems good to me

**Comment by CuteDog5695** [comment]
> Anyone here?

theres a thing called patience btw

**Comment by itsAakashz** [comment]
When this domain will start working?

**Pull request merged**
