### PR TITLE
Create aniruddh.json

### PR DESCRIPTION
**Pull request by aniruddhnishad**
### Requirements
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [x] The website is reachable.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### CODE REVIEW

**Review by wdhdev — COMMENTED** [review]
What do these IP's lead to?

**Comment by aniruddhnishad** [comment]
> What do these IP's lead to?

these are my vps ip addresses you can point to just this id: 23.94.14.190

**Comment by WilliamDavidHarrison** [comment]
> > What do these IP's lead to?
> 
> these are my vps ip addresses you can point to just this id: 23.94.14.190

Like what do they host I mean.

**Review by wdhdev — APPROVED** [review]

**Comment by WilliamDavidHarrison** [comment]
> hello ? my pull request is open since half a month. please do something

I can't merge PRs as I'm only a helper

**Review by MaskDuck — APPROVED** [review]

**Pull request merged**
