### PR TITLE
Create icm.json

### PR DESCRIPTION
**Pull request by ICM185**
Making my new website, im trying to get your subdomain

### CODE REVIEW

**Review by phenax — CHANGES_REQUESTED** [review]
CNAME has to be a **host name**. If you want a URL redirection, use URL instead of CNAME. If you want a CNAME record, remove everything but the host name.

**Comment by ICM185** [comment]
> CNAME has to be a **host name**. If you want a URL redirection, use URL instead of CNAME. If you want a CNAME record, remove everything but the host name.

So heyy, thank you for reviewing it, so i just change the CNAME part to URL right?

**Comment by phenax** [comment]
If you want a subdomain linked to your github pages website then change the value to just `icm185.github.io`. If you want a simple URL redirection then yes, changing `CNAME` to `URL` will do.

**Comment by ICM185** [comment]
> If you want a subdomain linked to your github pages website then change the value to just `icm185.github.io`. If you want a simple URL redirection then yes, changing `CNAME` to `URL` will do.

Done :)

**Comment by ICM185** [comment]
Is it ok now? :D

**Review by phenax — APPROVED** [review]

**Comment by ICM185** [comment]
Heyy, thank you for accepting my request, and i have a quick question,
Don't answer it if u don't want to.

Are you from kerala? Just asking because your name found relative.

**Pull request merged**
