### PR TITLE
Register www.mohan.is-a.dev

### PR DESCRIPTION
**Pull request by mohankumarpaluru**
Register www.mohan.is-a.dev with CNAME record pointing to mohan.is-a.dev.

### CODE REVIEW

**Comment by mohankumarpaluru** [comment]
> this domain points towards itself. kek

Hi there,

It seems that `www.mohan.is-a.dev` is currently inaccessible. That's why I'm trying to create an alias for it.

**Comment by orxngc** [comment]
> It seems that `www.mohan.is-a.dev` is currently inaccessible. That's why I'm trying to create an alias for it.

We do not support www subdomains.
https://mohan.is-a.dev _is_ accessible, though.

**Comment by mohankumarpaluru** [comment]
> We do not support www subdomains.
> https://mohan.is-a.dev _is_ accessible, though.

Yes, `mohan.is-a.dev` is accessible, but `www.mohan.is-a.dev` is not. I appreciate the free service you provide. If possible, could you share the reason why the ``www subdomain isn't available, even for nested subdomains? I'm just curious to understand better. Thank you!

**Comment by mohankumarpaluru** [comment]
got it thanks for the explanation, I'll close the PR

**Comment by mohankumarpaluru** [comment]
Hi @orxngc , now that www is allowed , can you please approve the PR

**Comment by orxngc** [comment]
yea

**Pull request merged**
