### PR TITLE
Added and modified files (Full description below)

### PR DESCRIPTION
**Pull request by whinee**
**ADDED**

- `domains/dc.whine.json`
- `domains/li.whine.json`

**CHANGED**

- Renamed `domains/deno.whine.json` to `domains/de.whine.json`
- Renamed `domains/projects.whine.json` to `domains/pr.whine.json`
- Modified `domains/whine.json` and `domains/whine.json`

### CODE REVIEW

**Comment by MaskDuck** [comment]
file name is invalid

**Review by MaskDuck — CHANGES_REQUESTED** [review]
pretty sure we arent alllowed to accept github pages verification

**Comment by whinee** [comment]
I removed the subdomains for github pages verification.

**Review by MaskDuck — APPROVED** [review]
not sus

**Pull request merged**
