### PR TITLE
Register itq.is-a.dev

### PR DESCRIPTION
**Pull request by devitq**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview
https://github.com/devitq/

### CODE REVIEW

**Comment by Real-Yash** [comment]
bro you have to use cname record url is not valid variable

**Comment by Real-Yash** [comment]
```
  {
    "repo": "https://github.com/username/repo",
    "owner": {
        "username": "username",
        "email": "youremailidhere"      
    },
    "record": {
        "CNAME": "username.github.io"
    }
}
```


something like this

**Comment by CuteDog5695** [comment]
> bro you have to use cname record url is not valid variable

???????
Bro we have URL records, why else would he put that record?

**Review by iostpa — APPROVED** [review]
Seems good to me

**Pull request merged**
