### PR TITLE
BETA: Register l7neg.is-a.dev

### PR DESCRIPTION
**Pull request by L7NEG**
Added `l7neg.is-a.dev` using the site.

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
We don't support Vercel.

**Comment by L7NEG** [comment]
Yes I see but I want to suggest to make a dns website with automatic api

**Comment by WilliamDavidHarrison** [comment]
We don't support Vercel on our domains unfortunately.

**Comment by L7NEG** [comment]
Ok np, thanks for the reply.

**Pull request closed without merging**
