### PR TITLE
Create theanonymous.hacker.json

### PR DESCRIPTION
**Pull request by TheDeveloper7878**

### CODE REVIEW

**Review by phenax — CHANGES_REQUESTED** [review]
This is in the wrong directory. Please move the file to `domains`.

Also, did you mean to use a CNAME record pointing to your github pages or a url redirection to your github pages website? If so, let us know since right now your subdomain will just redirect to the url specified which is the `thedeveloper` repo.

**Comment by TheDeveloper7878** [comment]
> This is in the wrong directory. Please move the file to `domains`.
> 
> Also, did you mean to use a CNAME record pointing to your github pages or a url redirection to your github pages website? If so, let us know since right now your subdomain will just redirect to the url specified which is the `thedeveloper` repo.

yes i meant to 
also what do u mean by wrong directory

**Comment by phenax** [comment]
You need to have your domain json file in the domains directory as mentioned in the README

**Comment by TheDeveloper7878** [comment]
> You need to have your domain json file in the domains directory as mentioned in the README

okkk

**Pull request closed without merging**
