### PR TITLE
 Add a verified domain

### PR DESCRIPTION
**Pull request by vncsmnl**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview
[vinicius.is-a.dev](https://vinicius.is-a.dev/)

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
https://github.com/is-a-dev/register/issues/6627#issuecomment-1666382002

**Comment by vncsmnl** [comment]
#6627

**Comment by WilliamDavidHarrison** [comment]
Read the comment I requested changes with.

**Comment by vncsmnl** [comment]
I updated the Json filename to _github-pages-challenge-vncsmnl.vinicius.json and I added the TXT id

**Comment by WilliamDavidHarrison** [comment]
You need a whole separate file for TXT verification. I have done it for you now, so don't worry.

**Review by wdhdev — APPROVED** [review]

**Comment by vncsmnl** [comment]
I understand thank you. Sorry for the double work.

**Comment by vncsmnl** [comment]
I understand thank you. Sorry for the double work.

**Pull request merged**
