### PR TITLE
Create coolify.json

### PR DESCRIPTION
**Pull request by UntoldGam**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.

### CODE REVIEW

**Comment by UntoldGam** [comment]
the correct port for the ip is 8000 to take you to the coolify service

**Comment by UntoldGam** [comment]
am i allowed to have this as a wildcard domain so *.coolify.is-a.dev
Coolify is a hosting website that the "root" coolify.is-a.dev domain would be running off of with the subdomains of the "root" being the websites that I host.
The documentation can be found here: https://coolify.io/docs/

**Review by VaibhavSys — CHANGES_REQUESTED** [review]
We do not allow hosting companies.

**Comment by TerraPlayz** [comment]
Inactive

**Pull request closed without merging**
