### PR TITLE
Add CNAME in domain config `sunny.json`

### PR DESCRIPTION
**Pull request by Sunny-unik**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

[sunny.is-a.dev](https://sunny.is-a.dev)

### CODE REVIEW

**Review by VaibhavSys — CHANGES_REQUESTED** [review]
CNAME cannot be used with other records.

**Comment by Sunny-unik** [comment]
@TheBotlyNoob & @YouFoundAlpha I want any of you or someone else to please review this PR. I know this PR is already assigned to @VaibhavSys but maybe he is busy somewhere so he has not reviewed my PR in the last two days.
My portfolio website and some other projects hosted on my GitHub pages have not been live for the last 5 days so any help from your side is appreciated.

**Review by YouFoundAlpha — APPROVED** [review]
Looks good to me

**Comment by YouFoundAlpha** [comment]
> @TheBotlyNoob & @YouFoundAlpha I want any of you or someone else to please review this PR. I know this PR is already assigned to @VaibhavSys but maybe he is busy somewhere so he has not reviewed my PR in the last two days.
> My portfolio website and some other projects hosted on my GitHub pages have not been live for the last 5 days so any help from your side is appreciated.

You'll just have to wait for a maintainer to merge it since I am not a maintainer

**Comment by Sunny-unik** [comment]
> You'll just have to wait for a maintainer to merge it since I am not a maintainer

Okay, Thanks @YouFoundAlpha

**Review by VaibhavSys — APPROVED** [review]

**Comment by VaibhavSys** [comment]
> @TheBotlyNoob & @YouFoundAlpha I want any of you or someone else to please review this PR. I know this PR is already assigned to @VaibhavSys but maybe he is busy somewhere so he has not reviewed my PR in the last two days. My portfolio website and some other projects hosted on my GitHub pages have not been live for the last 5 days so any help from your side is appreciated.

Sorry for the delay!

**Pull request merged**
