### PR TITLE
Update william.json

### PR DESCRIPTION
**Pull request by wdhdev**

### CODE REVIEW

**Comment by MaskDuck** [comment]
duplicate of the one is already merged. #2139

**Comment by WilliamDavidHarrison** [comment]
actually i have 2 subdomains

**Comment by MaskDuck** [comment]
aww sorry i thought it was duplicate.

**Comment by WilliamDavidHarrison** [comment]
no problem, can you merge commit?

**Review by MaskDuck — APPROVED** [review]

**Comment by MaskDuck** [comment]
(you're invited to join our server)

**Comment by WilliamDavidHarrison** [comment]
ill join the discord

**Pull request merged**
