### PR TITLE
yo

### PR DESCRIPTION
**Pull request by prisect**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

http://88.127.172.169/ (my server)

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please make a website

**Comment by kenkodima** [comment]
Ok, i will be redirecting it to my website later, could you make is online ?

**Review by wdhdev — APPROVED** [review]

**Comment by kenkodima** [comment]
Unable to connect

An error occurred during a connection to r3tr0vw.is-a.dev.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the web.

**Comment by WilliamDavidHarrison** [comment]
Please open an issue.

**Pull request merged**
