### PR TITLE
Update mqry.json

### PR DESCRIPTION
**Pull request by ssii4**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.

### CODE REVIEW

**Comment by mqry** [comment]
@WilliamDavidHarrison

**Review by wdhdev — CHANGES_REQUESTED** [review]
404 on website and repo

**Comment by mqry** [comment]
What do I do?

**Comment by WilliamDavidHarrison** [comment]
> What do I do?

Create the repo and upload your website.

**Comment by mqry** [comment]
im new to this, so how do i connect the repo to this ?

**Comment by WilliamDavidHarrison** [comment]
> im new to this, so how do i connect the repo to this ?

You need to create the repo then add your website.

**Comment by mqry** [comment]
> > im new to this, so how do i connect the repo to this ?
> 
> You need to create the repo then add your website.

I have created a repo and web

**Comment by mqry** [comment]
@WilliamDavidHarrison

**Review by wdhdev — APPROVED** [review]

**Comment by mqry** [comment]
It's showing 404 on website
@WilliamDavidHarrison

**Comment by WilliamDavidHarrison** [comment]
> It's showing 404 on website
> @WilliamDavidHarrison

You need to setup the domain on your repo.

- Go to your GitHub repository that you use for your is-a.dev domain.
- Click on the Settings tab.
- Click on the Pages link in the sidebar.
- In the custom domain option, enter the domain you registered.
- Check the `Enforce HTTPS` checkbox.
- Give your domain some time (~24 hours) for the changes to propagate.

**Comment by mqry** [comment]
No> > It's showing 404 on website
> 
> > @WilliamDavidHarrison
> 
> 
> 
> You need to setup the domain on your repo.
> 
> 
> 
> - Go to your GitHub repository that you use for your is-a.dev domain.
> 
> - Click on the Settings tab.
> 
> - Click on the Pages link in the sidebar.
> 
> - In the custom domain option, enter the domain you registered.
> 
> - Check the `Enforce HTTPS` checkbox.
> 
> - Give your domain some time (~24 hours) for the changes to propagate.
> 
> 
> 
> did those already, I guess I gotta wait

**Comment by mqry** [comment]
I've cleared my history so many times & cleared my cache, it was stuck on 404 now it's on the register web. Whenever I get the dns checked, it says that I don't have " the repo " connected when I have

**Comment by mqry** [comment]
@WilliamDavidHarrison

**Comment by WilliamDavidHarrison** [comment]
> I've cleared my history so many times & cleared my cache, it was stuck on 404 now it's on the register web. Whenever I get the dns checked, it says that I don't have " the repo " connected when I have 

I'm not sure, open an issue and a helper or another maintainer will help you.

**Pull request merged**
