### PR TITLE
Added z4xiVia is-a-dev-cli

### PR DESCRIPTION
**Pull request by carrved**
Added z4xivia the CLI

### CODE REVIEW

**Comment by z4xi** [comment]
used wrong record

**Comment by z4xi** [comment]
realized i didnt use the wrong record
also heres a preview:

**Review by wdhdev — APPROVED** [review]

**Comment by z4xi** [comment]
@WilliamDavidHarrison just asking, how do I make my subdomain stay as `z4xi.is-a.dev` and not change to my link I've inputted?

**Comment by WilliamDavidHarrison** [comment]
> @WilliamDavidHarrison just asking, how do I make my subdomain stay as `z4xi.is-a.dev` and not change to my link I've inputted?

It's the only way as we don't support Netlify.

**Comment by z4xi** [comment]
> > @WilliamDavidHarrison just asking, how do I make my subdomain stay as `z4xi.is-a.dev` and not change to my link I've inputted?
> 
> It's the only way as we don't support Netlify.

oh ok, thank you!

**Comment by WilliamDavidHarrison** [comment]
> > > @WilliamDavidHarrison just asking, how do I make my subdomain stay as `z4xi.is-a.dev` and not change to my link I've inputted?
> > 
> > It's the only way as we don't support Netlify.
> 
> oh ok, thank you!

Sorry for the inconvenience! 😀

**Pull request merged**
