### PR TITLE
Update jacob.json

### PR DESCRIPTION
**Pull request by IbrahimDevX**
Nobody was using this website and my friend wanted his own with his name, so I edited it in. I've made Ibrahim.is-a.dev before too

### CODE REVIEW

**Review by TheBotlyNoob — CHANGES_REQUESTED** [review]
You are taking this domain from another person...

**Comment by mtgsquad** [comment]
> You are taking this domain from another person...

Agreed.

**Comment by mtgsquad** [comment]
Just because someone else isn't using this domain, doesn't mean you can just come and take it. Let me know if you still want it and I can try contacting the person for you.

**Comment by mtgsquad** [comment]
> @IbrahimDevX well, turns out you can just call your friend to create a pull and make it himself.

I agree. If your friend wants a subdomain, please tell them to make a PR themselves.

**Comment by mtgsquad** [comment]
@IbrahimDevX, Please let me know if you would still like me to contact the owner on behalf of the `is-a.dev` team. Please respond to this comment in the next few days, otherwise I'll just close it.

**Comment by mtgsquad** [comment]
PR closed due to taking someone else's domain and then simply not responding.

**Pull request closed without merging**
