### PR TITLE
Register grusio.is-a.dev

### PR DESCRIPTION
**Pull request by mattiagrusio**
Added `grusio.is-a.dev` using the [CLI](https://www.npmjs.com/package/@is-a-dev/cli).

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
I can't reach your website

**Comment by mattiagrusio** [comment]
only port 2015 is opened for now

**Comment by WilliamDavidHarrison** [comment]
Can you send a screenshot of your website?

**Comment by mattiagrusio** [comment]
Il Dom 9 Apr 2023, 02:28 William Harrison ***@***.***> ha
scritto:

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
