### PR TITLE
Create theweebsamurai.json

### PR DESCRIPTION
**Pull request by TheWeebSamurai**
### Requirements
- [✓] You're not using Vercel or Netlify.
- [✓] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [✓] The website is reachable.
- [✓] The CNAME record doesn't contain `https://` or `/`.  
- [✓] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### Link to Website

theweebsamurai.is-a.dev
https://website-production-8d88.up.railway.app/

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Not enough content on website.

**Comment by TheWeebSamurai** [comment]
> Not enough content on website.

I am currently working on the website like shifting my main website thingy to this so I am developing the website rn

**Comment by WilliamDavidHarrison** [comment]
> > Not enough content on website.
> 
> I am currently working on the website like shifting my main website thingy to this so I am developing the website rn

You'll need to wait until then to get a domain

**Comment by TheWeebSamurai** [comment]
Ok

**Comment by TheBotlyNoob** [comment]
I'm closing this because of the large amounts of pull requests. You can make another PR later with the fixes if you want.

**Pull request closed without merging**
