### PR TITLE
Create adons.json

### PR DESCRIPTION
**Pull request by Adkimsm**
add adons

### CODE REVIEW

**Review by phenax — CHANGES_REQUESTED** [review]
Are you sure you meant to use a TXT record here? Please refer to the docs or ask if you're unsure about this.

**Comment by Adkinsm2020** [comment]
[Auto reply] Hello, I have something to do at the moment, I will deal 
with it later, please leave a message if you have anything need me.

**Comment by adkict** [comment]
[Auto reply] Hello, I have something to do at the moment, I will deal 
with it later, please leave a message if you have anything need me.

**Comment by Adkimsm** [comment]
[Auto reply] Hello, I have something to do at the moment, I will deal 
with it later, please leave a message if you have anything need me.

**Pull request closed without merging**
