### PR TITLE
Update tekno.json

### PR DESCRIPTION
**Pull request by EmanueleIannuzzi**
Updated record from CNAME to A record, for use with a personal VPS

### CODE REVIEW

**Comment by TeknoSenpai** [comment]
Please review my request, because it's really urgent.

**Comment by TeknoSenpai** [comment]
*Anybody?* @hackermondev @TheBotlyNoob ?

**Review by TheBotlyNoob — APPROVED** [review]
cool!

**Comment by TheBotlyNoob** [comment]
you shouldn't rush us, as we have lives too.

**Comment by TeknoSenpai** [comment]
@TheBotlyNoob yea sorry, my bad hehe, i don't have a life and i forget others have one 😅

jokes aside, i'm sorry, i didn't mean to rush anybody, i just needed the changes merged ASAP.

**Pull request merged**
