### PR TITLE
Update saxophone.json

### PR DESCRIPTION
**Pull request by ghost**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://k51qzi5uqu5dkufpe6tqnpkkgbd2ylzp27td5newwkx3nafsx87crm2zsy2f7o.ipns.dweb.link/

### CODE REVIEW

**Review by iostpa — CHANGES_REQUESTED** [review]
Can't seem to access the webpage, please send a screenshot of your website.

**Comment by saxophone-guy** [comment]
Updated. Can you recheck? @CuteDog5695

**Review by iostpa — APPROVED** [review]
Can't access site but based off the screenshot, it seems good to me

**Comment by saxophone-guy** [comment]
hm.. it's broken for some reason. might open a second PR in a few seconds

**Pull request merged**
