### PR TITLE
Small grammar fixes

### PR DESCRIPTION
**Pull request by wdhdev**

### CODE REVIEW

**Comment by LogSkele** [comment]
lmao dont think adding punctuation at the end of lists will get your pr merged

**Review by mtgsquad — APPROVED** [review]

**Comment by mtgsquad** [comment]
> lmao dont think adding punctuation at the end of lists will get your pr merged

William is a trusted member of is-a.dev's discord, and fixing grammar won't hurt.

**Comment by WilliamDavidHarrison** [comment]
> lmao dont think adding punctuation at the end of lists will get your pr merged

famous last words

**Comment by LogSkele** [comment]
xD yea

**Pull request merged**
