### PR TITLE
Something is breaking parts of my site and I think it's CF Proxy.

### PR DESCRIPTION
**Pull request by Yunexiz**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.

### CODE REVIEW

**Comment by wdhdev** [comment]
It loads perfectly fine for me on multiple devices, what do you mean by destroying your site?

**Comment by Yunexiz** [comment]
> It loads perfectly fine for me on multiple devices, what do you mean by destroying your site?

Rephrase: my site depends on a lot of bots - external servers loading images and stuff, like OpenAI. I noticed that none of these were able to load the CF protected version at is-a.dev but it works 100% at onrender.com, if you would take a look. You could quickly test this by sending the link in Discord and waiting for the embed. ai-y.onrender.com returns immediately but ai-y.is-a.dev is empty.

**Comment by Yunexiz** [comment]
The first part where I noticed was at an image viewing by AI. The external server kept returning error 400 image data not valid, which was probably just a block from CF.

**Comment by Yunexiz** [comment]
Oh also, the Render settings still say the domain needs verification when clicking verify. Something else is up with that.

**Pull request merged**
