### PR TITLE
Register joko.is-a.dev

### PR DESCRIPTION
**Pull request by AhNode**
Register joko.is-a.dev with A record pointing to 69.197.135.202.

### CODE REVIEW

**Comment by AhNode** [comment]
http://pnode2.danbot.host:9585/ web preview, the domain for my API

**Comment by AhNode** [comment]
http://pnode2.danbot.host:9585/

there is updated website with a content

**Comment by orxngc** [comment]
Lmao this is just a template, kek. Add something, even a "I'm orangc, here's my email, I like anime", will suffice.

**Comment by AhNode** [comment]
pnode2.danbot.host:9671

oke, maybe its good, just twibbon maker but not complete yet, just add the API but ther is preview

**Comment by AhNode** [comment]
approve plsss, for my homework:(

**Pull request merged**
