### PR TITLE
Create ninjaasmoke.json

### PR DESCRIPTION
**Pull request by ninjaasmoke**

### CODE REVIEW

**Review by phenax — DISMISSED** [review]
Unfortunately, vercel is not supported. We do support [Railway](https://railway.app/) tho.

**Comment by ninjaasmoke** [comment]
Updated the CNAME

**Review by MaskDuck — APPROVED** [review]
gud

**Comment by ninjaasmoke** [comment]
@phenax any further changes required?

**Comment by MaskDuck** [comment]
@ninjaasmoke sorry for the delay, you dont need to change

**Pull request merged**
