### PR TITLE
Updating nameservers for elnexreal.is-a.dev

### PR DESCRIPTION
**Pull request by pundang**
## Requirements
Unless explicitly specified otherwise by a **maintainer**, your domain must pass **all** of the indicated requirements below.
Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.
- [x] There is sufficient information at the `owner` field.  

## Link to Website
elnexreal.epizy.com

### CODE REVIEW

**Review by omsenjalia — DISMISSED** [review]
looks great to me

**Comment by elnexreal** [comment]
> looks great to me

noice :trollface:

**Review by omsenjalia — DISMISSED** [review]
👍👍

**Review by omsenjalia — APPROVED** [review]

**Comment by elnexreal** [comment]
OMG SORRY I FIXED IT 100% NOW... SORRY SORRY

**Comment by TerraPlayz** [comment]
> OMG SORRY I FIXED IT 100% NOW... SORRY SORRY

It's okay. 👍👍🔥🔥

**Review by wdhdev — CHANGES_REQUESTED** [review]
We don't support NS records.

**Comment by elnexreal** [comment]
> We don't support NS records.

what records do you support?

**Comment by elnexreal** [comment]
im seeing that CNAME works, my website has CNAME records support so im going to update it

**Comment by WilliamDavidHarrison** [comment]
> > We don't support NS records.
> 
> what records do you support?

Please read the [docs](https://is-a.dev/docs)

**Pull request closed without merging**
