### PR TITLE
BETA: Register scythe.is-a.dev

### PR DESCRIPTION
**Pull request by InariFoxed**
Added `scythe.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Comment by ScytheMediaTheDev** [comment]
how do i add a website for a portfolio, i just want to make this a website where i can introduce what i do and have an intro of myself, and i dont know what to set the record to, to do that, i dont know what the records after mean. 
Screenshot 2024-02-12 8 04 49 AM

**Comment by Grafaffel** [comment]
@ScytheMediaTheDev

You could host the site on GitHub Pages and add it via a CNAME Record. E.g YourName.github.io

**Review by iostpa — CHANGES_REQUESTED** [review]

**Comment by CuteDog5695** [comment]
> @ScytheMediaTheDev
> 
> You could host the site on GitHub Pages and add it via a CNAME Record. E.g YourName.github.io

he can also use Cloudflare Pages or any other hosting (except for Vercel and Netlify)

**Comment by ScytheMediaTheDev** [comment]
@Grafaffel @CuteDog5695 , what would be a valid MX record?

**Comment by CuteDog5695** [comment]
> @Grafaffel @CuteDog5695 , what would be a valid MX record?

MX is for email stuff, if you want a email forwarding service, use ImprovMX

**Pull request closed without merging**
