### PR TITLE
Register domain harshnj.is-a.dev

### PR DESCRIPTION
**Pull request by HarshNarayanJha**
## Requirements
- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric.
- [x] You have completed your website. (Not quite complete but ongoing)
- [x] The website is reachable.
- [x] You're not using Vercel.
- [x] The CNAME record doesn't contain `https://` or `/`. 
- [x] There is sufficient information at the `owner` field. 

## Website Link/Preview
Website [link](https://harshnarayanjha.github.io)
Preview:
image

### CODE REVIEW

**Comment by HarshNarayanJha** [comment]
I will also like to have an email forwarder on this domain to my email address. I have already signed up with forwardemail.net
How can I do this?
Do I need to create a new file or put the MX and TXT records in this file? May I create a new PR or can I make changes in this PR too?

**Comment by CuteDog5695** [comment]
If you want to add MX and TXT, you'd need to replace the CNAME records with A records for GitHub pages (which are 185.199.108.153, 185.199.109.153, 185.199.110.153, 185.199.111.153). Then you can add the MX and TXT records forwardemail.net wants you to add.
If you update the file in your fork, it will automatically be added in this PR so don't worry about making another PR.
Since you want to add a email forwarder to your domain, I won't merge this PR yet so that you have a decent amount of time adding those records.

**Comment by HarshNarayanJha** [comment]
Thanks for quick response! Looking up the internet, I understand why both CNAME and MX records can't be on the same domain! Therefore, my solutions include have a different subdomain like `mail.harshnj.is-a.dev` for mail records, but it would create a rather large email for use. Therefore, I will have both under this domain. I believe that I can register multiple subdomains in the future!
But still I can't understand how those A records, those ips, will point to my github pages page.

Another query (probably unrelated to this stuff), I read on the internet that forwarding emails is rather dangerous for various reasons. Another alternative is to add my domain's email address to gmail (and maybe to other email frontends) and use that interface for sending and receiving emails through my domain's email. Guides on this topic are confusing.
I still need to create a forwardmail account for MX records, but how can I disable forwarding and use it using gmail itself.
Pointers on this topic would be helpful

**Comment by HarshNarayanJha** [comment]
Nonetheless, I will update the file, and if everything seems right, please merge the PR! I will open new ones if I need to update anything!
Do I also need to do this [step](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages)? (on is-a.dev [docs](https://www.is-a.dev/docs/github-pages-verification/))

**Comment by CuteDog5695** [comment]
> Nonetheless, I will update the file, and if everything seems right, please merge the PR! I will open new ones if I need to update anything! Do I also need to do this [step](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages)? (on is-a.dev [docs](https://www.is-a.dev/docs/github-pages-verification/))

I think its recommended to verify your domain with GitHub

**Review by iostpa — APPROVED** [review]
Seems good to me now

**Pull request merged**
