### PR TITLE
Create pronoy2108.json

### PR DESCRIPTION
**Pull request by pacman2108**

### CODE REVIEW

**Comment by omxpro** [comment]
Please fill the pr comment with this as it's required:

To make our job easier, please spend time to review your application before submitting. 


#### Add a x between [] if you meet that requirement example `[x]`
- [ ] You're not using Vercel or Netlify.
- [ ] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [ ] The website is reachable.
- [ ] The CNAME record doesn't contain any slash.
- [ ] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

**Comment by pronoy2108** [comment]
> Please fill the pr comment with this as it's required:
> 
> To make our job easier, please spend time to review your application before submitting.
> 
> #### Add a x between [] if you meet that requirement example `[x]`
> * [ ]  You're not using Vercel or Netlify.
> * [ ]  You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
>   
>   * Link to website:
> * [ ]  The website is reachable.
> * [ ]  The CNAME record doesn't contain any slash.
> * [ ]  There's enough information at the `owner` field.
>   
>   * You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
> 
> #### Feel free to join our discord server for more updates or any help related to the service :D - [discord.gg/PZCGHz4RhQ](https://discord.gg/PZCGHz4RhQ)

image

**Comment by omxpro** [comment]
> > Please fill the pr comment with this as it's required:
> > To make our job easier, please spend time to review your application before submitting.
> > #### Add a x between [] if you meet that requirement example `[x]`
> > 
> > * [ ]   You're not using Vercel or Netlify.
> > * [ ]   You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
> >   
> >   * Link to website:
> > * [ ]   The website is reachable.
> > * [ ]   The CNAME record doesn't contain any slash.
> > * [ ]   There's enough information at the `owner` field.
> >   
> >   * You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
> > 
> > #### Feel free to join our discord server for more updates or any help related to the service :D - [discord.gg/PZCGHz4RhQ](https://discord.gg/PZCGHz4RhQ)
> 
> image

Sorry but: Vercel and Netlify is not currently available anymore. We don't support them. And your website isn't even reachable.

**Review by hackermondev — CHANGES_REQUESTED** [review]
Vercel is not supported.

**Comment by pronoy2108** [comment]
lorem ipsum

**Comment by pronoy2108** [comment]
lorem ipsum

**Comment by WilliamDavidHarrison** [comment]
@pronoy2108 Please use a different provider or close this PR.

**Comment by pronoy2108** [comment]
Ok

**Pull request closed without merging**
