### PR TITLE
@ahammednibras8 want to register his domain

### PR DESCRIPTION
**Pull request by ahammednibras8**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.

### CODE REVIEW

**Review by triach-rold — COMMENTED** [review]
Reachable but needs more content to be considered as "complete".

**Comment by ahammednibras8** [comment]
can i get the domain or not.

**Review by triach-rold — CHANGES_REQUESTED** [review]
You need to add more content to your page. It's literally just a placeholder right now at best. Make an actual page with a few paragraphs and a little more effort or just complete the website alltogether.

**Comment by ahammednibras8** [comment]
I think it's enough for get this domain.Currently i'am learning to code.So i created a simple html page.

**Review by Stef-DP — APPROVED** [review]
i think it's enough

**Pull request merged**
