### PR TITLE
BETA: Register thelittleoutside.is-a.dev

### PR DESCRIPTION
**Pull request by NiceSapien**
Added `thelittleoutside.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Comment by NiceSapien** [comment]
I just wanted a domain for my wife. Thanks!

**Comment by NiceSapien** [comment]
Record name: _vercel
content: vc-domain-verify=thelittleoutside.is-a.dev,0271c127cd03108dfd2d
Type: TXT

**Review by VaibhavSys — CHANGES_REQUESTED** [review]
Vercel isn't supported. Try Github Pages or Cloudflare Pages

**Comment by NiceSapien** [comment]
> Vercel isn't supported. Try Github Pages or Cloudflare Pages

Ok

**Review by wdhdev — CHANGES_REQUESTED** [review]
We do not support Vercel.

**Review by wdhdev — CHANGES_REQUESTED** [review]
We don't support Vercel.

**Comment by NiceSapien** [comment]
Oh, she made a PR of her own, np

**Pull request closed without merging**
