### PR TITLE
hi

### PR DESCRIPTION
**Pull request by ItzArman09**

### CODE REVIEW

**Review by hackermondev — CHANGES_REQUESTED** [review]
?????? You definitely don't need all these domains.

**Comment by ItzArman09** [comment]
I need

**Comment by MaskDuck** [comment]
you're claiming a bunch of domains... you won't use it anw

**Comment by MaskDuck** [comment]
we still have perms to reject whenever we like

**Comment by mtgsquad** [comment]
@ItzArman09 Claiming a bunch of domains all redirecting to arman.is-a.dev is technically hogging, since one can't have so many projects with such names, and second, you have to respond to our comments, otherwise your previous registration for arman.is-a.dev will also be removed.

**Comment by ItzArman09** [comment]
sorry i had exams so i was not able to reply, also sorry if this is not accepted. and btw can i have all the requests coming to *.arman.is-a.dev redirected to main page?

**Comment by mtgsquad** [comment]
> sorry i had exams so i was not able to reply, also sorry if this is not accepted. and btw can i have all the requests coming to *.arman.is-a.dev redirected to main page?

No, that is not allowed.

**Comment by ItzArman09** [comment]
ah ok thank you. You may close the pr

**Pull request closed without merging**
