### PR TITLE
Devan2051 patch 1

### PR DESCRIPTION
**Pull request by devan2051**
To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [x] You're not using Vercel or Netlify.
- [ ] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [x] The website is reachable.
- [x] The CNAME record doesn't contain any slash.
- [x] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Sorry, we don't support domain verification.

**Comment by devan2051** [comment]
How Can I provide this CNAME then? Its Showing me:

CNAME Label/ Host: etxnusylo7ik.www.devanmed.is-a.dev.
CNAME Destination/Target: gv-vn2mzywbrbt3o7.dv.googlehosted.com

**Comment by WilliamDavidHarrison** [comment]
> How Can I provide this CNAME then? Its Showing me:
> 
> CNAME Label/ Host: etxnusylo7ik.www.devanmed.is-a.dev. CNAME Destination/Target: gv-vn2mzywbrbt3o7.dv.googlehosted.com
> 
> Edit: I am using Google Sites for my Website...

You can't if it required verification.

**Comment by devan2051** [comment]
Okay, Thank you

**Pull request closed without merging**
