### PR TITLE
Create puneetgopinath.json

### PR DESCRIPTION
**Pull request by PuneetGopinath**
I added my subdomain, pls merge it after checking
I will improve my portfolio as I keep learning next.js, it is nothing big now 😅

Thanks,
Puneet Gopinath

### CODE REVIEW

**Review by mtgsquad — CHANGES_REQUESTED** [review]
CNAME can only have the domain!
Please remove the protocol and the subdirectories/routes.

**Comment by PuneetGopinath** [comment]
> use [Railway](https://railway.app?referralCode=jj)

My credits are already less ;-;
I can't host more things in railway

**Comment by TheBotlyNoob** [comment]
oof, is there any other hosting provider you can use other than Vercel or Netlify?

**Comment by PuneetGopinath** [comment]
Nah, when my Qovery credits are less, no other free host available

**Pull request closed without merging**
