### PR TITLE
BETA: Register cloudskies.is-a.dev

### PR DESCRIPTION
**Pull request by cloudcloudskies**
Added `cloudskies.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Review by Omxpro — APPROVED** [review]

**Review by iostpa — APPROVED** [review]

**Comment by CuteDog5695** [comment]
https://carrd.co/docs/sites/using-a-custom-domain

**Comment by Omxpro** [comment]
> How to setup this?

https://is-a.dev/docs

**Comment by CuteDog5695** [comment]
> > How to setup this?
> 
> https://is-a.dev/docs

they are using carrd.co, we dont have docs for that

**Comment by Omxpro** [comment]
👍👍

**Comment by CuteDog5695** [comment]
yes, but you'd need to edit the .json and make another PR
for what record you should use for redirecting check here https://www.is-a.dev/docs/domain-structure/

**Pull request merged**
