### PR TITLE
Update light.json

### PR DESCRIPTION
**Pull request by s3mant**
I decided to change my name
my previous name: Bad Boy Codes

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
You don't own this domain. I checked the edit history and it shows the user `EvaZeVolt` (this updates even if you change your GitHub username).

**Comment by SemantCodes** [comment]
> You don't own this domain. I checked the edit history and it shows the user `EvaZeVolt` (this updates even if you change your GitHub username).

that user haven't used their domain plus they aren't answering their emails either

**Comment by WilliamDavidHarrison** [comment]
> > You don't own this domain. I checked the edit history and it shows the user `EvaZeVolt` (this updates even if you change your GitHub username).
> 
> that user haven't used their domain plus they aren't answering their emails either

Sorry, they'll have to confirm the change.

@EvaZeVolt do you approve this change?

**Comment by SemantCodes** [comment]
> > > You don't own this domain. I checked the edit history and it shows the user `EvaZeVolt` (this updates even if you change your GitHub username).
> > 
> > 
> > that user haven't used their domain plus they aren't answering their emails either
> 
> Sorry, they'll have to confirm the change.
> 
> @EvaZeVolt do you approve this change?

nvm, I've decided to not use this domain.

**Pull request closed without merging**
