### PR TITLE
Update krvishal.json

### PR DESCRIPTION
**Pull request by imshvishal**
### Requirements
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [x] The website is reachable.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### CODE REVIEW

**Review by wdhdev — APPROVED** [review]

**Comment by TheGeekDex** [comment]
Why hasn't it been merged even after approval?

**Comment by TheGeekDex** [comment]
@WilliamDavidHarrison , Why hasn't it been merged even after approval?

**Comment by WilliamDavidHarrison** [comment]
> @WilliamDavidHarrison , Why hasn't it been merged even after approval?

I cannot merge PRs as I'm only a helper. Please wait for a maintainer to merge it.

**Comment by TheGeekDex** [comment]
> > @WilliamDavidHarrison , Why hasn't it been merged even after approval?
> 
> I cannot merge PRs as I'm only a helper. Please wait for a maintainer to merge it.

ohh, i see. Thanks btw ;)

**Comment by WilliamDavidHarrison** [comment]
> > > @WilliamDavidHarrison , Why hasn't it been merged even after approval?
> > 
> > 
> > I cannot merge PRs as I'm only a helper. Please wait for a maintainer to merge it.
> 
> ohh, i see. Thanks btw ;)

Sorry for the confusion 😄

**Comment by TheGeekDex** [comment]
> > > > @WilliamDavidHarrison , Why hasn't it been merged even after approval?
> > > 
> > > 
> > > I cannot merge PRs as I'm only a helper. Please wait for a maintainer to merge it.
> > 
> > 
> > ohh, i see. Thanks btw ;)
> 
> Sorry for the confusion 😄

You need not to sorry, it was my fault that i got confused.., you are doing great. :)

**Comment by TheGeekDex** [comment]
Still Waiting ;(

**Comment by WilliamDavidHarrison** [comment]
> Still Waiting ;(

I can't merge PR's.

**Comment by imshvishal** [comment]
@TheBotlyNoob Hey, please help me with this commit as well. I am waiting for its approval from a long time.

**Review by MaskDuck — APPROVED** [review]

**Pull request merged**
