### PR TITLE
Create hypermusic.json

### PR DESCRIPTION
**Pull request by whoisjayd**

### CODE REVIEW

**Review by mtgsquad — DISMISSED** [review]
Your file name should be `hypermusic.json`, not just `hypermusic.`

**Review by MaskDuck — APPROVED** [review]

**Comment by MaskDuck** [comment]
both, yes, theres a limit that you can only create ∞ sites.

**Comment by Git-Jaydeep** [comment]
image

Is this possible?
😶 Hope So

**Comment by Git-Jaydeep** [comment]
Hi 👋🏻
image
Is this possible?
I need this for google workspace domain verification.

**Pull request merged**
