### PR TITLE
jetus domain, covering for #603

### PR DESCRIPTION
**Pull request by TheBotlyNoob**
fixed up Dev-Jetus' repo so he can have his sub-domain

### CODE REVIEW

**Comment by hackermondev** [comment]
uh
shouldn't he be doing this? not u

**Review by hackermondev — CHANGES_REQUESTED** [review]
the github pages setup is incorrect. the repo name must be ``dev-jetus.github.io``

**Comment by TheBotlyNoob** [comment]
>shouldn't he be doing this? not u

If he doesn't want me to, then I can close it, I just think hes taking too long in making the changes...

**Comment by TheBotlyNoob** [comment]
@hackermondev Fixed the repo

**Review by hackermondev — APPROVED** [review]

**Pull request closed without merging**
