### PR TITLE
Register Subdomain: anthony2be-blog

### PR DESCRIPTION
**Pull request by Anthony2be**
Added the domain: anthony2be-blog

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please add more content to your website

**Comment by Anthony2be** [comment]
> Please add more content to your website

I'm planning to

**Comment by JewishLewish** [comment]
Hi Anthony!

**Comment by Anthony2be** [comment]
> > > Please add more content to your website
> > 
> > 
> > I'm planning to
> 
> We have to wait until then.

but you approve my other site which literally has less content 😭

**Comment by Anthony2be** [comment]
actually wait im gonna close this and just transfer my old domain to the new one

**Comment by WilliamDavidHarrison** [comment]
Ok

**Pull request closed without merging**
