### PR TITLE
Create community.nziie.json

### PR DESCRIPTION
**Pull request by Nzii3**
### Requirements
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [x] The website is reachable.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### Link to Website
https://nziiecommunity.freeflarum.com
to be: `https://community.nziie.is-a.dev`

### CODE REVIEW

**Review by wdhdev — APPROVED** [review]

**Comment by Nzii3** [comment]
Is someone able to review?

**Comment by Nzii3** [comment]
Hello??

**Review by wdhdev — APPROVED** [review]

**Comment by Nzii3** [comment]
But it’s still not merged :/

**Review by Server-Manager-Dev-Team — APPROVED** [review]

**Comment by Nzii3** [comment]
@MaskDuck

**Comment by Nzii3** [comment]
bump

**Comment by Nzii3** [comment]
@MaskDuck are you available? I’ve been waiting a long time :/

**Comment by Nzii3** [comment]
bruh it’s been 10 days

**Comment by Nzii3** [comment]
> > bruh it’s been 10 days
> 
> i used to wait longer for my domain, i'm on break/exams rn so i don't check github much

oh ok

**Pull request closed without merging**
