### PR TITLE
Register play-prozt.is-a.dev

### PR DESCRIPTION
**Pull request by pxldevv**
Added `play-prozt.is-a.dev` using the [CLI](https://www.npmjs.com/package/@is-a-dev/cli).

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
We don't support TXT verification.

**Comment by Techpro709** [comment]
why not, isn't it just a txt record though?

**Comment by WilliamDavidHarrison** [comment]
It verifies that you own the domain which is why we cannot allow it.

**Comment by Techpro709** [comment]
I see, the way this works (correct me if I am wrong) is that it checks that you own the SUB domain. Honestly even if it checks for the whole domain, i don't know why you would care anyways. I can only register subdomains by submitting PR. I just need minehut (minecraft hosting) to know that I can forward people from the domain to the minecraft server. 

Honestly that is how most places work for domains. If this does go against your TOS thats fine, I want to find out if there is a way to work around this, or make an exception.

**Comment by WilliamDavidHarrison** [comment]
Unfortunately most TXT verification systems then verify the whole domain so we cannot allow it at all.

**Comment by Techpro709** [comment]
Do you think you could check if minehut does this. I really would like this domain for this minecraft server.

**Comment by WilliamDavidHarrison** [comment]
I cannot check that as I do not personally use MineHut.

**Pull request closed without merging**
