### PR TITLE
Add my website domain

### PR DESCRIPTION
**Pull request by RLX-OP**

### CODE REVIEW

**Comment by RLX-OP** [comment]
Pls add I need my domain asap :8

**Comment by RLX-OP** [comment]
I am in a need of this domain

**Comment by RLX-OP** [comment]
Ahhh, come on tell me what's wrong so I can correct it and get my domain it's almost 2 days.
:(

**Comment by RLX-OP** [comment]
Now pls everything is good I think so

**Review by phenax — CHANGES_REQUESTED** [review]
Sorry for the delay. (#1529). You cannot add CNAME and A record for the same domain. If you want to use github pages, CNAME alone is enough.

**Comment by RLX-OP** [comment]
@phenax I am closing this pls see latest one project that is full bug free

**Pull request closed without merging**
