### PR TITLE
BETA: Register ved.is-a.dev

### PR DESCRIPTION
**Pull request by ved-patel226**
Added `ved.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Review by ved-patel226 — COMMENTED** [review]
s

**Comment by ved-patel226** [comment]
how long does it take to review

**Review by Stef-DP — APPROVED** [review]

**Comment by Stef-00012** [comment]
> how long does it take to review

it can take a few mins as it can take spme days, everything is done manually, we're not robots

**Comment by ved-patel226** [comment]
oh sorry bout that i thought there was a bot

**Pull request merged**
