### PR TITLE
Register Subdomain: Mahesh

### PR DESCRIPTION
**Pull request by ghost**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
I can't reach your website

**Review by wdhdev — CHANGES_REQUESTED** [review]
Still can't reach your website

**Comment by MaheshTheDeveloper** [comment]
Now try it should work

**Comment by MaheshTheDeveloper** [comment]
The website is live... at that time I was working on the site thought it will take time for you to come

**Comment by MaheshTheDeveloper** [comment]
@MaskDuck or @WilliamDavidHarrison

**Comment by MaheshTheDeveloper** [comment]
Or do I have to re-open pull request...?

**Comment by MaheshTheDeveloper** [comment]
I'll re-open the pull request...

**Pull request closed without merging**
