### PR TITLE
BETA: Register shiva-vijai.is-a.dev

### PR DESCRIPTION
**Pull request by Shiva-Vijai**
Added `shiva-vijai.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Review by PinkLittleKitty — APPROVED** [review]

**Review by PinkLittleKitty — CHANGES_REQUESTED** [review]
Nvm

**Review by PinkLittleKitty — APPROVED** [review]

**Review by Shiva-Vijai — COMMENTED** [review]
i updated record to CNAME

**Review by iostpa — APPROVED** [review]
seems good to me

**Comment by CuteDog5695** [comment]
oh btw closing and reopenning PR isnt recommended

**Pull request merged**
