### PR TITLE
Register karim.is-a.dev

### PR DESCRIPTION
**Pull request by k-amhaz**
Added `karim.is-a.dev` using the [CLI](https://www.npmjs.com/package/@is-a-dev/cli).

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please use a valid record.

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please use a valid record

**Comment by k-amhaz** [comment]
What can I use as a valid record

**Comment by WilliamDavidHarrison** [comment]
A record which points to your website.

**Pull request closed without merging**
