### PR TITLE
Create agam778.json

### PR DESCRIPTION
**Pull request by agam778**

### CODE REVIEW

**Review by hackermondev — CHANGES_REQUESTED** [review]
CNAME cannot be URL.

**Comment by agam778** [comment]
Fixed

**Comment by agam778** [comment]
@hackermondev

**Review by hackermondev — APPROVED** [review]

**Comment by agam778** [comment]
So when will you merge this PR?

**Review by TheBotlyNoob — APPROVED** [review]
now

**Comment by agam778** [comment]
@TheBotlyNoob @hackermondev Domain is still not working

**Comment by agam778** [comment]
image
It is showing this now @hackermondev @TheBotlyNoob

**Comment by agam778** [comment]
@hackermondev @TheBotlyNoob Please answer

**Comment by hackermondev** [comment]
@agam778 This is a known issue. Please refer to https://github.com/is-a-dev/register/issues/741#issuecomment-843877764 on how to fix it.

**Comment by agam778** [comment]
image
But i get this error

**Comment by hackermondev** [comment]
Yeah for some reason Vercel has that error. You might need to use another hosting provider or change the record on your domain to redirect to your Vercel site instead of using it as a CNAME

**Comment by agam778** [comment]
Will netlify work?

**Comment by hackermondev** [comment]
Yeah I think so

**Comment by agam778** [comment]
Ok wait a sec i'll try

**Comment by agam778** [comment]
Do i have to create a new PR?

**Comment by hackermondev** [comment]
yes

**Comment by agam778** [comment]
K

**Pull request merged**
