### PR TITLE
Added qxb3.json

### PR DESCRIPTION
**Pull request by qxb3**

### CODE REVIEW

**Review by MaskDuck — APPROVED** [review]
n01c3

**Comment by MaskDuck** [comment]
hi @qxb3 

now you need to config railway, please add `qxb3.is-a.dev` into your railway custom domain.

if you didnt star this repo pls star

if you need help feel free to join our discord (invite in readme) or create a gh issue.

**Comment by qxb3** [comment]
@MaskDuck Done, its working now thank you! 🥳

**Comment by qxb3** [comment]
okay

**Pull request merged**
