### PR TITLE
Create Willy.json

### PR DESCRIPTION
**Pull request by xrap1dx**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

not made website yet once I get it I’ll proxy to DBH & use it

https://discord.com/channels/830872854677422150/1271417154776072235/1271421310760783903

### CODE REVIEW

**Comment by wdhdev** [comment]
Impersonation of me!!!

**Comment by orxngc** [comment]
Odear?! Imposta

**Comment by RyanW15** [comment]
The site won’t be accessible cause I need the damn domain! @wdhdev It is actually gonna be ur fan page (:

**Comment by xrap1dx** [comment]
@wdhdev it is a fan page 4 you.

also the site won’t be accessible cuz I need the domain for DBH proxy.

**Comment by xrap1dx** [comment]
?? @MaskDuck

**Comment by omsenjalia** [comment]
@xrap1dx please send a preview of your website/link to your DBH domain or link using one of the DBH provided domains to let us look at your website. Otherwise the pr cannot be merged without a preview

**Pull request closed without merging**
