### PR TITLE
Register kokoapi.is-a.dev

### PR DESCRIPTION
**Pull request by kokofixcomputers**
Register kokoapi.is-a.dev with A record pointing to 45.90.12.32.

### CODE REVIEW

**Comment by kokofixcomputers** [comment]
Screenshot 2024-08-05 at 10 11 45 AM
Do not think this is inaccessible just by pasting the ip in the browser!!!!! I have to manually add this subdomain into my hosting service later as right now it says That domain does not point to this server. Make sure your A record is set to 45.90.12.32. and doesn't let me add

**Comment by kokofixcomputers** [comment]
# Read above before declining ^^^^^^^^^^^^^

**Review by iostpa — APPROVED** [review]
Seems good to me

**Comment by kokofixcomputers** [comment]
Thanks!

**Pull request merged**
