### PR TITLE
wbalaile is-a.dev registration

### PR DESCRIPTION
**Pull request by 6alaile**
How do I point to a specific subdomain on my website ? All the A records are the same and the subdomain does not have a CNAME record.

### CODE REVIEW

**Comment by mtgsquad** [comment]
If you want to point to a subdomain on a pre-existinf site, just use CNAME as shown in our guide, for redirecting to thr subdomain use a URL record.

**Comment by wilby-mj** [comment]
The subdomain doesn't have a CNAME, do I just add one ?

**Comment by wilby-mj** [comment]
Hope this works.

**Review by mtgsquad — APPROVED** [review]
Seems good.

**Pull request merged**
