### PR TITLE
Updated records

### PR DESCRIPTION
**Pull request by demonitize**
Replaced redirect with type A record for glitch because of course i use glitch

### CODE REVIEW

**Review by hackermondev — CHANGES_REQUESTED** [review]
TXT records are not supported. You probably don't need them anyways so you can remove them.

**Comment by demonitize** [comment]
I'm using TXT for ImprovMX. also the docs state that you can use TXT records, but only one

**Review by demonitize — COMMENTED** [review]
removed txt and mx records from countdown subdomain as i already have them on the main domain

**Comment by demonitize** [comment]
@hackermondev @TheBotlyNoob I have submitted the changes that have yet to be reviewed, I would remove the `Pending Changes` tag but I am unable to

**Pull request closed without merging**
