### PR TITLE
create syahirAmali.json

### PR DESCRIPTION
**Pull request by syahirAmali**

### CODE REVIEW

**Review by MaskDuck — APPROVED** [review]
not sus

**Review by MaskDuck — CHANGES_REQUESTED** [review]
file name should be lowercase.

**Review by AbubakarKang — DISMISSED** [review]

**Comment by syahirAmali** [comment]
renamed file to lowecase @MaskDuck

**Comment by MaskDuck** [comment]
cname also

**Comment by syahirAmali** [comment]
Updated

**Review by MaskDuck — APPROVED** [review]
not sus

now go config the gh pages, you can find how at the docs.

*btw dont forget to star the repo*

**Pull request merged**
