### PR TITLE
Update abdessattar.json

### PR DESCRIPTION
**Pull request by abdessattar23**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview
https://abdessattar23.github.io

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Why does your website require webcam access?

**Comment by CuteDog5695** [comment]
Also shows for me that the website needed webcam access.

**Comment by wdhdev** [comment]
Yeah, that is extremely weird and not how you go about removing bots. Also, who really cares if bots go to your website, it's not really affecting anyone, worst case scenario just add a captcha to enter the site.

**Comment by abdessattar23** [comment]
@wdhdev I just chosed that way lol hhh anyway i have removed it you can check again please

**Comment by wdhdev** [comment]
It's an invasion of privacy if anything. I won't be approving this domain. Any existing domains you own will be removed.

**Comment by CuteDog5695** [comment]
Closing PR now, your domains have been removed now. Maybe next time when you use a free subdomain service you make sure your site doesn't try to spy on people?

**Pull request closed without merging**
