### PR TITLE
Register tobez.is-a.dev

### PR DESCRIPTION
**Pull request by tobezdev**
Added `tobez.is-a.dev` using the [CLI](https://www.npmjs.com/package/@is-a-dev/cli).

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please complete your website

**Comment by TobezDev** [comment]
Is now complete.

**Review by wdhdev — CHANGES_REQUESTED** [review]
I can't reach your website now.

**Comment by TobezDev** [comment]
Works fine for me. It may be that the DNS is still updating for some regions. Give it a couple of hours and have another look. You can also check the status at https://status.tobez.dev

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
