### PR TITLE
Register bob.is-a.dev

### PR DESCRIPTION
**Pull request by Rubinskiy**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://rubinskiy.github.io//

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please create a website.

**Comment by Rubinskiy** [comment]
> Please create a website.

My GitHub pages website is reachable at https://rubinskiy.github.io/

**Comment by WilliamDavidHarrison** [comment]
You need to add actual content to it.

**Comment by Rubinskiy** [comment]
> You need to add actual content to it.

I have added some more content

**Review by wdhdev — DISMISSED** [review]

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
