### PR TITLE
Create nyan.json

### PR DESCRIPTION
**Pull request by aeongdesu**

### CODE REVIEW

**Review by omsenjalia — CHANGES_REQUESTED** [review]
Your "discord" is missing a :

**Comment by aeongdesu** [comment]
@omxpro , thank you for noticing me!

**Comment by omxpro** [comment]
> @omxpro , thank you for noticing me!

No problem

**Review by omsenjalia — APPROVED** [review]
👍

**Review by mtgsquad — APPROVED** [review]

**Pull request merged**
