### PR TITLE
Create lejhand.json

### PR DESCRIPTION
**Pull request by LejhandG**

### CODE REVIEW

**Review by TheBotlyNoob — APPROVED** [review]
nice, I like the style, it looks nice!

**Comment by LejhandGamingYT** [comment]
Thanks 🙏

**Comment by LejhandGamingYT** [comment]
It's giving me an error that subdomain is not properly configured :c

**Comment by TheBotlyNoob** [comment]
> It's giving me an error that subdomain is not properly configured :c

its not properly configured because the PR has not been merged. try reverting to a previous commit, because either way if you redirect to the is-a.dev domain then you wont be able to see the website that _you_ created.

**Comment by LejhandGamingYT** [comment]
I am rebuilding the website

**Pull request closed without merging**
