### PR TITLE
Create mijhelt.json

### PR DESCRIPTION
**Pull request by ejrv**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

+ Discord: ejrv#2738

## Website Link/Preview

https://mijhelt.github.io/

### CODE REVIEW

**Review by wdhdev — APPROVED** [review]

**Comment by ejrv** [comment]
image
server not found

**Comment by AutumnVN** [comment]
> server not found

it's mijhelt.is-a.dev not mijhelt-is-a.dev

**Comment by ejrv** [comment]
> > server not found
> 
> it's mijhelt.is-a.dev not mijhelt-is-a.dev

oh yeah misstype sorry

**Comment by ejrv** [comment]
image
now i have this problem

**Comment by AutumnVN** [comment]
did you set custom domain in your repo settings

**Comment by ejrv** [comment]
> did you set custom domain in your repo settings

no

**Comment by AutumnVN** [comment]
so just set it 🤷‍♂️
read configuring https://www.is-a.dev/docs/github_pages/

**Pull request merged**
