### PR TITLE
Create _vercel.victoria.json

### PR DESCRIPTION
**Pull request by iTahseen**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://viktoriaa.vercel.app

### CODE REVIEW

**Review by iostpa — CHANGES_REQUESTED** [review]
This is not how you use Vercel with your is-a.dev domain. Please read our documentation about how to do it.

**Comment by iTahseen** [comment]
updated code for verification, sorry I made mistake at first

**Comment by cupglassDEV** [comment]
> updated code for verification, sorry I made mistake at first

@iTahseen 

Wheres `victoria.json`? You prob need that. Not only `_vercel.victoria.json`

PLEASE FOR THE LOVE OF GOD, read the DOCS https://is-a.dev/docs/vercel

**Comment by iTahseen** [comment]
my vercel.json file is here https://github.com/is-a-dev/register/pull/17034
I'm sorry for bothering you guys

**Pull request closed without merging**
