### PR TITLE
Create _github-pages-challenge-uuphoria2.uuphoria2.json

### PR DESCRIPTION
**Pull request by queenkoopa8500**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview
https://uuphoria2.github.io

### CODE REVIEW

**Comment by uuphoria2** [comment]
@DEV-DIBSTER Please review this :+1:.

**Review by triach-rold — CHANGES_REQUESTED** [review]
No CNAME ?

**Comment by CuteDog5695** [comment]
> No CNAME ?

this one is txt verification for github pages

**Review by iostpa — APPROVED** [review]
seems good to me

**Pull request merged**
