### PR TITLE
Register arif.is-a.dev

### PR DESCRIPTION
**Pull request by nexuls**
Added `arif.is-a.dev` using the [CLI](https://www.npmjs.com/package/@is-a-dev/cli).

### CODE REVIEW

**Comment by EtherealTheDev** [comment]
We dont support TXT records I believe

**Review by wdhdev — CHANGES_REQUESTED** [review]
We don't support TXT verification

**Comment by NeuroNexul** [comment]
But vercel is showing me the option to add TXT records only.

image

**Comment by WilliamDavidHarrison** [comment]
We don't support Vercel due to this issue. We do support Cloudflare Pages, GitHub Pages, Railway, etc though.

**Pull request closed without merging**
