### PR TITLE
Adding a TXT record

### PR DESCRIPTION
**Pull request by Tanish2002**
URL redirection didn't work so trying the other solution from #404

### CODE REVIEW

**Comment by Tanish2002** [comment]
https://github.com/is-a-dev/register/issues/404#issuecomment-726644158
Trying out this solution ^

**Comment by phenax** [comment]
Give it some time. The change hasn't reflected yet. URL redirection doesn't need a TXT validation or any kind of configuration in your repo.

**Comment by phenax** [comment]
The changes have reflected. Closing this issue.

**Comment by Tanish2002** [comment]
Thanks and I'm sorry, I guess I should learn how to wait :pensive:

**Pull request closed without merging**
