### PR TITLE
feat: new user

### PR DESCRIPTION
**Pull request by TemurbekRuziyev**
To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [x] The website is reachable.
- [x] The CNAME record doesn't contain any slash.
- [x] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

### CODE REVIEW

**Review by iop3 — CHANGES_REQUESTED** [review]
maybe and a bit more in the website and what are all thoes xml  and iml files?

**Comment by AceyDoCodes** [comment]
You cant have MX with CNAME :/ also i dont think you can have CNAME with A or URL record

**Review by MaskDuck — CHANGES_REQUESTED** [review]
can you delete files located under the `.idea` folder and the folder itself?

**Review by MaskDuck — CHANGES_REQUESTED** [review]
uhhh you cant combine cname with other records sorry

**Comment by TemurbekRuziyev** [comment]
Hi,  what should to do? Please give me guide to get domain name

**Comment by WilliamDavidHarrison** [comment]
@TemurbekRuziyev do you not need records at all? If you want your temurbekruziyev.github.io to be on your is-a.dev domain, add the CNAME record: "temurbekruziyev.github.io" to your file.

**Review by MaskDuck — CHANGES_REQUESTED** [review]
pls complete your website first >:( 

we don't accept website with just random words

**Comment by WilliamDavidHarrison** [comment]
@TemurbekRuziyev why do you keep adding random files? You only add your domain.

**Pull request closed without merging**
