### PR TITLE
Added devmirza via is-a-dev-cli

### PR DESCRIPTION
**Pull request by Zaid-maker**
Added devmirza via the CLI

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
I can't reach your website.

**Comment by Zaid-maker** [comment]
> I can't reach your website.

It needs to be build with github pages I am doing it, it should work in any second

**Comment by Zaid-maker** [comment]
> I can't reach your website.

It's a nextjs website hosted on github pages, can I use vercel?

**Comment by piotr25691** [comment]
> > I can't reach your website.
> 
> It's a nextjs website hosted on github pages, can I use vercel?

nope, vercel/netlify are not supported

**Pull request closed without merging**
