### PR TITLE
Update esp.json

### PR DESCRIPTION
**Pull request by fakeesp**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.

### CODE REVIEW

**Review by MaskDuck — DISMISSED** [review]
it's just a fileserver. 

if your domain is proxied then pls give us a review

**Comment by fakeesp** [comment]
my site is reachable by esp.ovh domain right now

i want to get ssl certificate on is-a.dev domain and publish site on it a bit later

**Comment by CuteDog5695** [comment]
> my site is reachable by esp.ovh domain right now
> 
> i want to get ssl certificate on is-a.dev domain and publish site on it a bit later

I mean, as long as you give a preview of your website we will merge it (and you did give a preview so I'll merge the PR now)

**Review by iostpa — APPROVED** [review]

**Comment by fakeesp** [comment]
image

from now website is reachable

**Pull request merged**
