### PR TITLE
Changing cname to albinpraveen.github.io 

### PR DESCRIPTION
**Pull request by ALBINPRAVEEN**
## Requirements
Unless explicitly specified otherwise by a **maintainer**, your domain must pass **all** of the indicated requirements below.
Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.

### CODE REVIEW

**Review by omsenjalia — APPROVED** [review]

**Comment by TerraPlayz** [comment]
Dude your website is fire 🔥🔥

**Comment by ALBINPRAVEEN** [comment]
Thbkz btw

**Comment by ALBINPRAVEEN** [comment]
Your connection is not private
Attackers might be trying to steal your information from albinpraveen.is-a.dev (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID


Why showing error like this in my website

**Comment by TerraPlayz** [comment]
> Your connection is not private Attackers might be trying to steal your information from albinpraveen.is-a.dev (for example, passwords, messages or credit cards). Learn more NET::ERR_CERT_COMMON_NAME_INVALID
> 
> Why showing error like this in my website

It's probably cuz GitHub didn't issue a SSL certificate. Wait a few hours it'll be fixed

**Comment by TerraPlayz** [comment]
Probably means it can be true but it can be also false

**Review by wdhdev — CHANGES_REQUESTED** [review]
This PR makes zero changes. You just need to update your fork.

**Comment by TerraPlayz** [comment]
> This PR makes zero changes.

He removed / from CNAME

**Comment by WilliamDavidHarrison** [comment]
> > This PR makes zero changes.
> 
> He removed / from CNAME

There isn't one on main branch.

**Comment by TerraPlayz** [comment]
> > > This PR makes zero changes.
> > 
> > 
> > He removed / from CNAME
> 
> There isn't one on main branch.

Oh okau

**Comment by TerraPlayz** [comment]
Okay

**Comment by TerraPlayz** [comment]
Confused

**Comment by WilliamDavidHarrison** [comment]
> no change needed so...

Why'd you reopen then close?

**Pull request closed without merging**
