### PR TITLE
Create ahmed.is-a.dev

### PR DESCRIPTION
**Pull request by ahmed-eldin**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://github.com/ahmed-eldin/portfolio-site

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
I can't reach your website

**Comment by ahmed-eldin** [comment]
How do I make it reachable?

**Comment by WilliamDavidHarrison** [comment]
> How do I make it reachable?

By publishing it on GitHub pages and moving it to the root of the repo.

**Comment by ahmed-eldin** [comment]
I published it to GitHub. I can't have any folders in the repo?

https://github.com/ahmed-eldin/portfolio-site/tree/main/PortfolioSite

**Comment by WilliamDavidHarrison** [comment]
You can have folders in the repo, it just works better if the website is in the root folder.

**Comment by ahmed-eldin** [comment]
Just brought the main files to the root directory

**Comment by WilliamDavidHarrison** [comment]
> Just brought the main files to the root directory

I meant moving the files in the `PortfolioSite` into the root directory.

**Comment by ahmed-eldin** [comment]
Just moved all the main files to the root directory. Can I move the assets folder into the the root as well? There is no option to edit the path.

**Comment by WilliamDavidHarrison** [comment]
> Just moved all the main files to the root directory. Can I move the assets folder into the the root as well? There is no option to edit the path.

You don't need to move the assets

**Comment by WilliamDavidHarrison** [comment]
Do you have GitHub Pages enabled?

**Comment by ahmed-eldin** [comment]
No I'm not familiar with GitHub Pages

**Comment by ahmed-eldin** [comment]
I just uploaded my completed vs code project to a github repo.

**Pull request closed without merging**
