### PR TITLE
Create qloha.json

### PR DESCRIPTION
**Pull request by qloha**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://sora-os-production.up.railway.app
Is it okay if I keep working on the frontend/backend of the website?

### CODE REVIEW

**Review by iostpa — CHANGES_REQUESTED** [review]
I'd like a preview of your website. (Link given gave a 404 error)

**Comment by qloha** [comment]
@orangci sorry https://sora-os.up.railway.app

**Comment by qloha** [comment]
that was the old link i forgot to update it here that is my fault

**Review by qloha — COMMENTED** [review]
Updated the preview link

**Pull request closed without merging**
