### PR TITLE
Register Subdomain: Poked

### PR DESCRIPTION
**Pull request by PokedWasTaken**
## To make our job easier, please spend time to review your application before submitting.

> Link to website: http://pokedarmory.github.io/
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. This requirement can be raised if the domain you're registering is for emails
- [x] The website is reachable.
- [x] The CNAME record doesn't contain any slash.
- [x] There's enough information at the owner field.
- [x] You should have your email presented. If you don't want to share email, you can leave email an empty string ("") and add any other social such as Discord/Twitter/etc.

### CODE REVIEW

**Review by iop3 — DISMISSED** [review]
looking good :)

**Review by MaskDuck — CHANGES_REQUESTED** [review]
please complete your website.

**Comment by PokedArmory** [comment]
I didn't have any time for the past month, but I just uploaded a finished version.

**Comment by PokedArmory** [comment]
@MaskDuck

**Review by PokedWasTaken — COMMENTED** [review]
Finished.

**Comment by co-existing** [comment]
looks fine now, wait for other maintainers to approve and merge

**Comment by PokedArmory** [comment]
@co-existing Is there a way to get @MaskDuck to see the changes?

**Comment by co-existing** [comment]
Actually there's nothing you can do, except wait. Idk to be honest.

**Review by wdhdev — DISMISSED** [review]

**Comment by PokedArmory** [comment]
I'm about to give up on this project, its been over a month with no response.

**Comment by WilliamDavidHarrison** [comment]
> I'm about to give up on this project, its been over a month with no response.

Sorry for the wait, but we have a lot of PR's to review and merge so it will take a while. I would merge your PR but I do not have the permissions to.

**Comment by PokedArmory** [comment]
@WilliamDavidHarrison Should I just make a new pull request?

**Comment by WilliamDavidHarrison** [comment]
> @WilliamDavidHarrison Should I just make a new pull request?

If you want.

**Pull request closed without merging**
