### PR TITLE
my em@il forwarder

### PR DESCRIPTION
**Pull request by MaskDuck**
pls approve

why is everybody too slow

### CODE REVIEW

**Review by AbubakarKang — APPROVED** [review]

**Review by MaskDuck — COMMENTED** [review]
lemme see if this approve

**Comment by MaskDuck** [comment]
NO IT DOESNT

**Review by hackermondev — APPROVED** [review]

**Comment by SX-9** [comment]
how did you made this???

**Comment by MaskDuck** [comment]
idk

**Pull request merged**
