### PR TITLE
Update and rename frenchguy.json to seqyu.json

### PR DESCRIPTION
**Pull request by nvct-website**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

it looks good doesnt it lol

### CODE REVIEW

**Review by DEV-DIBSTER — DISMISSED** [review]

**Comment by nvct-website** [comment]
Hello @DEV-DIBSTER !
I see that you added the "reason: merge conflict" tag but I am not sure if this means my PR has been rejected as the changes have been approved but not merged.

Have a good day/night/afternoon.

**Comment by CuteDog5695** [comment]
It isn't rejected, he added that label since this PR has a conflicting file.

**Comment by CuteDog5695** [comment]
Which in result he can't merge the pull request (forgot to add in the comment above)

**Comment by nvct-website** [comment]
image
requested change has been commited to the PR

**Pull request closed without merging**
