### PR TITLE
BETA: Update anon.is-a.dev

### PR DESCRIPTION
**Pull request by anondev-sudo**
Updated `anon.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Review by VaibhavSys — CHANGES_REQUESTED** [review]
CNAME cannot be used in conjunction with any other record types.

**Comment by anondev-sudo** [comment]
Why?

**Comment by anondev-sudo** [comment]
Also how do I set priority for MX records?

**Comment by anondev-sudo** [comment]
changed it to A record

**Review by mtgsquad — APPROVED** [review]
Approved as requested in is-a-dev discord server.

**Comment by anondev-sudo** [comment]
How do I set priority for MX record?

**Comment by anondev-sudo** [comment]
The provider wants these MX records with correct priority number

<h3 style="box-sizing: inherit; margin: 0px; color: rgb(0, 0, 0); font-family: arial, helvetica, &quot;liberation sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Požadované MX záznamy</h3>

data | typ | prio
-- | -- | --
4e7b2afdee66dc77.mx2.emailprofi.seznam.cz | MX | 10
4e7b2afdee66dc77.mx1.emailprofi.seznam.cz

**Comment by anondev-sudo** [comment]
Also how do I make subdomain like docs.anon.is-a.dev ?

**Comment by anondev-sudo** [comment]
Please reply

**Comment by WilliamDavidHarrison** [comment]
1. You cannot specify the priority of MX records, they are assigned automatically starting from 10
2. You can make a subdomain like docs.anon.is-a.dev by just creating another JSON file called `docs.anon.json`

**Pull request merged**
