### PR TITLE
security: adds dmarc policy

### LINKED ISSUE #1178: Is it possible to use DKIM and DMARC?
Is it possible to use DKIM and DMARC with an is-a.dev (sub)domain?

### PR DESCRIPTION
**Pull request by phenax**
Fixes #1178

### CODE REVIEW

**Review by TheBotlyNoob — APPROVED** [review]

**Review by MaskDuck — APPROVED** [review]
havent review domain test since idk js

**Comment by TheBotlyNoob** [comment]
any update @phenax?

**Review by WDH-2 — APPROVED** [review]

**Comment by WilliamDavidHarrison** [comment]
Approved with wrong account lol

**Review by wdhdev — APPROVED** [review]

**Comment by WilliamDavidHarrison** [comment]
@phenax Is this going to be actually implemented or can this just be closed?

**Comment by WilliamDavidHarrison** [comment]
@phenax Can this be merged or should we just close it?

**Pull request closed without merging**
