### PR TITLE
Register jackchap.is-a.dev

### PR DESCRIPTION
**Pull request by jackchapm**
Added `jackchap` via the registration website.

### CODE REVIEW

**Comment by crepppy** [comment]
I would also like to know what your policy is in replacing unused subdomains

jack.is-a.dev is currently taken, however, the URL it points to is no longer active and shows as unregistered on a WHOIS lookup https://who.is/whois/jackfrisby.co.

If possible, I'd appreciate it if you didn't merge this request yet, so I could instead change `jack` to my own domain.

**Comment by crepppy** [comment]
Appreciate it! 👍🏻

**Review by wdhdev — DISMISSED** [review]

**Comment by WilliamDavidHarrison** [comment]
@crepppy can you merge latest changes in to your branch?

**Comment by crepppy** [comment]
crepppy:main looks up to date?

**Comment by WilliamDavidHarrison** [comment]
> https://github.com/crepppy/register/tree/main looks up to date?

It won't let me merge, I need you to sync your fork.

**Comment by WilliamDavidHarrison** [comment]
Or I can close this PR and make a separate updated version

**Comment by WilliamDavidHarrison** [comment]
@crepppy Are you going to make a new PR or should I do it?

**Comment by crepppy** [comment]
@WilliamDavidHarrison Working now?

**Review by wdhdev — APPROVED** [review]

**Comment by WilliamDavidHarrison** [comment]
> @WilliamDavidHarrison Working now?

Yep

**Pull request merged**
