### PR TITLE
Register cycloneaddons.is-a.dev

### PR DESCRIPTION
**Pull request by CycloneAddons**
Register deepesh.is-a.dev with CNAME record pointing to deepeshxcode.github.io.

### CODE REVIEW

**Review by triach-rold — CHANGES_REQUESTED** [review]
Website is reachable, but needs more content to be considered as "complete".

**Review by iostpa — CHANGES_REQUESTED** [review]
i would like you to add more stuff to the website

**Comment by CycloneAddons** [comment]
> i would like you to add more stuff to the website

Now I added Look to My Webpage

**Review by iostpa — APPROVED** [review]
seems good to me now

**Comment by CycloneAddons** [comment]
> seems good to me now

Can I add domain now ?

**Comment by CuteDog5695** [comment]
> > seems good to me now
> 
> Can I add domain now ?

PR got merged so yes

**Pull request merged**
