### PR TITLE
Create sambhrama.json

### PR DESCRIPTION
**Pull request by Sambhrama754**
Add my sub domain
Thank you so much I wanted a sweet looking .is-a.dev for yt and GitHub
UwU

Regards,
Sambhrama754

### CODE REVIEW

**Comment by Sambhrama754** [comment]
Sir pls merge my pull request

**Comment by Sambhrama754** [comment]
Uhh src code is broken itself I think 🤔

**Comment by Sambhrama754** [comment]
Okie now it should work

**Review by hackermondev — APPROVED** [review]

**Comment by hackermondev** [comment]
Please be patience as two maintainers will need to approve the PR.

**Comment by Sambhrama754** [comment]
Okie thank you so much

**Comment by Sambhrama754** [comment]
@TheBotlyNoob  
Pls approve

**Review by phenax — APPROVED** [review]

**Pull request merged**
