### PR TITLE
BETA: Register my.sembiland.is-a.dev

### PR DESCRIPTION
**Pull request by dennsaja**
Added `my.sembiland.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Comment by TTGGHHgjkG** [comment]
My previous is-a-dev domain is not working...have written to the help desk

**Review by omsenjalia — CHANGES_REQUESTED** [review]
URL records must have protocol (ex. `https://`)

**Comment by TTGGHHgjkG** [comment]
it already has https://

**Comment by TTGGHHgjkG** [comment]
delete domains/sembiland.json

**Review by omsenjalia — APPROVED** [review]

**Comment by TTGGHHgjkG** [comment]
delete domains/sembiland.json

**Pull request merged**
