### PR TITLE
devcreates.is-a.dev Domain

### PR DESCRIPTION
**Pull request by lezetho**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

(Website N/A, email only.)

### CODE REVIEW

**Comment by lezetho** [comment]
I'm requesting a NS domain because I plan to host multiple websites onto subdomains of `devcreates.is-a.dev`. I also would like to have it as in the future I might use the domain and host a website to share what DevCreates is.

**Comment by lezetho** [comment]
william if you deny it because of ploszukiwacz i will crash out

**Comment by PlOszukiwaczDEV** [comment]
erm technicly you dont have a website so you shouldnt get the domain

**Comment by CuteDog5695** [comment]
> william if you deny it because of ploszukiwacz i will crash out

well that came out of nowhere

**Comment by lezetho** [comment]
> > william if you deny it because of ploszukiwacz i will crash out
> 
> well that came out of nowhere

@PlOszukiwaczDEV was telling me he dmed william :sob:

**Comment by lezetho** [comment]
> > > william if you deny it because of ploszukiwacz i will crash out
> > 
> > 
> > well that came out of nowhere
> 
> Meow

denied

**Comment by PlOszukiwaczDEV** [comment]
> > > william if you deny it because of ploszukiwacz i will crash out
> > 
> > 
> > well that came out of nowhere
> 
> @PlOszukiwaczDEV was telling me he dmed william 😭

:blueCookie:

**Comment by lezetho** [comment]
> > > > william if you deny it because of ploszukiwacz i will crash out
> > > 
> > > 
> > > well that came out of nowhere
> > 
> > 
> > @PlOszukiwaczDEV was telling me he dmed william 😭
> 
> :blueCookie:

get out-

**Comment by PlOszukiwaczDEV** [comment]
> > > > > william if you deny it because of ploszukiwacz i will crash out
> > > > 
> > > > 
> > > > well that came out of nowhere
> > > 
> > > 
> > > @PlOszukiwaczDEV was telling me he dmed william 😭
> > 
> > 
> > :blueCookie:
> 
> get out-

:nuhuh:

**Comment by CuteDog5695** [comment]
why tf are yall chatting in here :sob:

**Comment by PlOszukiwaczDEV** [comment]
> why tf are yall chatting in here 😭

this way better then discord frfr

**Comment by lezetho** [comment]
> > why tf are yall chatting in here 😭
> 
> this way better then discord frfr

valid tho

**Comment by lezetho** [comment]
> why tf are yall chatting in here 😭

why cant we :shrug:

**Comment by CuteDog5695** [comment]
> > why tf are yall chatting in here 😭
> 
> why cant we 🤷

im just asking

**Comment by lezetho** [comment]
> > > why tf are yall chatting in here 😭
> > 
> > 
> > why cant we 🤷
> 
> im just asking

i asked first

**Comment by CuteDog5695** [comment]
> > > > why tf are yall chatting in here 😭
> > > 
> > > 
> > > why cant we 🤷
> > 
> > 
> > im just asking
> 
> i asked first

nuh uh

**Comment by lezetho** [comment]
> > > > > why tf are yall chatting in here 😭
> > > > 
> > > > 
> > > > why cant we 🤷
> > > 
> > > 
> > > im just asking
> > 
> > 
> > i asked first
> 
> nuh uh

yuh uh

**Comment by CuteDog5695** [comment]
nuh uh

**Comment by lezetho** [comment]
YUH UH

**Comment by lezetho** [comment]
waiting

**Comment by PlOszukiwaczDEV** [comment]
Thank you william

**Comment by lezetho** [comment]
i quit ur banned @PlOszukiwaczDEV

**Pull request closed without merging**
