### PR TITLE
Register megacfilm.is-a.dev

### PR DESCRIPTION
**Pull request by mcvo1705**
Added `megacfilm.is-a.dev` using the [CLI](https://www.npmjs.com/package/@is-a-dev/cli).

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please use a valid record

**Review by wdhdev — CHANGES_REQUESTED** [review]
I cannot reach your website.

**Comment by mcvo1705** [comment]
> I cannot reach your website.
https://prefer-disappointed-wage-advance.trycloudflare.com/

**Review by wdhdev — CHANGES_REQUESTED** [review]
This looks like an illegal movie site to me, so I cannot be give you a domain.

**Comment by mcvo1705** [comment]
> This looks like an illegal movie site to me, so I cannot be give you a domain.

understood, thank for your time.

**Pull request closed without merging**
