### PR TITLE
Patch 6

### PR DESCRIPTION
**Pull request by Yunexiz**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.

### CODE REVIEW

**Comment by orxngc** [comment]
No you can't have it :((

**Comment by Yunexiz** [comment]
> No you can't have it :((

NOOOOOOOOOOOOOOOOOOOO

**Comment by wdhdev** [comment]
@orangc First come, first served. Sorry not sorry. :)

**Comment by wdhdev** [comment]
User agreed to give it to orangx.

**Pull request closed without merging**
