### PR TITLE
Register Subdomain: tarun577

### PR DESCRIPTION
**Pull request by H-57**
Added the domain: tarun577

### CODE REVIEW

**Comment by TerraPlayz** [comment]
## Pull Request Opened
Your pull request has been opened! Just wait for a maintainer to merge it and then you can start using your domain!

<a href="https://www.buymeacoffee.com/phenax" target="_blank">Buy Me a Coffee</a> <a href="https://liberapay.com/phenax" target="_blank">Liberapay</a>

---

**Made a mistake in the records?** Don't worry, you can make those changes in your fork and it will be automatically added to this pull request.

**Review by omsenjalia — APPROVED** [review]
Great

**Review by omsenjalia — APPROVED** [review]
Great

**Review by omsenjalia — CHANGES_REQUESTED** [review]
Cannot use local ip

**Review by omsenjalia — COMMENTED** [review]
Also why do you need 3 domains? Hacker domain is invalid. Tarun577 and Tarun 57 has just diffrence of 7. Why do you need both of them?

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
