### PR TITLE
Create null.json

### PR DESCRIPTION
**Pull request by null1s**
To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [ ] You're not using Vercel or Netlify.
- [ ] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [ ] The website is reachable.
- [ ] The CNAME record doesn't contain any slash.
- [ ] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

### CODE REVIEW

**Comment by MicroBotCodes** [comment]
There's nothing in it lol

**Review by MaskDuck — CHANGES_REQUESTED** [review]
please have some actual sort of record in the file.

if you need help, read the [docs](https://is-a.dev/docs) or join our discord (link in readme)

**Review by wdhdev — CHANGES_REQUESTED** [review]
Blank file

**Comment by disCodeDev** [comment]
Docs are down atm, how I can set it up??

2022-08-28, sk, 09:06 MaskDuck ***@***.***> rašė:

**Comment by WilliamDavidHarrison** [comment]
> Docs are down atm, how I can set it up?? 2022-08-28, sk, 09:06 MaskDuck ***@***.***> rašė:
> […](#)

Refer to the file directly: https://github.com/is-a-dev/docs/blob/main/src/docs/domain_structure/index.md

**Pull request closed without merging**
