### PR TITLE
Register my sub domain

### PR DESCRIPTION
**Pull request by jakeharrison90**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

excelcommunity.vercel.app

### CODE REVIEW

**Comment by jakeharrison90** [comment]
is there problem with my files?

**Comment by DEV-DIBSTER** [comment]
> is there problem with my files?

@jakeharrison90 Mainly socials, you have no email nor an OWL, meaning we have no way to contact you. A type of contact should be provided in the owner property.

**Comment by jakeharrison90** [comment]
> > is there problem with my files?
> 
> @jakeharrison90 Mainly socials, you have no email nor an OWL, meaning we have no way to contact you. A type of contact should be provided in the owner property.

I don't have problem to add email, but I have read in previous pull that it isn't necessary so we can use or not

**Comment by DEV-DIBSTER** [comment]
> > > is there problem with my files?
> > 
> > 
> > @jakeharrison90 Mainly socials, you have no email nor an OWL, meaning we have no way to contact you. A type of contact should be provided in the owner property.
> 
> I don't have problem to add email, but I have read in previous pull that it isn't necessary so we can use or not

Correct, you do not need an email, but a replacement (e.g. our OWL system, a Discord username, Twitter/X handle, etc).

**Comment by jakeharrison90** [comment]
> > > > is there problem with my files?
> > > 
> > > 
> > > @jakeharrison90 Mainly socials, you have no email nor an OWL, meaning we have no way to contact you. A type of contact should be provided in the owner property.
> > 
> > 
> > I don't have problem to add email, but I have read in previous pull that it isn't necessary so we can use or not
> 
> Correct, you do not need an email, but a replacement (e.g. our OWL system, a Discord username, Twitter/X handle, etc).

I just copied the same format that was approved so i just use that. fine i have updated file

**Review by DEV-DIBSTER — APPROVED** [review]

**Pull request merged**
