### PR TITLE
Update lthon09.json

### PR DESCRIPTION
**Pull request by lthon09**
## Requirements
- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website.
- [x] The website is reachable.
- [x] You're not using Vercel or Netlify.
- [x] The CNAME record doesn't contain `https://` or `/`.
- [x] There is sufficient information at the `owner` field.

## Website Link/Preview
[Preview](https://lthon09-1-h1587393.deta.app/)

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
I can't reach your website, please send a preview/screenshot of the site.

**Comment by lthon09** [comment]
> I can't reach your website, please send a preview/screenshot of the site.

should be working now

**Comment by WilliamDavidHarrison** [comment]
I still cannot reach your website.

**Comment by WilliamDavidHarrison** [comment]
Please send a screenshot of your website then.

**Comment by lthon09** [comment]
wdym by not working btw

**Comment by lthon09** [comment]
https://pagespeed.web.dev/report?url=https%3A%2F%2Flthon09-1-h1587393.deta.app%2F&form_factor=desktop this is the results of pagespeed, there are screenshots and it seems like the websites accessible

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
