### PR TITLE
Update arsdorint.json

### PR DESCRIPTION
**Pull request by arsdorintbp2003**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
I can't reach your website

**Comment by arsdorintbp2003** [comment]
When I type "arsdorint.github.io", it is redirected to arsdorint.is-a.dev, which make it inaccessible

**Review by wdhdev — DISMISSED** [review]
I'll approve, just try and get your site up.

**Review by wdhdev — APPROVED** [review]

**Comment by arsdorintbp2003** [comment]
Sorry, when I verify my is-a.dev site, it is said as follows:
image
What should I do to fix this?

**Pull request merged**
