### PR TITLE
Forgot it wasn't that easy!

### PR DESCRIPTION
**Pull request by EtherealTheDev**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ x ] The file is in the `domains` folder and is in the JSON format.
- [ x ] You have completed your website. 
- [ x  ] The website is reachable.  
- [x  ] You're not using Vercel or Netlify.  
- [x ] The CNAME record doesn't contain `https://` or `/`.  
- [ x] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://etherealthedev.repl.co

### CODE REVIEW

**Comment by EtherealTheDev** [comment]
Forgot it wasn't that easy with replit

**Comment by EtherealTheDev** [comment]
Why is it failing checks? It should be fine

**Review by wdhdev — CHANGES_REQUESTED** [review]
We don't support TXT verification.

**Comment by WilliamDavidHarrison** [comment]
> Why is it failing checks? It should be fine

You can't have a CNAME and another type of record together.

**Comment by EtherealTheDev** [comment]
Done, I'm retarded and forgot the txt thing was for cloudflare

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
