### PR TITLE
BETA: Register raman.is-a.dev

### PR DESCRIPTION
**Pull request by kushalshah0**
Added `raman.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Review by triach-rold — CHANGES_REQUESTED** [review]
Clever, but link needs to direct to a reachable and complete website.

**Comment by kushalshah0** [comment]
> Clever, but link needs to direct to a reachable and complete website.

Done !

**Review by kushalshah0 — COMMENTED** [review]
Done !

**Review by MaskDuck — APPROVED** [review]
to some extent this website still lack content but uhhhhhhhhhhhhh I think this is enough

**Pull request merged**
