### PR TITLE
Create zach.json

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by MaskDuck — CHANGES_REQUESTED** [review]
can we not have some placeholder pls ty

**Review by ghost — COMMENTED** [review]
I have made the changes.

**Comment by mtgsquad** [comment]
Just to let you know, your review holds no significance in terms of merging.

**Review by mtgsquad — DISMISSED** [review]

**Comment by zachjmurphy** [comment]
> Just to let you know, your review holds no significance in terms of merging.

I know it doesn’t.

**Comment by mtgsquad** [comment]
@zachjmurphy add the email placeholder back.

**Comment by zachjmurphy** [comment]
> @zachjmurphy add the email placeholder back.

Okay will do.

**Comment by MaskDuck** [comment]
what i meant was, complete your website first.

there's no issue at the json.

**Pull request closed without merging**
