### PR TITLE
BETA: Register toasty.is-a.dev

### PR DESCRIPTION
**Pull request by toastyyyxd**
Added `toasty.is-a.dev` using the Discord bot.

### CODE REVIEW

**Review by luni-moon — CHANGES_REQUESTED** [review]
Check this please: https://github.com/is-a-dev/register/issues/6627#issuecomment-1666382002

**Comment by toastyyyxd** [comment]
> Check this please: [#6627 (comment)](https://github.com/is-a-dev/register/issues/6627#issuecomment-1666382002)

I changed it to use cloudflare pages CNAME, hopefully thats fine, thanks alot!

**Review by wdhdev — DISMISSED** [review]
I cannot reach your website.
image

**Comment by toastyyyxd** [comment]
> I cannot reach your website. image

Apologies for the late reply.
I forgot to push the website repo to origin, it should work now.

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
