### PR TITLE
Update sanidhya.json

### PR DESCRIPTION
**Pull request by codersonet**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
You can't have CNAME records with other records. We also don't support TXT verification.

**Comment by CoderSoNet** [comment]
Then remove A, TXT

**Comment by CoderSoNet** [comment]
Then remove A, TXT

**Review by wdhdev — CHANGES_REQUESTED** [review]
You will need to provide a valid email address as the one on your domain will no longer be valid after the PR is merged.

**Comment by CoderSoNet** [comment]
What happens to this?

**Comment by CoderSoNet** [comment]
Please help me bro i literally don't know how it works,

**Pull request closed without merging**
