### PR TITLE
Create manoj-kumar-c.json

### PR DESCRIPTION
**Pull request by ManojkumarChandrasekar**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://manoj-kumar-c.github.io/manojkumar-c-dev/#/

### CODE REVIEW

**Review by triach-rold — APPROVED** [review]
Website is reachable and non-empty. Seem(s) good. Nice job on the website.

**Comment by Manoj-kumar-C** [comment]
Is the subdomain allocated ???

**Comment by triach-rold** [comment]
From discord -> 
>To create additional subdomains under an existing one, you may create a file in the domains/ directory using the format subsubdomain.yoursubdomain.json. For example, if you already have the subdomain example.is-a.dev defined in the file example.json located in the domains/ directory, to create a new subdomain start.example.is-a.dev, you would create a new file start.example.json in the domains/ directory using the same format as the existing example.json file. Please note that you must own the example.is-a.dev subdomain in order to create further subdomains under it.

**Review by iostpa — APPROVED** [review]
seems good to me

**Comment by CuteDog5695** [comment]
oh by the way, record is in URL so it will just redirect

**Comment by Manoj-kumar-C** [comment]
yes you are correct

**Comment by Manoj-kumar-C** [comment]
It is working fine . Is it possible to add to change the URL

image



The subdomain is redirecting correctly . Is it possible to do without redirection . I need my site as manoj-kumar-c.is-a.dev 
It is redirecting to https://manoj-kumar-c.github.io/manojkumar-c-dev .Is it possible to do ?

**Comment by CuteDog5695** [comment]
yes it is possible, you can check here on how to do it https://www.is-a.dev/docs/github_pages/
btw you only need to change the record, you do not need to change the json file to what the doc shows

**Pull request merged**
