### PR TITLE
Create wavingcat.json

### PR DESCRIPTION
**Pull request by WavingCatDevs**

### CODE REVIEW

**Comment by WavingCatDevs** [comment]
also i would like it to be wavingcat.is-a.dev please instead of wavingcatdevs.is-a.dev 😄 thank youuu

**Comment by TheBotlyNoob** [comment]
wait, would you like `wavingcatdevs.is-a.dev` **instead** or **with** `wavingcat.is-a.dev`?

**Comment by WavingCatDevs** [comment]
> wait, would you like `wavingcatdevs.is-a.dev` **instead** or **with** `wavingcat.is-a.dev`?

i would like wavingcat.is-a.dev please

**Comment by WavingCatDevs** [comment]
oops

**Review by TheBotlyNoob — APPROVED** [review]

**Comment by TheBotlyNoob** [comment]
thanks for the enthusiasm!

**Comment by WavingCatDevs** [comment]
https://wavingcat.is-a.dev dosent seem to work, please may you have a look it this, thanks alot 😄

**Comment by TheBotlyNoob** [comment]
we still need to wait for another @is-a-dev/maintainers to approve, then we can merge this pr.

**Review by mtgsquad — APPROVED** [review]

**Comment by WavingCatDevs** [comment]
Thanks so much guys!, now i just need to wait for https im guessing :)

**Pull request merged**
