### PR TITLE
BETA  Add Subdomain:Trash-Panda

### PR DESCRIPTION
**Pull request by Nunya-9018**
Added the domain  Trash-Panda

### CODE REVIEW

**Review by andrewstech — CHANGES_REQUESTED** [review]
Website needs to be finished

**Comment by Nunya-9018** [comment]
@andrewstech Yes it does but I have a almost finished site on my pc I just need to finish some things and commit it

**Comment by Nunya-9018** [comment]
It's more finished than this image

**Comment by Nunya-9018** [comment]
I'm changing hosting providers so vercel link will not work anymore

**Pull request closed without merging**
