### PR TITLE
Added masmiyen via is-a-dev-cli

### PR DESCRIPTION
**Pull request by MASMIYEN**
Added masmiyen via the CLI

### CODE REVIEW

**Comment by MASMIYEN** [comment]
This time I did it from command line

**Comment by WilliamDavidHarrison** [comment]
Same issue as last time. Just create the file and don't modify it.

image

**Review by MASMIYEN — COMMENTED** [review]
did it before, same issue
can you delete masmiyen.json, I ll submit again

**Comment by WilliamDavidHarrison** [comment]
I'll fix it.

**Review by wdhdev — APPROVED** [review]
I don't think you ever deleted the original files, so that is why it's broken. I have fixed them.

**Pull request merged**
