### PR TITLE
Create victoria.json

### PR DESCRIPTION
**Pull request by iTahseen**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

victoriaa.vercel.app

### CODE REVIEW

**Comment by cupglassDEV** [comment]
TXT **only** dosent really do anything to your domain..

If you want to make a domain verification (for example, [vercel](https://vercel.com)) make a separate file like `_vercel.victoria.json` but you need to make a new `victoria.json` WITH content using these records:

`CNAME` (this is the easiest, just point it to one of your github pages, or Vercel <sup>(again)</sup>), 
`A` (for ipv4, useful for apex domain like this. Vercel support this), and 
`AAAA` (for ipv6)

https://is-a.dev/docs/domain-structure/

Or if you use one of these services, consider reading these docs:
https://is-a.dev/docs/github-pages/
https://is-a.dev/docs/vercel/

**Comment by iTahseen** [comment]
I'm sorry I couldn't find vercel's documentation on is-a.dev website.
I made a new file as you said _vercel.victoria.json
with content like this
{
  "owner": {
    "username": "itahseen"
  },
  "record": {
    "CNAME": "victoriaa.vercel.app"
  }
}

hope that it will work now

**Comment by cupglassDEV** [comment]
> I'm sorry I couldn't find vercel's documentation on is-a.dev website.
> I made a new file as you said _vercel.victoria.json
> with content like this
> {
>   "owner": {
>     "username": "itahseen"
>   },
>   "record": {
>     "CNAME": "victoriaa.vercel.app"
>   }
> }
> 
> hope that it will work now
@iTahseen 

you blind?? https://is-a.dev/docs/vercel Its literally on top of the heading


And no, that is incorrect

**Comment by CuteDog5695** [comment]
@iTahseen We do have documentation for Vercel, as @cupglassDEV stated. Please redo the whole process and follow along the documentation for this domain.

**Comment by iTahseen** [comment]
kindly I have updated my victoria.json file and my _vercel.victoria.json file is here
https://github.com/is-a-dev/register/pull/17063

**Pull request closed without merging**
