### PR TITLE
Create auth

### PR DESCRIPTION
**Pull request by ashfn**
To make our job easier, please spend time to review your application before submitting. 

- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [x] The website is reachable.
- [x] The CNAME record doesn't contain any slash.
- [x] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.

### CODE REVIEW

**Comment by omxpro** [comment]
@Authorises please fill the text that the pr has. Add a x in between [] for that

**Comment by Authorises** [comment]
> @Authorises please fill the text that the pr has. Add a x in between [] for that
Yep just filled it in, sorry I missed it at first

**Comment by omxpro** [comment]
You need a completed website 
Screenshot_20220618-164654_Brave

**Review by hackermondev — DISMISSED** [review]

**Comment by hackermondev** [comment]
You need a completed website before I can merge.

**Review by MaskDuck — CHANGES_REQUESTED** [review]
i disagree, this domain may make people think its is-a.dev official domains. @is-a-dev/maintainers, what do you think?

**Comment by Authorises** [comment]
> i disagree, this domain may make people think its is-a.dev official domains. @is-a-dev/maintainers, what do you think?

It's short for authorises, my username,

**Comment by omxpro** [comment]
> > i disagree, this domain may make people think its is-a.dev official domains. @is-a-dev/maintainers, what do you think?
> 
> It's short for authorises, my username,

Then change it to authorises as auth.is-a.dev will be thinked as it's a official domain. But it's not official domain so ywa

**Comment by omxpro** [comment]
Yea

**Comment by Authorises** [comment]
would autho.is-a.dev work instead?

**Comment by mtgsquad** [comment]
> would autho.is-a.dev work instead?

No sadly as that could be a mispell, + we're already working on stuff and we already plan to use auth.is-a.dev

**Comment by Authorises** [comment]
> 

There could be hundreds of misspells, what's the point in blocking all of them?

staff.is-a.dev
users.is-a.dev
api.is-a.dev
admin.is-a.dev
help.is-a.dev

thousands of misspells for a similar thing

**Comment by LogSkele** [comment]
just use `authorises.is-a.dev`

**Comment by techpixel** [comment]
May I recommend `author.is-a.dev`?

**Comment by LogSkele** [comment]
still sounds like a official one

**Comment by Authorises** [comment]
I believe I have fixed all of the issues. 😄

**Comment by Authorises** [comment]
> > > 
> > 
> > There could be hundreds of misspells, what's the point in blocking all of them?
> > 
> > staff.is-a.dev
> > users.is-a.dev
> > api.is-a.dev
> > admin.is-a.dev
> > help.is-a.dev
> > 
> > thousands of misspells for a similar thing
> 
> Dude, how do you not understand simple words, just use another name since auth.is-a.dev is an official domain used in the new registration site.
> 

Scroll up

**Pull request closed without merging**
