### PR TITLE
Registrar.is-a.dev

### PR DESCRIPTION
**Pull request by Satindar31**
For the hackathon. Still WIP

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

image

### CODE REVIEW

**Comment by Satindar31** [comment]
Odd, I did everything as per the docs. Why's it showing an invalid file name?

**Comment by orxngc** [comment]
i will await the review of at least one other maintainer before merging this

**Comment by Satindar31** [comment]
> i will await the review of at least one other maintainer before merging this due to the domain name

lmao, yeah i get it np problem

**Comment by Satindar31** [comment]
@Stef-00012 could you also review?

**Comment by wdhdev** [comment]
No

**Pull request closed without merging**
