### PR TITLE
Create lqhuy.json

### PR DESCRIPTION
**Pull request by Lqhuy125**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.

### CODE REVIEW

**Review by iostpa — CHANGES_REQUESTED** [review]
Please remove the domain from your repo, since I can't see your website because its redirecting to the is-a.dev domain.

**Comment by Lqhuy125** [comment]
i have updated, pls review help me @CuteDog5695

**Review by iostpa — CHANGES_REQUESTED** [review]
Please add more content to your website.

**Comment by Lqhuy125** [comment]
Hello @CuteDog5695, im sorry but can you review again help me, thank you very much

**Pull request closed without merging**
