### PR TITLE
Update new.sx9.json to hopefully fix an issue

### PR DESCRIPTION
**Pull request by satr14washere**
2023-12-06-133540_1366x768_scrot
2023-12-06-133627_1366x768_scrot
2023-12-06-133654_1366x768_scrot

### CODE REVIEW

**Comment by SX-9** [comment]
site code: https://github.com/SX-9/sx-2nd-website

**Comment by SX-9** [comment]
im redeploying the record to hopefully fix this

**Comment by SX-9** [comment]
if you're wondering how this happened well idfk it just vanished

**Comment by WilliamDavidHarrison** [comment]
I will re run the workflow instead.

**Pull request closed without merging**
