### PR TITLE
Create _discord.oxmc.json

### PR DESCRIPTION
**Pull request by oxmc**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

This is for the connections part in discord

### CODE REVIEW

**Comment by oxmc** [comment]
@WilliamDavidHarrison When running this checks, i'm a bit confused, we can make the files like this correct? or is that a thing yet.

**Review by wdhdev — CHANGES_REQUESTED** [review]
We don't support domain verification, you will need to use the Verify by HTTPS option instead.

**Comment by WilliamDavidHarrison** [comment]
> @WilliamDavidHarrison When running this checks, i'm a bit confused, we can make the files like this correct? or is that a thing yet.

We don't support Discord TXT verification at this time unfortunately. I will pass this onto @phenax and we might be able to get this added.

**Comment by oxmc** [comment]
Thank you for informing me!

**Comment by oxmc** [comment]
> We don't support domain verification, you will need to use the Verify by HTTPS option instead.

it does not seem to like that

image

**Comment by WilliamDavidHarrison** [comment]
Does the file end in `.html`? It shouldn't. Also, try giving it some time as that has fixed it for other users as well.

**Comment by oxmc** [comment]
Still nothing:
image

**Comment by WilliamDavidHarrison** [comment]
Unfortunately I cannot provide support with this as this is not to do with your subdomain, it is to do with GitHub Pages and Discord.

**Pull request closed without merging**
