### PR TITLE
Create windows10sunvalley.json

### PR DESCRIPTION
**Pull request by userwin64**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://windows10sunvalley.github.io

### CODE REVIEW

**Review by DEV-DIBSTER — APPROVED** [review]

**Comment by DEV-DIBSTER** [comment]
Approval for file, still need to determine if this is not infringing on copyright.

**Comment by DEV-DIBSTER** [comment]
CC: @wdhdev @VaibhavSys @CuteDog5695

**Comment by userwin64** [comment]
> Approval for file, still need to determine if this is not infringing on copyright.

this is a fan-made windows mod and in the download page (specifically in the cover image) there's a text that said "not affiliated with microsoft"

**Comment by CuteDog5695** [comment]
> CC: @wdhdev @VaibhavSys @CuteDog5695

We have merged [astrowin.is-a.dev](https://astrowin.is-a.dev) before, which is also simillar to this PR. So if we would go with that logic this could theoretically be merged, but I would like to hear opinions from other maintainers.

**Pull request merged**
