### PR TITLE
BETA: Register ranareal.is-a.dev

### PR DESCRIPTION
**Pull request by Zer0Rea1**
Added `ranareal.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Review by Omxpro — CHANGES_REQUESTED** [review]
need to add mx2.improvmx.com and a txt record

**Comment by NotRana** [comment]
now plz check

**Review by Omxpro — APPROVED** [review]

**Comment by NotRana** [comment]
we can only put 1 record in website

**Comment by NotRana** [comment]
how much time it takes

**Comment by Omxpro** [comment]
wait for the maintainers please

**Review by iostpa — APPROVED** [review]

**Pull request merged**
