### PR TITLE
Register Subdomain: bardia

### PR DESCRIPTION
**Pull request by abardia**
Added the domain: bardia

### CODE REVIEW

**Review by omsenjalia — APPROVED** [review]
Great

**Review by omsenjalia — DISMISSED** [review]
Great

**Review by wdhdev — CHANGES_REQUESTED** [review]
Can you please send a preview of your website

**Comment by abardia** [comment]
yes: https://abardia.github.io  , this would be the URL. 👍

**Comment by abardia** [comment]
> yes: https://abardia.github.io , this would be the URL. 👍

I think it works now.

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
