### PR TITLE
Create ffj20.json

### PR DESCRIPTION
**Pull request by FFJ-20**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

It'll be an api, i don't have any previews yet, you can contact me on discord: FFJ 2.0#6693

### CODE REVIEW

**Review by wdhdev — DISMISSED** [review]
Please create a website

**Comment by FFJ-20** [comment]
> Please create a website

But how do i create a website when it's supposed to be for an api

**Comment by WilliamDavidHarrison** [comment]
> > Please create a website
> 
> But how do i create a website when it's supposed to be for an api

Just create a basic webpage showing endpoints or something.

**Comment by FFJ-20** [comment]
> > > Please create a website
> > 
> > 
> > But how do i create a website when it's supposed to be for an api
> 
> Just create a basic webpage showing endpoints or something.

Is the html stuff needs or can i just do raw text?

**Comment by WilliamDavidHarrison** [comment]
> > > > Please create a website
> > > 
> > > 
> > > But how do i create a website when it's supposed to be for an api
> > 
> > 
> > Just create a basic webpage showing endpoints or something.
> 
> Is the html stuff needs or can i just do raw text?

You could just do a basic unordered list with endpoints and how to use them.

**Comment by FFJ-20** [comment]
> > > > > Please create a website
> > > > 
> > > > 
> > > > But how do i create a website when it's supposed to be for an api
> > > 
> > > 
> > > Just create a basic webpage showing endpoints or something.
> > 
> > 
> > Is the html stuff needs or can i just do raw text?
> 
> You could just do a basic unordered list with endpoints and how to use them.

But the endpoints won't work as it's with github pages, is that alright?

**Comment by WilliamDavidHarrison** [comment]
> But the endpoints won't work as it's with github pages, is that alright?

Well you need a website, regardless.

**Review by MaskDuck — APPROVED** [review]
i'm sorry for the confusion =((

**Comment by WilliamDavidHarrison** [comment]
> @WilliamDavidHarrison in this case it can be lifted

My bad.

**Pull request merged**
