### PR TITLE
Create rahuletto.json

### PR DESCRIPTION
**Pull request by Rahuletto**
.

### CODE REVIEW

**Review by MaskDuck — CHANGES_REQUESTED** [review]
the cname returned not found

**Comment by Rahuletto** [comment]
Now ?

**Comment by Rahuletto** [comment]
Is it ready to be merged ?

**Comment by Rahuletto** [comment]
Is this ready to be pushed ?

**Review by wdhdev — APPROVED** [review]
@MaskDuck The website is is now reachable.

**Comment by Rahuletto** [comment]
I hope this pr gets merged as soon as possible @MaskDuck

**Comment by Rahuletto** [comment]
Hello ?? @MaskDuck ?

**Review by armoredvortex — APPROVED** [review]

**Comment by WilliamDavidHarrison** [comment]
> Hello ?? @MaskDuck ?

Please don't ping the maintainers.

**Comment by Rahuletto** [comment]
Closed due to inactivity

**Pull request closed without merging**
