### PR TITLE
Update abhay7.json

### PR DESCRIPTION
**Pull request by abhay7dev**
Remove CNAME, add MX/TXT/URL

### CODE REVIEW

**Comment by phenax** [comment]
Undraft the pr when it is ready to merge

**Comment by EpicGamer007** [comment]
Ready :)

**Review by phenax — APPROVED** [review]

**Comment by EpicGamer007** [comment]
Hey @phenax , I am getting the following error when trying to follow the redirect from the site, is this expected?
image

I set the `"URL"` field in the `"record"` object to my new site but this is what I get.

**Comment by phenax** [comment]
DNS changes can take some time to propogate. Give it some time, clear your browser cache and try again.

**Pull request merged**
