### PR TITLE
Create terroid.json

### PR DESCRIPTION
**Pull request by skandabhairava**

### CODE REVIEW

**Review by AbubakarKang — APPROVED** [review]
Good

**Comment by skandabhairava** [comment]
Heylo @AbubakarKang! Can I now go ahead and use the domain? I'm not sure how this process works. It says that you have approved the changes, but it also shows that 1 workflow waiting for approval
Thanks!

**Review by MaskDuck — APPROVED** [review]
nice

**Comment by MaskDuck** [comment]
@skandabhairava now go config github pages. create a new issue in github, or join our discord if you needs help!

for future reference, approval from people who have power to run workflow/merge pull request, aka a maintainer, will have a green tick instead of a grey tick. see the image for example. i am a code owner/maintainer, but abubakar kang isn't.

image

**Comment by skandabhairava** [comment]
> @skandabhairava everyone can review code, but code owner review is required to merge. (hint: im a code owner, but he isnt!)
> 
> no, the domain isnt ready yet, but soon™️ wait me a minute. meanwhile star the repo.

ahh, understood!
Thanks a lot :D, starred the repo!

**Pull request merged**
