### PR TITLE
Create d3admanbot.is-a.dev.json

### PR DESCRIPTION
**Pull request by D3ADVAU**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.

### CODE REVIEW

**Comment by D3ADVAU** [comment]
Hey there. Pull my request.

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please add more content to your website

**Comment by D3ADVAU** [comment]
Hey there. Check my website and pull my request.

**Review by wdhdev — CHANGES_REQUESTED** [review]
image

**Comment by D3ADVAU** [comment]
Screenshot_2023-03-29-10-42-31-309_com kiwibrowser browser

I have fixed it. Please check and pull my request

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
