### PR TITLE
Create chandra.json

### PR DESCRIPTION
**Pull request by sekharmalla**

### CODE REVIEW

**Review by MaskDuck — CHANGES_REQUESTED** [review]
the github pages give me a 404.

**Comment by sekharmalla** [comment]
here is the url https://sekharmalla.github.io/portfolio/ working for me.

**Comment by MaskDuck** [comment]
Then you should access it using yourdomainname.is-a.dev/portfolio. Confirm?

**Comment by MaskDuck** [comment]
@sekharmalla

**Comment by MaskDuck** [comment]
Ill merge this.

**Review by MaskDuck — APPROVED** [review]

**Comment by sekharmalla** [comment]
No no, i want https://chandra.is-a.dev/ please tell me how do i configure.

**Comment by sekharmalla** [comment]
@MaskDuck

**Comment by MaskDuck** [comment]
Rename your gh pages repo to yourghusername.github.io ig

**Comment by MaskDuck** [comment]
I am on mobile right now.

**Comment by MaskDuck** [comment]
Ill add the pending fix label. When you are done, ping me.

**Comment by sekharmalla** [comment]
@MaskDuck its done. Renamed tomy username

**Comment by MaskDuck** [comment]
uh i meant `<yourghusername>.github.io`.
for example maskduck.github.io

**Comment by sekharmalla** [comment]
@MaskDuck yes, i want to do that unfortunately i create a folder again and enabled that for github pages, now i don't understand how to keep the html files in main repository so that they will load in sekharmalla.github.io

**Comment by MaskDuck** [comment]
im pretty sure the repo https://github.com/sekharmalla/sekharmalla.github.io doesnt exist.

**Comment by sekharmalla** [comment]
Okay @MaskDuck i figured out, i just renamed the repo from 'sekharmalla' to 'sekharmalla.github.io' now its perfect. Thank you very much for your help.

**Comment by MaskDuck** [comment]
owo your website looks cool!

**Comment by MaskDuck** [comment]
hi there @sekharmalla, your pr have been merged!

now you have to config github pages. you can find instruction [here](https://github.com/is-a-dev/register/blob/main/docs/hosted-at/github-pages.md).

dont forget to leave this repo a star if you haven't!

if you need help, feel free to join our discord (link in readme) or open a github issue.

**Comment by sekharmalla** [comment]
Thanks 😊, it still in development, i will get it done by end of the day. Thank you for all the help amd merge.

**Comment by MaskDuck** [comment]
no problem! <#

**Pull request merged**
