### PR TITLE
Create joaco11.json

### PR DESCRIPTION
**Pull request by Joaco619**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.

### CODE REVIEW

**Comment by cupglassDEV** [comment]
@CuteDog5695 Do we need to make a web preview first, even tho we're making a danbothosting bot according to the docs

**Review by iostpa — CHANGES_REQUESTED** [review]

**Comment by cupglassDEV** [comment]
> > @CuteDog5695 Do we need to make a web preview first, even tho we're making a danbothosting bot according to the docs
> 
> Yes, you do need to give a web preview, how else are we gonna see your site? (Also next time ping me on discord since I can easily miss comments like this)

shit im sorry, im kinda new to hosting bot so we're learning together

**Comment by CuteDog5695** [comment]
Nah its fine

**Review by iostpa — CHANGES_REQUESTED** [review]

**Comment by cupglassDEV** [comment]
Hey can you close the pr, it turns out he want to make a discord bot hosting service

(god why he didnt tell me from the start)

**Pull request closed without merging**
