### PR TITLE
Register Subdomain: mrinmoy

### PR DESCRIPTION
**Pull request by MrinmoyHaloi**
Added the domain: mrinmoy

### CODE REVIEW

**Comment by MrinmoyHaloi** [comment]
I followed the https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain guide here and added the ip addresses for a record. Didn't use CNAME because i need a txt record also for vscode domain verification. I am not sure if the ip addrresses should be on new lines

**Comment by MrinmoyHaloi** [comment]
When am i getting it :)

**Comment by MrinmoyHaloi** [comment]
@tonetheman

**Comment by MrinmoyHaloi** [comment]
How much longer will it take :) @andrewstech

**Review by andrewstech — APPROVED** [review]

**Pull request merged**
