### PR TITLE
Updated IP address

### PR DESCRIPTION
**Pull request by RehanPlayz**
(Doing this behalf of my friend Suki cause he doesn't know how to make PRs)

### CODE REVIEW

**Review by phenax — CHANGES_REQUESTED** [review]
Cannot allow edits to someone elses record. Please get the owner to create a new pr or approve this one to proceed.

**Comment by RehanPlayz** [comment]
> Cannot allow edits to someone elses record. Please get the owner to create a new pr or approve this one to proceed.

I also made the record....

**Comment by RehanPlayz** [comment]
https://github.com/is-a-dev/register/commit/ef27e474cfff27eb0e91fcfffd85b639a98efad4

**Review by phenax — COMMENTED** [review]
@RehanPlayz My bad. I'd suggest renaming the `username` field to yours instead if you'll be managing this subdomain as that'll avoid confusion with the review process.

**Comment by SukiPlayz** [comment]
@phenax Hey! I am the one who doesn't knows how to make a pull request. I am shame of my self. I asked him to help me. And the ip change is done in behalf of me. So can you approve it?

**Comment by SukiPlayz** [comment]
I am somehow the owner here. And I acknowledge that the ip change is legit and I actually needed it.

**Review by phenax — APPROVED** [review]

**Pull request merged**
