### PR TITLE
 Create api.json

### PR DESCRIPTION
**Pull request by a69y**

### CODE REVIEW

**Review by MaskDuck — CHANGES_REQUESTED** [review]
can you share more about the project?

**Comment by icancodebeauty** [comment]
Its For My All API's!!, Just Registering Domain For Now!!!

**Review by TheBotlyNoob — CHANGES_REQUESTED** [review]
I don't think we should allow this domain, because `api.is-a.dev` sounds like a legit thing. Maybe try changing the file name to `api.icancodebeauty.json`?

**Comment by icancodebeauty** [comment]
Closing This PR Because Its Legit!!!

**Pull request closed without merging**
