### PR TITLE
BETA: Register betsthebest.is-a.dev

### PR DESCRIPTION
**Pull request by Betsthebest**
Added `betsthebest.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Review by triach-rold — APPROVED** [review]
Website is complete and reachable. Nice work.


_Le site est complet et accessible. Beau travail._

**Comment by Betsthebest** [comment]
is it normal that in the manager i can't see the domain?

**Comment by CuteDog5695** [comment]
> is it normal that in the manager i can't see the domain?

PR hasnt been merged btw

**Review by iostpa — APPROVED** [review]
seems good to me

**Comment by Betsthebest** [comment]
thanks a lot

**Pull request merged**
