### PR TITLE
ady.is.a.dev registration

### PR DESCRIPTION
**Pull request by stryfe200fps**
To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [x] You're not using Vercel or Netlify.
- [ ] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [x] The website is reachable.
- [ ] The CNAME record doesn't contain any slash.
- [ ] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

### CODE REVIEW

**Comment by omxpro** [comment]
@stryfe200fps please fill in the []

**Review by omsenjalia — CHANGES_REQUESTED** [review]
Your CNAME cannot have https:// or any / so can you replace the url that you have put into CNAME with `tryfe200fps.github.io`. your cname should be `tryfe200fps.github.io`.

**Review by hackermondev — CHANGES_REQUESTED** [review]
Incorrect CNAME

**Comment by TheBotlyNoob** [comment]
We want subdomains that are a little higher quality than just hello, do you think you could do something creative to your website?

**Pull request closed without merging**
