### PR TITLE
Create themagicmush.json

### PR DESCRIPTION
**Pull request by KobeNi523**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://its.themagicmush.repl.co/

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
I can't reach your website

**Comment by KobeNi523** [comment]
@WilliamDavidHarrison WDYM inaccessible? It takes a few seconds to load but I can access it. Can you try again before I rewrite everything?

**Review by wdhdev — APPROVED** [review]
I like your website

**Comment by KobeNi523** [comment]
thanks! 

also i just wanted to say thanks for all the work you do. ive known about is-a.dev for a few years now and glad to see that its still running. i appreciate all the hours you put in every day so small devs like me can have something cool :)

though we'll probably never talk again, i hope you have a wonderful life

**Comment by WilliamDavidHarrison** [comment]
> thanks!
> 
> also i just wanted to say thanks for all the work you do. ive known about is-a.dev for a few years now and glad to see that its still running. i appreciate all the hours you put in every day so small devs like me can have something cool :)
> 
> though we'll probably never talk again, i hope you have a wonderful life

Thank you ❤️

**Pull request merged**
