### PR TITLE
SubDomain Request

### PR DESCRIPTION
**Pull request by ghost**
Hey, Currently the site isn't visible on my GitHub profile as I am still working on it and the code is really messy. So, If that's an issue I will change it's visibility 🙂

### CODE REVIEW

**Review by hackermondev — CHANGES_REQUESTED** [review]
You cannot make your domain redirect to your domain...

**Review by ghost — COMMENTED** [review]
Oh my bad! Fixed it now 😊

**Review by ghost — COMMENTED** [review]
Values for `repo` and `username` fields aren't case sensitive, right?

**Review by hackermondev — CHANGES_REQUESTED** [review]
Your Github site is 404, it must be visible for it to be published. If you're still working on it, you can leave the pull request open until you're done.

**Comment by hackermondev** [comment]
looks like the user account has been deleted

**Pull request closed without merging**
