### PR TITLE
Update arman.json

### PR DESCRIPTION
**Pull request by ItzArman09**

### CODE REVIEW

**Review by MaskDuck — CHANGES_REQUESTED** [review]
naw you cant use cname with other records.

**Comment by ItzArman09** [comment]
What?

**Comment by ItzArman09** [comment]
Then how will my websitw shown?

**Comment by MaskDuck** [comment]
idk its a dns limitation that is out of our control

**Comment by MaskDuck** [comment]
close [per request](https://canary.discord.com/channels/830872854677422150/830872854677422153/969241184910311456).

**Pull request closed without merging**
