### PR TITLE
Made some changes

### PR DESCRIPTION
**Pull request by Totallynotmwa**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.

### CODE REVIEW

**Review by iostpa — CHANGES_REQUESTED** [review]
not the way to do _discord.mwa.json

**Comment by Totallynotmwa** [comment]
> not the way to do _discord.mwa.json - @CuteDog5695 
What do i have to change?

**Comment by CuteDog5695** [comment]
> > not the way to do _discord.mwa.json - @CuteDog5695
> 
> What do i have to change?

you are renaming mwa.json and putting URL and TXT. for _discord you just need txt

**Comment by Totallynotmwa** [comment]
> > > not the way to do _discord.mwa.json - @CuteDog5695
> > 
> > 
> > What do i have to change?
> 
> you are renaming mwa.json and putting URL and TXT. for _discord you just need txt - @CuteDog5695 

Ohh soo you can only have txt and not url?

**Comment by CuteDog5695** [comment]
> > > > not the way to do _discord.mwa.json - @CuteDog5695
> > > 
> > > 
> > > What do i have to change?
> > 
> > 
> > you are renaming mwa.json and putting URL and TXT. for _discord you just need txt - @CuteDog5695
> 
> Ohh soo you can only have txt and not url?

yea, _discord.mwa.json only needs TXT, not also with URL

**Comment by Totallynotmwa** [comment]
> > > > > not the way to do _discord.mwa.json - @CuteDog5695
> > > > 
> > > > 
> > > > What do i have to change?
> > > 
> > > 
> > > you are renaming mwa.json and putting URL and TXT. for _discord you just need txt - @CuteDog5695
> > 
> > 
> > Ohh soo you can only have txt and not url?
> 
> yea, _discord.mwa.json only needs TXT, not also with URL 

Btw am just changing the name for the discord connections? is that okay?

**Pull request closed without merging**
