### PR TITLE
Create urduck.json

### PR DESCRIPTION
**Pull request by MaskDuck**
:mmLol:

### CODE REVIEW

**Comment by MaskDuck** [comment]
mmLol

i wish i had an alt so i could use that alt to open the pr so i could approve to merge this pr myself

**Comment by asheeeshh** [comment]
> mmLol
> 
> i wish i had an alt so i could use that alt to open the pr so i could approve to merge this pr myself

lol, the best i can do is just approve this pr, hope they merge it soon and get-

**Review by asrvd — APPROVED** [review]

**Comment by MaskDuck** [comment]
i mean... i have the power to merge this pr, but pr authors cant approve their own prs

**Review by TheBotlyNoob — APPROVED** [review]
oh, hi!

**Comment by TheBotlyNoob** [comment]
*classic*

**Pull request merged**
