### PR TITLE
Create hironichu.json

### PR DESCRIPTION
**Pull request by hironichu**
I don't know if it will work, but I wanted to try with Deno deploy (https://deno.com)

That's an amazing project by the way.

### CODE REVIEW

**Review by MaskDuck — APPROVED** [review]
not sus

**Comment by MaskDuck** [comment]
hi there @hironichu, your pr have been merged, congrats!!!

now you have to config deno. i am not really sure how to config, but make sure ssl is installed!

dont forget to star the repo if you havent!

if you need help feel free to join our discord (link in readme) or create a new github issue.

**Comment by hironichu** [comment]
Yep all working fine ! 

Thank you!

**Comment by MaskDuck** [comment]
np

**Pull request merged**
