### PR TITLE
Register Subdomain: chaotic

### PR DESCRIPTION
**Pull request by ryanabraham1**
Added the domain: chaotic

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please use a valid record

**Comment by ChaoticChaosTheGreat** [comment]
What does it mean record?

**Comment by WilliamDavidHarrison** [comment]
> What does it mean record?

What the domain points to.

**Comment by ChaoticChaosTheGreat** [comment]
Oh ok my bad, does this work?

**Comment by ChaoticChaosTheGreat** [comment]
Ye, I changed the CNAME to a github.io link, as I see other people doing that. Hopefully this worm with your guidelines. Le tme know if you need any other changes

**Review by ryanabraham1 — COMMENTED** [review]
Added a github pages link, following the format of other people, should work?

**Review by omsenjalia — APPROVED** [review]
I think website is ok we can't really see cuz you're already redirecting to is-a.dev

**Comment by ChaoticChaosTheGreat** [comment]
> I think website is ok we can't really see cuz you're already redirecting to is-a.dev

Oh sorry, I saw someone adding a CNAME file and I assumed you needed one. I've deleted the file but it may take sometime to update. If you want to confirm checkout the repo at https://github.com/ChaoticChaosTheGreat/chaoticchaosthegreat.github.io

**Comment by TerraPlayz** [comment]
> > I think website is ok we can't really see cuz you're already redirecting to is-a.dev
> 
> Oh sorry, I saw someone adding a CNAME file and I assumed you needed one. I've deleted the file but it may take sometime to update. If you want to confirm checkout the repo at https://github.com/ChaoticChaosTheGreat/chaoticchaosthegreat.github.io

👍👍

**Review by omsenjalia — DISMISSED** [review]
Great website. I'll let a maintiner know

**Comment by ChaoticChaosTheGreat** [comment]
Thank you so much. I love how you are giving subdomains out, keep up the great work.

**Review by wdhdev — DISMISSED** [review]

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
