### PR TITLE
Update sx9.json

### PR DESCRIPTION
**Pull request by satr14washere**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [X] The file is in the `domains` folder and is in the JSON format.
- [X] You have completed your website. 
- [X] The website is reachable.  
- [X] You're not using Vercel or Netlify.  
- [X] The CNAME record doesn't contain `https://` or `/`.  
- [X] There is sufficient information at the `owner` field.

### CODE REVIEW

**Comment by SX-9** [comment]
Moving subdomains (srry)

**Review by wdhdev — APPROVED** [review]
RIP

P.S: You should totally get a domain [here](https://github.com/free-domains/register) as well. /j

**Comment by SX-9** [comment]
Bruh i was gonna fix an error in the json

**Comment by SX-9** [comment]
But thz

**Pull request merged**
