### PR TITLE
Please read the change description

### PR DESCRIPTION
**Pull request by sh1ft3r-2**
I want to change from cashlycash.is-a.dev to arnav.is-a.dev

### CODE REVIEW

**Comment by CashlyCash** [comment]
PLEASE DO

**Review by TheBotlyNoob — APPROVED** [review]

**Comment by TheBotlyNoob** [comment]
i'm really sorry about the wait

**Comment by CashlyCash** [comment]
Guys pls do it :(

**Comment by CashlyCash** [comment]
@TheBotlyNoob

**Comment by CashlyCash** [comment]
@tonetheman

**Pull request merged**
