### PR TITLE
I need an NS record becouse i need cf free ddos, no enterprise breaks…

### PR DESCRIPTION
**Pull request by ploszukiwacz**
Yea i need an NS record for free cf ddos prot.

No before you ask me to proxy it wont work, ask sillydev why not me.

### CODE REVIEW

**Comment by PlOszukiwaczDEV** [comment]
i need a 1min tutorial on fixing the tests frfr

**Comment by PlOszukiwaczDEV** [comment]
nvm i just needed to delete a file lmafo

**Comment by Satindar31** [comment]
What do you mean ddos protection won't work? When you add `proxied: true` to your file and ping the website, do you see your servers ip?

**Comment by wdhdev** [comment]
That's intended. Proxying will show Cloudflare's IPs instead of your origin server's IP.

**Comment by PlOszukiwaczDEV** [comment]
Yea but I don't think you understand.

The host I use only allows the free tier of ddos prot

Why? I have no idea

I think it has to do with the enterprise tier

**Comment by Satindar31** [comment]
Add proxied: true to your file and you will get cloudflare's enterprise grade ddos protection. You can test it by doing a DoS attack on your site. I won't give you instructions but you can find some educational videos regarding this on YouTube.

**Comment by PlOszukiwaczDEV** [comment]
Does bro can't read?

I told you it dosent work with enterprise

Ask sillydev not me why

**Comment by Satindar31** [comment]
What does not work? DDOS protection? How do you know it does not work? Have you tested it? 

Also, you can ask sillydev to join the conversation and tell us why it does not work. The maintainers are unpaid and you shouldn't expect them to run after you and find sillydev and inquire why the ddos prot doesn't work, you should have posted the reason while making the pr.


Note: I am **NOT** a maintainer. This is all from my POV. Williams and other maintainers POV may be different from mine.

**Comment by PlOszukiwaczDEV** [comment]
Yes I have tested it and no sillydev can't join becouse he doesn't have a GitHub account.

Also I am muted for the next 6 days from their dc server

**Comment by Satindar31** [comment]
> Yes I have tested it

How did you test it? What was the outcome?

> and no sillydev can't join becouse he doesn't have a GitHub account.

Can show show screenshots of your conversation with him where he explains why it isn't working? 

> Also I am muted for the next 6 days from their dc server

~~Skill issue ngl~~

**Comment by wdhdev** [comment]
In additon to what @Satindar31 said, what host are you using?

The difference between enterprise and free DDoS protection should not be an issue with any host I'm aware of.

**Comment by Satindar31** [comment]
> In additon to what @Satindar31 said, what host are you using?
> 
> The difference between enterprise and free DDoS protection should not be an issue with any host I'm aware of.

From the ip in his existing file, he seems to be using https://datalix.de/. It's a German hosting company.

**Comment by PlOszukiwaczDEV** [comment]
Also i need an A record and an CNAME record becouse i am moving to cf pages.

And its not possible with is-a.dev but it is with cf so heres another reason why i need NS records

**Comment by Satindar31** [comment]
It's not possible with cloudflare either. For that matter, it's not possible with any DNS provider that exists or ever will exist because you can't just point a domain to 2 servers(even if they're the same).

**Comment by PlOszukiwaczDEV** [comment]
sadge

**Comment by PlOszukiwaczDEV** [comment]
smh i cant provide a reason on mobile

**Comment by VaibhavSys** [comment]
> ask sillydev why not me.
We won't be asking anyone. It is your responsibility to convey all the necessary details to us for us to merge your PR.

**Comment by Satindar31** [comment]
> > ask sillydev why not me.
> 
> We won't be asking anyone. It is your responsibility to convey all the necessary details to us for us to merge your PR. 
> 
> (Why am I seeing this 2 weeks late though)
> 

Why beat a dead horse?

**Comment by PlOszukiwaczDEV** [comment]
> > ask sillydev why not me.
> 
> We won't be asking anyone. It is your responsibility to convey all the necessary details to us for us to merge your PR.
> 
> (Why am I seeing this 2 weeks late though)

why reply after its closed?

**Pull request closed without merging**
