### PR TITLE
Register dhanushs.is-a.dev

### PR DESCRIPTION
**Pull request by ipuppyyt**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://portfolio-bo4.pages.dev

### CODE REVIEW

**Comment by ipuppyyt** [comment]
Please let me know if something needs attention

**Review by MaskDuck — CHANGES_REQUESTED** [review]
come again when you finish your website

**Comment by ipuppyyt** [comment]
> come again when you finish your website

Actually i wanted a subdomain owned by someone else. As it was taken, i was forced to create this one. The one i wanted, when i checked out wasn't complete either. Not that progress as of me too.

https://dhanush.is-a.dev this is that person's which isn't completed yet.

Also i got one approved earlier without it being complete and lateron i finished it.

Please do consider.

**Comment by CuteDog5695** [comment]
> > come again when you finish your website
> 
> Actually i wanted a subdomain owned by someone else. As it was taken, i was forced to create this one. The one i wanted, when i checked out wasn't complete either. Not that progress as of me too.
> 
> https://dhanush.is-a.dev this is that person's which isn't completed yet.
> 
> Also i got one approved earlier without it being complete and lateron i finished it.
> 
> Please do consider.

Some maintainers merge unfinished sites, some do not btw

**Review by DEV-DIBSTER — DISMISSED** [review]

**Comment by orxngc** [comment]
Closing as stale.

**Pull request closed without merging**
