### PR TITLE
Create Foufou-exe.json

### PR DESCRIPTION
**Pull request by Foufou-exe**

### CODE REVIEW

**Review by MaskDuck — APPROVED** [review]
gud, let's wait for someone to merge this.

**Review by mtgsquad — DISMISSED** [review]

**Comment by MaskDuck** [comment]
wait

**Review by MaskDuck — CHANGES_REQUESTED** [review]
filename should be lowercase, sorry i didnt realize that filename should be lowercase =(

**Comment by MaskDuck** [comment]
well this is not gud, if you are reading this dont merge it until i delete this comment

**Comment by Foufou-exe** [comment]
Should I do it again or should I wait?

**Comment by MaskDuck** [comment]
rename the file.

**Comment by Foufou-exe** [comment]
Is it good?

**Review by MaskDuck — APPROVED** [review]
gud ig

**Comment by Foufou-exe** [comment]
Perfect ,Thx ✅

**Review by mtgsquad — APPROVED** [review]

**Pull request merged**
