### PR TITLE
BETA: Register arnab.is-a.dev

### PR DESCRIPTION
**Pull request by arnabdatta**
Added `arnab.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Review by Omxpro — APPROVED** [review]
good but are you sure you wanna redirect to github? insted i'd sugget using a CNAME record

**Comment by arnabdatta** [comment]
@Omxpro Okay i think thats good suggestion. How do I change the domain registration to CNAME?

**Comment by Omxpro** [comment]
> @Omxpro Okay i think thats good suggestion. How do I change the domain registration to CNAME?

just replace it with `username.github.io`

**Comment by arnabdatta** [comment]
> > @Omxpro Okay i think thats good suggestion. How do I change the domain registration to CNAME?
> 
> just replace it with `username.github.io`

Done. Thanks!

**Review by iostpa — APPROVED** [review]
seems good to me

**Pull request merged**
