### PR TITLE
BETA: Register mydesktop.is-a.dev

### PR DESCRIPTION
**Pull request by bigcacarouci**
Added `mydesktop.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Review by triach-rold — APPROVED** [review]
Website is reachable.

**Review by Stef-DP — DISMISSED** [review]
you should complete your website

**Comment by bigcacarouci** [comment]
> you should complete your website

Hello, thanks  for the feedback. I updated my website as a simple presentation. Hope it's all ok.
Have a nice day!

**Review by triach-rold — APPROVED** [review]
Site is reachable and has content. Very clean.

**Review by DEV-DIBSTER — APPROVED** [review]

**Pull request merged**
