### PR TITLE
BETA: Register mrinank.is-a.dev

### PR DESCRIPTION
**Pull request by Mrinank-Bhowmick**
Added `mrinank.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Review by DEV-DIBSTER — APPROVED** [review]

**Comment by Mrinank-Bhowmick** [comment]
@DEV-DIBSTER Please delete my file, i dont want it

**Comment by CuteDog5695** [comment]
> @DEV-DIBSTER Please delete my file, i dont want it

PR wasn't supposed to be merged, so we will remove it anyways

**Comment by CuteDog5695** [comment]
Wait, this was back in January, sorry. Domain was already removed since we shut down the hosting a while ago

**Comment by Mrinank-Bhowmick** [comment]
> Wait, this was back in January, sorry. Domain was already removed since we shut down the hosting a while ago

Actually my email is publically available here, so I want to delete this file.

**Comment by CuteDog5695** [comment]
File as in your PR? Your file was already moved back in February (I think?) since we shutdown is-a.dev hosting. Also I don't think you can remove your PR since it was already merged.

**Comment by Mrinank-Bhowmick** [comment]
> File as in your PR? Your file was already moved back in February (I think?) since we shutdown is-a.dev hosting. Also I don't think you can remove your PR since it was already merged.

Yeah, I guess the file no longer exists in that folder, but is there any way to remove or hide my email ID from this merged file?

**Pull request merged**
