### PR TITLE
Create debertjamie.json

### PR DESCRIPTION
**Pull request by triangular-snowman**

### CODE REVIEW

**Review by AbubakarKang — APPROVED** [review]

**Review by MaskDuck — APPROVED** [review]
not sus

**Comment by MaskDuck** [comment]
for some reason ci cant be ran =(

**Comment by debertjamie** [comment]
thanks! :)

**Comment by MaskDuck** [comment]
sorry for the delay in merging =(

**Comment by debertjamie** [comment]
no prob!

**Pull request merged**
