### PR TITLE
Update alfanaan.json

### PR DESCRIPTION
**Pull request by Alfanaannet**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.

### CODE REVIEW

**Comment by Alfanaannet** [comment]
h

**Comment by Alfanaannet** [comment]
a

**Comment by Alfanaannet** [comment]
[elfanaan.giize.com](https://www.dynu.com/en-US/ControlPanel/BasicEdit?ATVPDKIKX0DER=SQBEAD0AMQAwADEAMQA0ADkAOAA0AA%7C%7C#collapseDefault)

**Comment by Alfanaannet** [comment]
gg

**Comment by Alfanaannet** [comment]
AlfanaanNet

**Review by Alfanaannet — COMMENTED** [review]
a

**Comment by Alfanaannet** [comment]
adfsfds

**Review by DEV-DIBSTER — APPROVED** [review]

**Pull request merged**
