### PR TITLE
BETA: Register verifier-for-netlify.is-a.dev

### PR DESCRIPTION
**Pull request by Givaa**
Added `verifier-for-netlify.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Comment by Givaa** [comment]
needs to verify the other domani giovannirapa.is-a.dev

**Review by wdhdev — CHANGES_REQUESTED** [review]
We don't support Netlify also what were you intending to do with this domain?

**Comment by Givaa** [comment]
Hi William, i was trying to prove to Netlify that i possess the subdomain
giovannirapa.is-a.dev to change it on their site. I've chose to use FTP and
left Netlify,  so no worries.


Il giorno sab 23 set 2023 alle ore 05:06 William Harrison <
***@***.***> ha scritto:

**Comment by WilliamDavidHarrison** [comment]
@Givaa Can this PR be closed in that case?

**Pull request closed without merging**
