### PR TITLE
Register Subdomain: petla

### PR DESCRIPTION
**Pull request by petlachor**
To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [x] The website is reachable.
- [x] The CNAME record doesn't contain any slash.
- [x] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
404

**Comment by Petla-reboot** [comment]
> 404

What should I do?

**Comment by WilliamDavidHarrison** [comment]
> > 404
> 
> What should I do?

Make it accessible

**Comment by Petla-reboot** [comment]
> > > 404
> > 
> > 
> > What should I do?
> 
> Make it accessible

Sorry, how do I make what accessible?

**Comment by WilliamDavidHarrison** [comment]
Depends on how you host your website.

**Comment by Petla-reboot** [comment]
> Depends on how you host your website.

I'm specifying the IP address of the rental server I'm using in the A record, but I thought it wouldn't apply unless it was merged.
Or do I need to redirect to my server's default URL? (I don't want to do it this way if possible)

**Comment by WilliamDavidHarrison** [comment]
Please provide the port your website is on.

**Comment by Petla-reboot** [comment]
> Please provide the port your website is on.

port?

**Comment by WilliamDavidHarrison** [comment]
> > Please provide the port your website is on.
> 
> port?

For example: 1.1.1.1:3000
3000 would be the port.

**Comment by Petla-reboot** [comment]
> For example: 1.1.1.1:3000 3000 would be the port.

The port is open, so my other domain `petla.shop` is accessible.
Is the A record I wrote in the .json already applied? If they have, then maybe the IP address I gave the server is wrong.

**Review by wdhdev — APPROVED** [review]

**Review by petlachor — COMMENTED** [review]
I think the A record is correct.

**Review by MaskDuck — APPROVED** [review]

**Pull request merged**
