### PR TITLE
Register nyc.is-a.dev

### PR DESCRIPTION
**Pull request by savageemote1**
Register nyc.is-a.dev with A record pointing to 69.197.135.204.

### CODE REVIEW

**Review by iostpa — CHANGES_REQUESTED** [review]

**Comment by CuteDog5695** [comment]
Also since you are using a proxy for nyc.json, please give a preview of your website

**Comment by savageemote1** [comment]
image

I would provide more screenshots but the website is on my computer.

**Comment by TobezDev** [comment]
@savageemote1 
I see you are using windows. Use `Ctrl + Shift + S` to take a screenshot on your device.
To upload the screenshot, just come back here and add it to a new comment.

**Comment by savageemote1** [comment]
I Will be transferring it to a Hosting Once its complete from Reddit, I am aware that it turns off

**Comment by tobezdev** [comment]
All good, figured I'd just let you know in case you wasn't aware :)

**Review by triach-rold — CHANGES_REQUESTED** [review]
Currently unreachable.

**Pull request closed without merging**
