### PR TITLE
Added altudeVia is-a-dev-cli

### PR DESCRIPTION
**Pull request by itslevir**
Added altudevia the CLI

### CODE REVIEW

**Comment by altude** [comment]
is the cli open source because i want to add a space to the issue title if it is

**Comment by WilliamDavidHarrison** [comment]
> is the cli open source because i want to add a space to the issue title if it is

It would be nice to be fixed.

Repo: https://github.com/andrewstech/is-a-dev-cli

**Review by wdhdev — CHANGES_REQUESTED** [review]
I just need you to provide an email then I can merge.

**Comment by altude** [comment]
fixed

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
