### PR TITLE
create mlmesa2.json

### PR DESCRIPTION
**Pull request by mlmesa2**

### CODE REVIEW

**Review by TheBotlyNoob — CHANGES_REQUESTED** [review]
The `CNAME` cannot have a `/`, try renaming your repo to `mlmesa2.github.io`, then change the `CNAME` to just `mlmesa2.github.io`

**Review by hackermondev — CHANGES_REQUESTED** [review]
CNAME cannot have a path so it must be ``mlmesa2.github.io``

**Comment by mtgsquad** [comment]
@mlmesa2, Would you still like this subdomain? Please fix the mistakes and do the requested changes, and you'll be ready to start using `is-a.dev`.

**Comment by TheBotlyNoob** [comment]
closing because of inactivity

**Pull request closed without merging**
