### PR TITLE
Register Subdomain: sukirthan

### PR DESCRIPTION
**Pull request by SukiPlayz**
Added the domain: sukirthan

### CODE REVIEW

**Comment by SukiPlayz** [comment]
wait why there's still that technoblade.json ?

**Review by wdhdev — CHANGES_REQUESTED** [review]
I can't reach your website

**Comment by SukiPlayz** [comment]
> I can't reach your website

What do you mean by can't reach your website? Just only creating it. @WilliamDavidHarrison

**Comment by WilliamDavidHarrison** [comment]
Sorry, your website needs to be completed / partially completed for me to accept the domain.

**Pull request closed without merging**
