### PR TITLE
Mail and proxy and rename

### PR DESCRIPTION
**Pull request by omsenjalia**

### CODE REVIEW

**Comment by omxpro** [comment]
Might also add Yandex Mail Support

**Review by MaskDuck — DISMISSED** [review]
no cname with other records ty

**Comment by omxpro** [comment]
Do i give cname its own "record": thing?

**Comment by omxpro** [comment]
I gotta go brb

**Comment by omxpro** [comment]
@MaskDuck fixed it

**Review by mtgsquad — APPROVED** [review]

**Pull request merged**
