### PR TITLE
Create ldt.json

### PR DESCRIPTION
**Pull request by luongductrong**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

[https://luongductrong.github.io/]

### CODE REVIEW

**Review by iostpa — CHANGES_REQUESTED** [review]
Site isn't accessible because its redirecting to the is-a.dev domain that you want to get.
To make the site accessible for us, please remove the `CNAME` file located at your websites repository.

**Comment by luongductrong** [comment]
> Site isn't accessible because its redirecting to the is-a.dev domain that you want to get. To make the site accessible for us, please remove the `CNAME` file located at your websites repository.

I did, thank you

**Review by iostpa — APPROVED** [review]
Seems good to me now

**Comment by CuteDog5695** [comment]
Forgot about this PR for a second

**Pull request merged**
