### PR TITLE
Register Subdomain: debargha

### PR DESCRIPTION
**Pull request by DebarghaXD**
Added the domain: debargha

### CODE REVIEW

**Comment by WilliamDavidHarrison** [comment]
@DebarghaXD CNAME records can not have `https://` or `/`

**Comment by DebarghaXD** [comment]
> @DebarghaXD CNAME records can not have `https://` or `/`

My bad, I edited it.

**Comment by WasabiThumb** [comment]
DID I JUST GET RICKROLLED IN 2022

**Comment by WilliamDavidHarrison** [comment]
> DID I JUST GET RICKROLLED IN 2022

How is this related?

**Comment by DebarghaXD** [comment]
> > DID I JUST GET RICKROLLED IN 2022
> 
> How is this related?

Actually my main domain i.e. debargha.tk is a rickroll lmao

**Review by andrewstech — APPROVED** [review]

**Pull request merged**
