### PR TITLE
Register tomiszivacs.is-a.dev

### PR DESCRIPTION
**Pull request by TomiSzivacs**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.

### CODE REVIEW

**Comment by user0-07161** [comment]
Sorry; he is very new to GitHub, I am helping him with this

**Comment by user0-07161** [comment]
Here is the updated description:


## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- :white_check_mark:  The file is in the `domains` folder and is in the JSON format.
- :white_check_mark:  The file's name is all lowercased and alphanumeric. 
- :x: You have completed your website.   --> Side-note: Website will we finished soon, please wait a few days
- :white_check_mark:  The website is reachable.    
- :white_check_mark:  The CNAME record doesn't contain `https://` or `/`.  
- :white_check_mark:  There is sufficient information at the `owner` field.  

## Website Link/Preview

https://tomiszivacs.github.io/

**Comment by user0-07161** [comment]
We'll let you know once the website is finished.

**Comment by user0-07161** [comment]
Oh shit-

**Comment by user0-07161** [comment]
Could you do that? As I do not have write permissions to that fork

**Comment by user0-07161** [comment]
Anyways the website is done so far

**Comment by user0-07161** [comment]
Or actually, close this, I'll just create a new one PR.

**Comment by user0-07161** [comment]
Check #14722; this one (#14707 can be closed.)

**Comment by CuteDog5695** [comment]
Since the other PR for the exact domain has been merged, I'll close this PR now

**Pull request closed without merging**
