### PR TITLE
Register beast.is-a.dev

### PR DESCRIPTION
**Pull request by BEAST2802**
Added `beast.is-a.dev` using the [CLI](https://www.npmjs.com/package/@is-a-dev/cli).

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please add more content to your website

**Comment by BEAST2802** [comment]
> Please add more content to your website

i will add, i am currently making it, just wanted to secure the sub-domain so none takes it

**Comment by WilliamDavidHarrison** [comment]
@BEAST2802 Unfortunately, your website needs to be complete before we can give you the subdomain. You also don't need to worry about someone taking your subdomain name.

**Comment by BEAST2802** [comment]
> @BEAST2802 Unfortunately, your website needs to be complete before we can give you the subdomain. You also don't need to worry about someone taking your subdomain name.

Ok then i will complete the website first

**Pull request merged**
