### PR TITLE
BETA: Update glqch.is-a.dev

### PR DESCRIPTION
**Pull request by Glqch404**
Updated `glqch.is-a.dev` using the site.

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please use a valid record.

**Comment by joythejoystick1** [comment]
> Please use a valid record.

**Comment by joythejoystick1** [comment]
i replaced the CNAME with TXT and placed the txt u specified, but github also gave me a value for it, where do i place it

**Comment by WilliamDavidHarrison** [comment]
You set the TXT as the value and the name as the domain file name.

**Comment by joythejoystick1** [comment]
okay i put the value github gave me into the TXT section, but the name is already glqch.is-a.dev, i dont understand the name part

**Comment by WilliamDavidHarrison** [comment]
You need to keep your original domain the same and create a new file with the name GitHub gave you and a TXT with the value they gave you.

**Comment by joythejoystick1** [comment]
Im very sorry im taking much of your time but Its because im lost, i read the whole documentation about github pages and i set it up correctly as it said, but it didn't mention anything about TXT or Value Or adding a new file with the name github provided, if it is possible would u mind contacting me in discord and we can finish this in less than 5 mins, its not that im stupid, trust me im very experienced in these things but the docs dont even mention this, and i cant set it up without using a tutorial over PR's, My discord username is "glqch"

**Comment by WilliamDavidHarrison** [comment]
Please provide the details GitHub has given you (the record name and value)

**Comment by joythejoystick1** [comment]
Record name:_github-pages-challenge-joythejoystick1.glqch

Value:eb682c2a35bd6139b653df86f7d248

**Review by wdhdev — DISMISSED** [review]

**Review by wdhdev — APPROVED** [review]

**Comment by joythejoystick1** [comment]
I cant describe to u how thankful i am to u, once i added the files u put in here, everything started working, i was able to verify the domain in like 1 minute, i added it in the custom domains section, it took 5 mins for it ti ve provisioned and it worked, i wanna thank u for guiding me through this not-so-hard-thing-i-thought-was-complicted, and sorry for making u explain everything at a higher level

**Comment by joythejoystick1** [comment]
My website is now online thanks to u <3

**Comment by WilliamDavidHarrison** [comment]
No problem, I'm happy to help :)

**Comment by Glqch404** [comment]
Hey i changed my name on github and changed the json file please push the changes to manage.is-a.dev

**Pull request merged**
