### PR TITLE
BETA: Register williamsebastian.is-a.dev

### PR DESCRIPTION
**Pull request by BaseParody**
Added `williamsebastian.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Comment by BaseParody** [comment]
kindly chek this domain also

**Comment by BaseParody** [comment]
feat(domain): devhub.is-a.dev

**Comment by BaseParody** [comment]
feat(domain): williamsebastian.is-a.dev

**Comment by BaseParody** [comment]
feat(domain): williamsebastian.is-a.dev

**Review by DEV-DIBSTER — APPROVED** [review]

**Pull request merged**
