### PR TITLE
add sub-domain

### PR DESCRIPTION
**Pull request by an1ndra**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [X] The file is in the `domains` folder and is in the JSON format.
- [X] You have completed your website. 
- [X] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [X] The CNAME record doesn't contain `https://` or `/`.  
- [X] There is sufficient information at the `owner` field.

### CODE REVIEW

**Review by wdhdev — APPROVED** [review]

**Comment by meanindra** [comment]
getting  `DNS check unsuccessful` error
```error
meanindra.is-a.dev is improperly configured
Your site's DNS settings are using a custom subdomain, meanindra.is-a.dev, that is set up as an A record. We recommend you change this to a CNAME record pointing to meanindra.github.io. For more information, see [documentation](https://docs.github.com/articles/setting-up-a-custom-domain-with-github-pages/) (InvalidARecordError).
```

**Comment by WilliamDavidHarrison** [comment]
Please wait 24 hours.

**Comment by meanindra** [comment]
@WilliamDavidHarrison  still getting same error

**Comment by WilliamDavidHarrison** [comment]
Can you please open an issue where we can help you further.

**Pull request merged**
