### PR TITLE
Major removal of inaccessible and hijacked domains.

### PR DESCRIPTION
**Pull request by iostpa**

### CODE REVIEW

**Review by wdhdev — APPROVED** [review]

**Comment by iostpa** [comment]
@whinee @oyepriyansh The domain you guys own are being removed due to it being hijacked. If you want to reclaim the domain, make a new PR.

**Comment by wdhdev** [comment]
Also verify the domains with GitHub Pages so that way they cannot be hijacked in the future even if they are not used :wink:

**Comment by whinee** [comment]
ive lost interest in the domain now huhuu thanks for the heads up tho!

**Comment by iostpa** [comment]
@sanoojes forgot to mention you here, since I removed a nested subdomain from you

**Comment by sanoojes** [comment]
> @sanoojes forgot to mention you here, since I removed a nested subdomain from you since it was hijacked

Oh, thank you so much! I completely forgot about that blog page. I started working on it but never created a good one, so I abandoned it. But I don't know what you mean by hijacked domains.

**Comment by iostpa** [comment]
Basically someone hijacked your blog domain to make it a indonesian casino scam site.

**Comment by iostpa** [comment]
Like this (seems that google still has it indexed)
image

**Comment by sanoojes** [comment]
> Like this (seems that google still has it indexed) image

oops how is this done and how can i prevent this from happening ?

**Comment by wdhdev** [comment]
You can verify `yourname.is-a.dev` in your account settings > Pages.

**Pull request merged**
