### PR TITLE
Update almightynan.json

### PR DESCRIPTION
**Pull request by almightynan**

### CODE REVIEW

**Review by wdhdev — DISMISSED** [review]

**Comment by AlmightyNan** [comment]
@WilliamDavidHarrison can you review this pr

**Comment by WilliamDavidHarrison** [comment]
> @WilliamDavidHarrison can you review this pr

I've approved it but I can't merge PR's.

**Comment by AlmightyNan** [comment]
> > @WilliamDavidHarrison can you review this pr
> 
> I've approved it but I can't merge PR's.

Alright, thanks for approving

**Comment by AlmightyNan** [comment]
@andrewstech can you merge this pr?

**Comment by AlmightyNan** [comment]
@andrewstech @WilliamDavidHarrison can you review this for the last time?

**Review by wdhdev — APPROVED** [review]

**Review by MaskDuck — APPROVED** [review]

**Pull request merged**
