### PR TITLE
Added robot0730

### PR DESCRIPTION
**Pull request by Robotsrule4545**
Added robot0730via the CLI

### CODE REVIEW

**Comment by Robotsrule4545** [comment]
should i use my public IP?

**Comment by WilliamDavidHarrison** [comment]
> should i use my public IP?

What do you mean by public IP?

Also, I can't reach `218.188.208.192`

**Review by MaskDuck — CHANGES_REQUESTED** [review]

**Review by wdhdev — CHANGES_REQUESTED** [review]
I can't reach your website

**Comment by WilliamDavidHarrison** [comment]
Unreachable website + no email + no response.

**Pull request closed without merging**
