### PR TITLE
Create mysterek.json

### PR DESCRIPTION
**Pull request by mysterek1337**
sus amogus

### CODE REVIEW

**Comment by mysterek1337** [comment]
someone??

**Review by phenax — CHANGES_REQUESTED** [review]
Sorry for the delay (#1529). `A` record value has to be an array of ips.

**Review by malbouy — CHANGES_REQUESTED** [review]
Try using this?
```
{
    "owner": {
      "username": "mysterek1337",
      "email": "mysterekkonto@gmail.com"
    },
    "record": {
      "A": ["51.77.48.172"]
    }
  }
```

**Comment by mysterek1337** [comment]
> Try using this?
> 
> ```
> {
>     "owner": {
>       "username": "mysterek1337",
>       "email": "mysterekkonto@gmail.com"
>     },
>     "record": {
>       "A": ["51.77.48.172"]
>     }
>   }
> ```

ITS BEEN 2 MONTHS AGO, SERVERS DIED!!

**Pull request closed without merging**
