### PR TITLE
Create client.nziie

### PR DESCRIPTION
**Pull request by Nzii3**
Adds a subdomain for my services page.

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview
https://nziie.is-a.dev/

### CODE REVIEW

**Review by andrewstech — CHANGES_REQUESTED** [review]
I see this is a sellpass site. What do you plan on selling?

**Comment by Nzii3** [comment]
> I see this is a sellpass site. What do you plan on selling?

I sell bot services on Discord, I make bots for people. And im not using sellpass anymore, using sellix but i don't need anymore, so im closing this.

**Comment by Nzii3** [comment]
Actually @andrewstech I do need this domain, but I'm not using Sellix anymore, I am using WHMCS to sell my Discord bot creation services.

**Comment by Nzii3** [comment]
Going to edit the cname in a little bit.

**Comment by Nzii3** [comment]
Actually @andrewstech I do need this domain, but I'm not using Sellix anymore, I am using a different billing system.

**Comment by WilliamDavidHarrison** [comment]
@Nzii3 I don't think we can allow a domain which sells anything, sorry about this.

**Comment by Nzii3** [comment]
@WilliamDavidHarrison it doesn’t say anywhere we can’t use subdomains for billing services.

**Comment by Nzii3** [comment]
You also said you “think”. Shouldn’t you actually check :/

**Comment by Nzii3** [comment]
I’m literally selling discord bot services, nothing illegal.

**Comment by WilliamDavidHarrison** [comment]
My decision is final.

**Comment by mtgsquad** [comment]
@Nzii3 We're pretty sure we can't authorize selling on our domains. A major reason for this, is that scams are possible, you could in theory modify the page, to basically be a page to buy subscription's to is-a.dev, and it would be on an our domain, so it could make people prone to scams. We will wait until the maintainers can fully discuss this.

**Pull request closed without merging**
