### PR TITLE
Create glutis

### PR DESCRIPTION
**Pull request by huyvu15**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.

### CODE REVIEW

**Comment by huyvu15** [comment]
thanks for sharing

**Review by iostpa — CHANGES_REQUESTED** [review]
File isn't in json format.

**Review by iostpa — CHANGES_REQUESTED** [review]
Now its good

**Review by iostpa — APPROVED** [review]
Whoops

**Pull request merged**
