### PR TITLE
Register Subdomain: david-elbaz

### PR DESCRIPTION
**Pull request by DavidELBAZpro**
Added the domain: david-elbaz

### CODE REVIEW

**Review by omsenjalia — CHANGES_REQUESTED** [review]
Hey. URL record is invalid. It needs to start with https://. please read [docs](https://is-a.dev/docs) or join our discord server for more help

**Review by omsenjalia — CHANGES_REQUESTED** [review]
Hey. URL record is invalid. It needs to start with https://. please read [docs](https://is-a.dev/docs) or join our discord server for more help

**Comment by TerraPlayz** [comment]
Sorry my internet sent it 2 times

**Comment by TerraPlayz** [comment]
@DavidELBAZpro you have 2 days (yesterday was already counted as a day so total 3 days) to fix this issue or @WilliamDavidHarrison will close the PR

**Comment by WilliamDavidHarrison** [comment]
Extended period of time given, no response.

**Pull request closed without merging**
