### PR TITLE
Create balloon.json

### PR DESCRIPTION
**Pull request by fu-sen**
I want `balloon.is-a.dev` 🎈))
This CNAME is the server that runs the Telnet BBS. This server is running [Caddy](https://caddyserver.com/).
I will issue [ZeroSSL](https://zerossl.com/). It doesn't seem to have been issued yet: https://crt.sh/?q=is-a.dev

### CODE REVIEW

**Review by hackermondev — APPROVED** [review]
idk

**Comment by fu-sen** [comment]
Okay. That's what I expected from admin comments.
It will be useful when using web services and VPS in the future.

The point destination of CNAME, `bbs.yt`, is registered in [FreeDNS](https://freedns.afraid.org/).
https://freedns.afraid.org/domain/registry/?sort=5&q=bbs.yt&submit=SEARCH

I use this Dynamic DNS to refer to a web server [Caddy](https://caddyserver.com/) running on Windows.

Is there any other information you are missing to understand?

**Review by TheBotlyNoob — APPROVED** [review]

**Comment by fu-sen** [comment]
To give you more peace of mind, I have set up a dedicated repository.
You can edit `repo` or will pull request again for changes. (Due to the waiting situation for merge, this edit had to wait once)
https://github.com/fu-sen/balloon.is-a.dev

**Review by phenax — APPROVED** [review]
@fu-sen As long as the CNAME resolves, it should work. CNAME records have to issue their own certificates which I'm assuming you will figure that out.

**Comment by phenax** [comment]
The changes have been published!! It should reflect in less than 24 hours.

## Here's what you need to do next
If your domain points to a server you own, add \`domain-name.is-a.dev\` to your server config. For https, you will have to configure ssl certificate to allow the new subdomain.

### For github pages users,
* Go to your github page repo (\`user/user.github.io\`)
* Open up the **settings** tab
* Scroll down to the **Github pages** section
* In the **Custom domain** text input, enter the domain you registered (\`domain-name.is-a.dev\`)
* Check the **Enforce HTTPS** checkbox below the input
* Give it some time to reflect and you should be good to go


## Need help with your domain?
If you are having trouble setting up your domain, [create an issue](https://github.com/is-a-dev/register/issues/new/choose). I will try my best to get back to you asap!


## Made a mistake in the record?
Don't worry, you can create a new pull request with the corrections


## Love/Hate the service?
**Love it?** Leave it a **star**! Also consider donating so that I can keep this service running forever!
**Hate it?** Please leave your feedback by [creating an issue](https://github.com/is-a-dev/register/issues/new/choose). I would really like to keep improving this service for other users.


## Wanna support this project?
Help me in my mission to keep this service alive forever by donating!

<a href="https://www.buymeacoffee.com/phenax" target="_blank">Buy Me A Coffee</a> <a href="https://liberapay.com/phenax" target="_blank">Liberapay recurring donation button</a>

**Comment by fu-sen** [comment]
Thank you for registering so far! 😄
I intended to apply for registration, which is difficult for administrators to verify, but it went smoothly.
Because I wanted to use ZeroSSL instead of Let's Encrypt. Don't worry, I'm used to the procedure. 🔒
(I used to sell it as a reseller of SSL certificates, domain and rental server. At that time there was no VPS yet)
I get the name server reflection and make the website visible. 🚀

**Pull request merged**
