### PR TITLE
Create stefdp.json

### PR DESCRIPTION
**Pull request by Stef-DP**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://stef-00012.github.io

### CODE REVIEW

**Comment by Stef-00012** [comment]
gbot.json url is https://sdp-gbot.github.io

**Comment by Stef-00012** [comment]
`receiptify.json` url is https://sdp-receiptify.github.io

**Comment by SDP-Receiptify** [comment]
receiptify is on this acc

**Comment by Stef-00012** [comment]
stefdp is on this acc

**Comment by Stef-00012** [comment]
(yes, i made other 2 accs just for that)

**Review by DEV-DIBSTER — APPROVED** [review]

**Pull request merged**
