### PR TITLE
Added mitchVia is-a-dev-cli

### PR DESCRIPTION
**Pull request by liao02x**
Added mitchvia the CLI

### CODE REVIEW

**Review by omsenjalia — CHANGES_REQUESTED** [review]
I cannot reach that site

**Review by wdhdev — CHANGES_REQUESTED** [review]
Cannot reach website

**Comment by liao02x** [comment]
My new portfolio is WIP. I linked it to a starter for now.

**Comment by WilliamDavidHarrison** [comment]
Sorry, you need to finish your website first.

**Comment by liao02x** [comment]
The starter is not just the boilerplate. I was working on a whole website by myself and it might take another month or so. So I got a simpler template and ported the about page to it. So far it works and has valid content. Is there any other requirement? Do you want me to port a few of my notes and blogs to it just to show more content?

**Comment by WilliamDavidHarrison** [comment]
@liao02x It seems you're using Vercel. What you need to do is update your record to `"URL": "https://portfolio-mliao.vercel.app/"` for it to work with is-a.dev

**Comment by liao02x** [comment]
As I said earlier, the url "https://portfolio-mliao.vercel.app/" is just a placeholder for now. I implement a redirect to it from "114032.xyz" because the site would eventually be moved here and I just want to save some extra steps. Do you want me to have the record as "URL" for now and update it to "CNAME" afterward? Is it supported to update a record?

**Comment by WilliamDavidHarrison** [comment]
> As I said earlier, the url "https://portfolio-mliao.vercel.app/" is just a placeholder for now. I implement a redirect to it from "114032.xyz" because the site would eventually be moved here and I just want to save some extra steps. Do you want me to have the record as "URL" for now and update it to "CNAME" afterward? Is it supported to update a record?

As Vercel is not supported as a CNAME you'll need to use a URL record.

**Comment by liao02x** [comment]
> > As I said earlier, the url "https://portfolio-mliao.vercel.app/" is just a placeholder for now. I implement a redirect to it from "114032.xyz" because the site would eventually be moved here and I just want to save some extra steps. Do you want me to have the record as "URL" for now and update it to "CNAME" afterward? Is it supported to update a record?
> 
> As Vercel is not supported as a CNAME you'll need to use a URL record.

Please refer to the content. I am doing a CNAME from ".is-a.dev" domain to my domain "114032.xyz", not the vercel one. The content for "114032.xyz" is not finished yet, and you require a valid website for the ".is-a.dev" target, so I implement a 302 redirect from "114032.xyz" to "portfolio-mliao.vercel.app". The vercel support shouldn't be an issue, and it would be there for a long. Now do you need anything else from me?

**Review by wdhdev — APPROVED** [review]
Sorry for the confusion.

**Pull request merged**
