### PR TITLE
Register Subdomain: tushardeo

### PR DESCRIPTION
**Pull request by tusharvikky**
Added the domain: tushardeo

### CODE REVIEW

**Review by omsenjalia — CHANGES_REQUESTED** [review]
A record cannot contain cloud flare dns's ip

**Review by omsenjalia — DISMISSED** [review]
Good website

**Review by omsenjalia — APPROVED** [review]
This works

**Comment by tusharvikky** [comment]
👍

**Review by wdhdev — APPROVED** [review]

**Comment by tusharvikky** [comment]
@WilliamDavidHarrison : Build failed and I can see error while trying to access the configuration.
Test: 
(1) https://tushar.is-a.dev/
(2) https://tushardeo.is-a.dev/

**Comment by WilliamDavidHarrison** [comment]
> @WilliamDavidHarrison : Build failed and I can see error `ERR_SSL_VERSION_OR_CIPHER_MISMATCH ` while trying to access the configuration. Test: (1) https://tushar.is-a.dev/ (2) https://tushardeo.is-a.dev/

Try opening a new PR using a URL record instead.

**Pull request merged**
