### PR TITLE
Added moh via is-a-dev-cli

### PR DESCRIPTION
**Pull request by minoyahia**
Added moh via the CLI

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please use a valid record.

**Comment by minoyahia** [comment]
> Please use a valid record.

hello! sorry for messing it up, hope that i got it right this time

**Review by wdhdev — APPROVED** [review]
I see you're using my friend, @SX-9's code lol

**Comment by minoyahia** [comment]
> I see you're using my friend, @SX-9's code lol

yeah, saw his profile in discord, since i have no website at the moment used it

**Comment by WilliamDavidHarrison** [comment]
> > I see you're using my friend, @SX-9's code lol
> 
> yeah, saw his profile in discord, since i have no website at the moment used it

He opened a PR on your website to credit him, I reckon you should merge it.

**Comment by SX-9** [comment]
@minoyahia please dont copycat peoples code

**Pull request merged**
