### PR TITLE
Register abhrajitdas.is-a.dev

### PR DESCRIPTION
**Pull request by Abhrajitdas02**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.

### CODE REVIEW

**Review by iostpa — CHANGES_REQUESTED** [review]

**Review by iostpa — APPROVED** [review]
Should be fine now (also nice website!)

**Comment by CuteDog5695** [comment]
> > Should be fine now (also nice website!)
> 
> Thanks a lot!! When will I receive the domain?

DNS should propogate around 24 hours, then domain will be pointing to your website

**Comment by CuteDog5695** [comment]
> > > > Should be fine now (also nice website!)
> > > 
> > > 
> > > Thanks a lot!! When will I receive the domain?
> > 
> > 
> > DNS should propogate around 24 hours, then domain will be pointing to your website
> 
> Will there be any problem as I have given the as my original website was hosted originally at CNAME: https://abhrajitdas02.github.io/Portfolio-Website/ But it was changed to abhrajitdas.github.io !!

You can connect the domain to there even if I changed it to abhrajidas.github.io, if I left it like that it would of been invalid.

**Comment by CuteDog5695** [comment]
You just go to the repo your website is on and connect the domain there

**Pull request merged**
