### PR TITLE
.

### PR DESCRIPTION
**Pull request by S4IL21**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

emvas.s4il.json should be s4il21.github.io/Submarine-EMVAS
and
0.json should be s4il21.github.io/0

### CODE REVIEW

**Comment by S4IL21** [comment]
emvas.s4il.json should be s4il21.github.io/Submarine-EMVAS
and 
0.json should be s4il21.github.io/0

**Review by iostpa — CHANGES_REQUESTED** [review]
What Sono said.

**Comment by CuteDog5695** [comment]
> s4il21.github.io/0

That site redirects to the is-a.dev domain, please remove it so that I can see the site.

**Review by iostpa — APPROVED** [review]
Its fine now.

**Pull request merged**
