### PR TITLE
Create tclement0922.json

### PR DESCRIPTION
**Pull request by tclement0922**

### CODE REVIEW

**Review by MaskDuck — APPROVED** [review]
**[404 SUS POWER NOT FOUND]**

**Comment by MaskDuck** [comment]
now you need to config github pages. you can find how [here](https://github.com/is-a-dev/register/blob/main/docs/hosted-at/github-pages.md)!
**[OPTIONAL]** go star the repo pls

**Comment by tclement0922** [comment]
Done! Thanks :)

**Comment by niyazahmad6103-eng** [comment]
Mera work nhi kar Raha hai

**Pull request merged**
