### PR TITLE
Create dinothedev.json

### PR DESCRIPTION
**Pull request by ghost**
For me dinothedev

### CODE REVIEW

**Review by phenax — CHANGES_REQUESTED** [review]
If you meant to use URL redirection, use URL instead of CNAME. If you meant to use a subdomain, please read repl.co's documentation regarding custom subdomains.

**Comment by DinoTheDevOfficial** [comment]
I know how replits domain thing works you need to use a cname pointing to a replit. if you create a replit the same as your username it assigns the replit the <username>.repl.co domain

**Comment by phenax** [comment]
@DinoTheDevOfficial, CNAME's are hostnames not urls. As you may have seen in the repl it docs, there is no `https://` in the CNAME so in this case you'll need to remove it

**Comment by DinoTheDevOfficial** [comment]
fixed

**Review by phenax — APPROVED** [review]

**Pull request merged**
