### PR TITLE
Fix cname record for forum.cupglass.is-a.dev

### PR DESCRIPTION
**Pull request by ghost**
Sorry, i didnt read it carefully. So instead of
`cname.freeflarum.com`
it SHOULD point to that domain WITH a dot at the end, like this
`cname.freeflarum.com.`
https://docs.freeflarum.com/en/tutorials/custom-domain/

(even the checks are throwing an error because of the dot, but i didnt expect this to be required, a single dot???)

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.

### CODE REVIEW

**Comment by DEV-DIBSTER** [comment]
@cupglassDEV You're records are correct from before.

**Comment by cupglassDEV** [comment]
> @cupglassDEV You're records are correct from before.

But it says i need to point with a dot, because when i tried it this happens

image

**Comment by DEV-DIBSTER** [comment]
> But it says i need to point with a dot, because when i tried it this happens

We already handle the "." at the end, so you're records from before should have already propagated. You can also see that the validation fails when you have the "." per our DNS rules.

**Comment by cupglassDEV** [comment]
> > But it says i need to point with a dot, because when i tried it this happens
> 
> We already handle the "." at the end, so you're records from before should have already propagated. You can also see that the validation fails when you have the "." per our DNS rules.

Oh okay, thanks for the help! I will try to point it again on the forum settings
Thank you :)

**Comment by EducatedSuddenBucket** [comment]
@cupglassDEV that is issue from freeflarum due to dns propagation, domains without and with  work same for eg both google.com and google.com. will work on a browser. I have used deno with is-a.dev they also gave cname with dots but it works even in the json I didn't add dot in the cname

**Comment by cupglassDEV** [comment]
> @cupglassDEV that is issue from freeflarum due to dns propagation, domains without and with work same for eg both google.com and google.com. will work on a browser. I have used deno with is-a.dev they also gave cname with dots but it works even in the json I didn't add dot in the cname

Oh, thanks for the reply! <sup>I might try to remove this json file soon 😉™️</sup>

**Pull request closed without merging**
