### PR TITLE
Add Domain MazenGohar

### PR DESCRIPTION
**Pull request by MazenMostafaGohar**

### CODE REVIEW

**Review by MaskDuck — APPROVED** [review]
nice

**Comment by MaskDuck** [comment]
hi there, @MazenGohar! your pr is now merged, congrat!

now you need to config. base on your domain i cant know the hosting provider you use, but please include `mazengohar.is-a.dev` in your ssl!

pls star the repo if you havent

if you need help feel free to join our discord or create a new github issue.

**Comment by MazenGohar** [comment]
what do you mean by config the base on domain?

**Comment by MaskDuck** [comment]
i mean, base on your domain name, i couldn't identify the hosting provider you are using.

**Comment by MazenGohar** [comment]
my hosting says verified and added custom domain but it still redricts me to is-a.dev.

**Comment by MaskDuck** [comment]
even in incognito?

**Comment by MazenGohar** [comment]
yes......

**Comment by MaskDuck** [comment]
it is working for me

**Comment by MaskDuck** [comment]
but redirect to 404

**Comment by MazenGohar** [comment]
here is an imag
Screenshot (18)
e

**Comment by MazenGohar** [comment]
oh, I forgot, I didn't still upload the site!

**Comment by MazenGohar** [comment]
I uploaded the website files to my site and it still gives the same error

**Comment by MazenGohar** [comment]
could you send an image of what your page looks like?

**Comment by MaskDuck** [comment]
image

**Comment by MazenGohar** [comment]
sorry but where can I add the base url? I think I found it.
Is it in the repo or do I add it in my hosting service?
I get the same error because I still yet didn't upload my files
here is a screenshot
Screenshot (19)

**Comment by MazenGohar** [comment]
the following image is in the base url

**Comment by MazenGohar** [comment]
I fixed it now, by clearing browser cache.

**Pull request merged**
