### PR TITLE
Badges ✨

### PR DESCRIPTION
**Pull request by s3mant**
better looking readme badges ✨

### CODE REVIEW

**Comment by MaskDuck** [comment]
patch 12 wtf

**Comment by MaskDuck** [comment]
patch 69420 when:tm:

**Comment by MaskDuck** [comment]
also can you show an example of the edited file

**Comment by Bad-Boy-Codes** [comment]
> patch 12 wtf

💀

**Comment by Bad-Boy-Codes** [comment]
> patch 12 wtf

wait no
that was my patch
but nvm i created new one

**Pull request closed without merging**
