### PR TITLE
Register anay.is-a.dev

### PR DESCRIPTION
**Pull request by anay-208**
Added `anay.is-a.dev` using the [CLI](https://www.npmjs.com/package/@is-a-dev/cli).

### CODE REVIEW

**Comment by Anay028** [comment]
Hi, Here's the link to source code: https://github.com/anay028/portfolio
Live website: https://anay028.github.io/portfolio

**Review by wdhdev — APPROVED** [review]

**Comment by Anay028** [comment]
Hi, thanks for approving my request. For some reason, I m getting this error in github when I am trying to add the domain. Thanks!
image

**Comment by Anay028** [comment]
@WilliamDavidHarrison, I added the DNS, and still for some reason, my site isn't working. On github, it says DNS check successful. Would you mind helping me with this.

**Comment by WilliamDavidHarrison** [comment]
Please open an issue and we can help you there.

**Pull request merged**
