### PR TITLE
Added gitcat3Via is-a-dev-cli

### PR DESCRIPTION
**Pull request by GitCat3**
Added gitcat3via the CLI

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please specify an email and finish your website.

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please finish your website.

**Comment by GitCat3** [comment]
Working on it, should I set the or until it is finished?

**Comment by WilliamDavidHarrison** [comment]
You need to finish the website before we can give you the domain. You can keep this PR open.

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
