### PR TITLE
Add Domain devdreamer.is-a.dev

### PR DESCRIPTION
**Pull request by swasthik-s**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.

### CODE REVIEW

**Review by MaskDuck — CHANGES_REQUESTED** [review]
file is empty

**Comment by swasthik-s** [comment]
> file is empty

@MaskDuck Added the details. Please have a look

**Comment by CuteDog5695** [comment]
> ## 🔍 ReviewMate Analysis
> 
> File: [domains/devdreamer.json](https://github.com/is-a-dev/register/blob/f9d4754f536e955b7f0aec6c3f81575c988cf3b7/domains%2Fdevdreamer.json) Content URL: http://swasthik-s.github.io
> ### 📸 Screenshot

Judging by this screenshot, please add more stuff to your website

**Comment by orxngc** [comment]
Closing as stale

**Pull request closed without merging**
