### PR TITLE
Create sctech.json

### PR DESCRIPTION
**Pull request by sctech-tr**
## Here's why I have NS records:
- I have a bunch of (really a bunch of) subdomains, so I can't keep track of JSON files.
- It's easier of me to manage those subdomains from Cloudflare.
- Freedom. Those NS records are there for people to **use** and there's nothing that can stop me from using them.
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview
https://sctech.netlify.app

### CODE REVIEW

**Comment by cupglassDEV** [comment]
god, i need to forward my message again 😭

**Comment by cupglassDEV** [comment]
Forwarded from #16965 with my [own comment](https://github.com/is-a-dev/register/pull/16965#issuecomment-2453354270)
(Why is it forwarded? Because the OG Pull Request do exactly like this, with the same exact reason)

If you want to know what, and whos going to get the NS permission:
1. Services that forcefully needed you to use NS for custom domains, like Aternos and playit.gg. Some, like cloudflare transform and cloudflare tunnel needed you to use a special NS with your is-a.dev subdomain (because is-a.dev already listed on the Public Suffix List, so it treats *is-a.dev*, *co.kr*, *net.id* like the root of it)
OR
2. Some unsupported is-a.dev records that you desperately need it for your homeserver, like this https://github.com/is-a-dev/register/pull/16758

We don't accept responses like "oh, i want NS because it's easy to administer, than having to make a PR on Github", NO

We already made the https://registration.is-a.dev so the process can be a little bit easier, and it fails. Because some of y'all are sending invalid request to register the domain. Now you need to register using the manual one

**Comment by cupglassDEV** [comment]
It doesn't matter if you are doing it for freedom, too many subdomains, or such

**Comment by sctech-tr** [comment]
but “too many subdomains” is a valid reason for using ns records in the docs

**Comment by sctech-tr** [comment]
and why do you don’t accept ns records? they are just like any other record type, there is NO reason to prevent users from using them

**Comment by CuteDog5695** [comment]
> but “too many subdomains” is a valid reason for using ns records in the docs, as in

No it ain't, like we have on the FAQ (?), over 3000 domains have to edit the file via github PRs, why can't you?

> and why do you don’t accept ns records? they are just like any other record type, there is NO reason to prevent users from using them

Can easily be abused since you can make records without us knowing (NS records are basically full control over the subdomain), that is why we restrict it to those who have a valid reason for them

**Review by iostpa — CHANGES_REQUESTED** [review]
Please also state the reason why you want NS records

**Comment by CuteDog5695** [comment]
Oh, just saw the reason. No, you did not provide a valid reason.

**Comment by cupglassDEV** [comment]
> and why do you don’t accept ns records? they are just like any other record type, there is NO reason to prevent users from using them
@sctech-tr 
SEE, I TOLD YAA 😂

Now the maintainer comes in, i already **warned** you from the start. But you still keep insisting

**Comment by cupglassDEV** [comment]
As always, read the fricking docs. If you tell me about "Oh i want NS bcs it exist like other records", that means it equals "Oh i want PTR because it exist like other records"

Diffrent usage, same danger

https://is-a.dev/docs/domain-structure

**Comment by cupglassDEV** [comment]
If you want to use your free will, buy a domain. We really have limited support of records

**Comment by wdhdev** [comment]
Sigh

**Pull request closed without merging**
