### PR TITLE
BETA: Register bark1n.is-a.dev

### PR DESCRIPTION
**Pull request by Helixoo**
Added `bark1n.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Review by triach-rold — COMMENTED** [review]
Website is reachable, but empty.

**Comment by Helixoo** [comment]
I use railway, maybe that's why but I have a working website.
I guess it will be fixed once DNS is installed.

**Comment by JohnDigiDev** [comment]
> I use railway, maybe that's why but I have a working website. I guess it will be fixed once DNS is installed.

Yes that might be true

**Comment by Helixoo** [comment]
Websites public link is : https://portfolio-production-e130.up.railway.app/

**Comment by triach-rold** [comment]
Change it in the json and I guess that should be fine ? Also, that is an amazing website for a 14yo.

**Comment by Helixoo** [comment]
The entire site does not belong to me, I took it from an open source project and made some adjustments.

**Review by iostpa — APPROVED** [review]

**Comment by CuteDog5695** [comment]
> Change it in the json and I guess that should be fine ? Also, that is an amazing website for a 14yo.

he cant change the json file to the visible web link, Railway gives you a CNAME record which can't be viewed but is necessary to connect your domain to the website

**Pull request merged**
