### PR TITLE
Add psj.is-a.dev

### PR DESCRIPTION
**Pull request by philphirn**
Adds psj.is-a.dev

See if you really don't support `TXT` records please put the following `CNAME` record :

Host/Label : `emkt3s7nipkc.psj.is-a.dev.`
Destination/Target : `gv-2yeydifrrtrhvs.dv.googlehosted.com`

The reason is that I want Google to verify psj.is-a.dev
If you have any questions/queries please comment here or email me on the email address given in json file.

### CODE REVIEW

**Comment by hackermondev** [comment]
Sorry, we don't support TXT records and we don't support subdomain in subdomain records either (`emkt3s7nipkc.psj.is-a.dev`).

If you want to do Google verification, IIRC Google allows you to put a ``meta`` tag on your website to verify your domain.

**Review by hackermondev — DISMISSED** [review]
Please delete the ``domains/emkt3s7nipkc.psj.json`` file as we don't support that and remove the ``TXT`` record from the ``domains/psj.json`` file.

**Comment by philphirn** [comment]
@hackermondev done.
And regarding the other json file you wanted to delete, it doesn't show in the domains folder.

**Comment by hackermondev** [comment]
i mean delete the other file you created.

https://github.com/is-a-dev/register/blob/93267beffc4e4af27ec4506b8f40c756bc633989/emkt3s7nipkc.psj.json

**Comment by philphirn** [comment]
@hackermondev 
Done ✅

**Review by TheBotlyNoob — APPROVED** [review]

**Review by hackermondev — APPROVED** [review]

**Comment by hackermondev** [comment]
The changes have been published!! It should reflect in less than 24 hours.

## Here's what you need to do next
If your domain points to a server you own, add `domain-name.is-a.dev` to your server config. For https, you will have to configure ssl certificate to allow the new subdomain.

### For github pages users,
* Go to your github page repo (`user/user.github.io`)
* Open up the **settings** tab
* Scroll down to the **Github pages** section
* In the **Custom domain** text input, enter the domain you registered (`domain-name.is-a.dev`)
* Check the **Enforce HTTPS** checkbox below the input
* Give it some time to reflect and you should be good to go

## Need help with your domain?
If you are having trouble setting up your domain, [create an issue](https://github.com/is-a-dev/register/issues/new/choose). I will try my best to get back to you asap!

## Made a mistake in the record?
Don't worry, you can create a new pull request with the corrections

## Love/Hate the service?
**Love it?** Leave it a **star**! Also consider donating so that I can keep this service running forever!

**Hate it?** Please leave your feedback by [creating an issue](https://github.com/is-a-dev/register/issues/new/choose). I would really like to keep improving this service for other users.

## Wanna support this project?

Help me in my mission to keep this service alive forever by donating!

<a href="https://www.buymeacoffee.com/phenax" target="_blank">Buy Me A Coffee</a> <a href="https://liberapay.com/phenax" target="_blank">Liberapay recurring donation button</a>

**Pull request merged**
