### PR TITLE
Update badboy.json

### PR DESCRIPTION
**Pull request by s3mant**
i had to changed the cname just a little

from this: https://api-badboy.up.railway.app/
to this: https://badboy.up.railway.app/

### CODE REVIEW

**Review by MaskDuck — APPROVED** [review]
hasnt look into the website yet

**Comment by Bad-Boy-Codes** [comment]
> hasnt look into the website yet

checkout https://badboy.is-a.dev

**Comment by MaskDuck** [comment]
hm, the old thing looks fine, i wonder why should you change since the new one lead to a not found

**Comment by Bad-Boy-Codes** [comment]
> 

welp I had to change cuz it's a whole website and profilo not just api

**Comment by MaskDuck** [comment]
ah this one works! also beautiful website too! 
gave an approval, another maintainers will come soon and merge your prs!

**Comment by Bad-Boy-Codes** [comment]
> ah this one works! also beautiful website too! gave an approval, another maintainers will come soon and merge your prs!

thank you :)

**Review by mtgsquad — APPROVED** [review]

**Pull request merged**
