### PR TITLE
add me.is-a.dev

### PR DESCRIPTION
**Pull request by ihsangan**

### CODE REVIEW

**Review by TheBotlyNoob — CHANGES_REQUESTED** [review]
We don't support security challenges as nested subdomains at the moment

**Review by TheBotlyNoob — DISMISSED** [review]
interesting story?

**Comment by TheBotlyNoob** [comment]
I'm not entirely sure if we should allow this subdomain. I'll ask some of the other maintainers for their opinion. Sorry for the wait.

cc @is-a-dev/maintainers

**Comment by ihsangan** [comment]
Ok, fine.

**Comment by MaskDuck** [comment]
@ihsangan why do you want this domain name?

**Comment by ihsangan** [comment]
@MaskDuck it looks simple and i realize no one has used it yet...

**Comment by mtgsquad** [comment]
I'm sorry but we have to wait on everyone's response.

**Comment by ihsangan** [comment]
Now what?

**Pull request closed without merging**
