### PR TITLE
Automatically run labeling workflow when PR is created

### LINKED ISSUE #672: [CI] Fix github actions automation for auto-comment and auto-label
When the project started it was using `pull_request_target` event in github actions to trigger some automation. But due to vulnerabilities in the workflow, we are currently using `pull_request` event, because of which the automation stopped working.

The expected flow is

```
PR created ---labeller---> PR labelled (domain) ---merge---> PR comment with instructions for the user
```

### PR DESCRIPTION
**Pull request by jasonappah**
Closes #672. Tested successfully on my fork (see jasonappah#1)

### CODE REVIEW

**Review by phenax — CHANGES_REQUESTED** [review]
I don't think this would work since labelling PR needs access to `GITHUB_TOKEN` and `pull_request` doesn't allow access to it secrets from forked repositories. It worked with your fork since you were creating the PR from the same repo

**Comment by jasonappah** [comment]
Ahh totally missed that. I will look into this more this week.

**Comment by hackermondev** [comment]
5 weeks later... @jasonappah

**Comment by iop3** [comment]
5 weeks and 4 days later...

**Comment by kckarnige** [comment]
2 months and 3 days later... @jasonappah

**Comment by TheBotlyNoob** [comment]
\* sigh \* a hell of a long time later... @jasonappah

**Comment by thispsj** [comment]
This can be done by using `pull_request_target` instead of `pull_request` event in workflow files.

**Comment by TheBotlyNoob** [comment]
@thispsj see: #672

**Comment by thispsj** [comment]
@TheBotlyNoob ik that but labelling jobs can be run safely.
Unless you run any code from the fork of the PR itself, it's safe to run jobs on `pull_request_target`.
`pull_request_target` was introduced for such automation tasks.

You can read [this](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) for more info.

**Comment by TheBotlyNoob** [comment]
103 days later, @jasonappah 
image

**Comment by thispsj** [comment]
Hey 
@TheBotlyNoob 
If you really don't want `pull_request_target` then there's another way.
Use GitHub Webhooks, A relay server and the `repository_dispatch` event.

I can elaborate on this if you are interested in this idea.

**Comment by TheBotlyNoob** [comment]
@thispsj I don't really know GitHub actions, if you want to talk about it, talk to @phenax

**Comment by phenax** [comment]
@thispsj, I think we'll park this for now. This isn't essential and I am planning on doing some migrations in the future which would be in line with the solution you're suggesting.

@TheBotlyNoob, I think we can stop posting the post-merge message. What do you think?

**Comment by thispsj** [comment]
> @thispsj, I think we'll park this for now. This isn't essential and I am planning on doing some migrations in the future which would be in line with the solution you're suggesting.
> 
> @TheBotlyNoob, I think we can stop posting the post-merge message. What do you think?

Ok @phenax as you wish :+1:

**Comment by phenax** [comment]
Closing this PR. Will keep the issue open with a low priority label.

**Pull request closed without merging**
