### PR TITLE
Updated rehan-playz.json

### PR DESCRIPTION
**Pull request by RehanPlayz**
Updated rehan-playz.json to redirect to my webhost instead of GitHub Pages

### CODE REVIEW

**Review by LellisV2 — APPROVED** [review]
:)

**Comment by RehanPlayz** [comment]
;)

**Review by TheBotlyNoob — APPROVED** [review]

**Comment by RehanPlayz** [comment]
My bad, didn't mean to do that @TheBotlyNoob

**Comment by TheBotlyNoob** [comment]
I've aalready approved, but I can do it again 🤷

**Review by TheBotlyNoob — APPROVED** [review]

**Comment by RehanPlayz** [comment]
> I've already approved, but I can do it again 🤷
My Bad, didn't mean to ask for again approval again lol

**Comment by RehanPlayz** [comment]
Just need one more approving review!

**Review by hackermondev — APPROVED** [review]

**Pull request merged**
