### PR TITLE
Update almaz.json

### PR DESCRIPTION
**Pull request by AlmaziikDev**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [+] The file is in the `domains` folder and is in the JSON format.
- [+] The file's name is all lowercased and alphanumeric. 
- [+] There is sufficient information at the `owner` field.

### CODE REVIEW

**Comment by cupglassDEV** [comment]
No need the dots behind em

It is always covered by this dnsconfig https://github.com/is-a-dev/register/blob/9fa09f30406c9f525704a4bd3cb023ae677a0476/dnsconfig.js#L63

**Comment by cupglassDEV** [comment]
If improvMX cant resolve it, we'll wait. Because is-a.dev has a temporary downtime yesterday, so the dns propagation may be slow

**Comment by AlmaziikDev** [comment]
> If improvMX cant resolve it, we'll wait. Because is-a.dev has a temporary downtime yesterday, so the dns propagation may be slow

ah, okay then, thanks

**Comment by cupglassDEV** [comment]
> > If improvMX cant resolve it, we'll wait. Because is-a.dev has a temporary downtime yesterday, so the dns propagation may be slow
> 
> ah, okay then, thanks

Its ok, i have trouble with that also. Even though my domain has a special Nameserver permission, but when i add a new record, it keeps failing like nothing

**Comment by cupglassDEV** [comment]
oh no
image

**Review by iostpa — CHANGES_REQUESTED** [review]

**Review by iostpa — APPROVED** [review]
Seems good to me now

**Pull request merged**
