### PR TITLE
BETA: Register sama.is-a.dev

### PR DESCRIPTION
**Pull request by Sama-004**
Added `sama.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Comment by YouFoundAlpha** [comment]
Hello, @Sama-004 
Your CNAME record is invalid

**Comment by Sama-004** [comment]
> Hello, @Sama-004 Your CNAME record is invalid What are you trying to point your subdomain at?

gtihub pages

**Comment by Sama-004** [comment]
> > > Hello, @Sama-004 Your CNAME record is invalid What are you trying to point your subdomain at?
> > 
> > 
> > gtihub pages
> 
> Then read the documentation https://is-a.dev/docs/github_pages for information on how to set your subdomain up with it if you only want to redirect sama.is-a.dev to your github pages site then change
> 
> ```
> "CNAME": ""
> ```
> 
> to
> 
> ```
> "URL": "https://<your github username>.github.io"
> ```

Thanks for the help. I have done the needful

**Review by YouFoundAlpha — CHANGES_REQUESTED** [review]
Remove CNAME

**Comment by YouFoundAlpha** [comment]
Now you only need to wait for a maintainer to merge this pull request
It can take some time

**Comment by Sama-004** [comment]
> Remove CNAME

Done

**Review by DEV-DIBSTER — APPROVED** [review]

**Pull request merged**
