### PR TITLE
Renamed rehan-playz.json to rehanplayz.json

### PR DESCRIPTION
**Pull request by RehanPlayz**
and also added a TXT record for Zoho Mail Domain Verification (I Hope it works this time lol)

### CODE REVIEW

**Comment by RehanPlayz** [comment]
It works yay!

**Comment by TheBotlyNoob** [comment]
zohomail will not work here because of the way we parse MX records, I figured this out the hard way.

**Comment by TheBotlyNoob** [comment]
also, you cannot have more than one `TXT` record

**Comment by RehanPlayz** [comment]
> zohomail will not work here because of the way we parse MX records, I figured this out the hard way.

What alternative mail host do you suggest do you suggest?

**Comment by RehanPlayz** [comment]
> also, you cannot have more than 

> also, you cannot have more than one `TXT` record

I fixed it now and do you know a mail host that's better than ImprovMX because it can only forward emails not actually send emails from the domain

**Comment by RehanPlayz** [comment]
@TheBotlyNoob

**Comment by mtgsquad** [comment]
> > zohomail will not work here because of the way we parse MX records, I figured this out the hard way.
> 
> What alternative mail host do you suggest do you suggest?

I recommend using [ImprovMX](https://improvmx.com)

**Comment by RehanPlayz** [comment]
> > > zohomail will not work here because of the way we parse MX records, I figured this out the hard way.
> > 
> > 
> > What alternative mail host do you suggest do you suggest?
> 
> I recommend using [ImprovMX](https://improvmx.com)

Oh ok, I added added the records for ImprovMX the only issue with it is that I can't send emails from it like Zoho Mail

**Comment by RehanPlayz** [comment]
Could the maintainers please approve the PR

**Comment by RehanPlayz** [comment]
> Could any two of the maintainers please approve the PR

@TheBotlyNoob and @mtgsquad

**Review by TheBotlyNoob — DISMISSED** [review]

**Comment by TheBotlyNoob** [comment]
> > also, you cannot have more than one `TXT` record
> 
> I fixed it now and do you know a mail host that's better than ImprovMX because it can only forward emails not actually send emails from the domain

I have not really looked into it, all I know of is zoho mail, which doesn't work with `is-a.dev`.

**Comment by RehanPlayz** [comment]
Thx @TheBotlyNoob, Just need one more review

**Comment by RehanPlayz** [comment]
> > > also, you cannot have more than one `TXT` record
> > 
> > 
> > I fixed it now and do you know a mail host that's better than ImprovMX because it can only forward emails not actually send emails from the domain
> 
> I have not really looked into it, all I know of is zoho mail, which doesn't work with `is-a.dev`.

Oh ok ig, I will try finding an alternative

**Comment by RehanPlayz** [comment]
@TheBotlyNoob Small Question, I edited the rehan-playz.json to rehanplayz.json so rehan-playz.is-a.dev should stop working and rehanplayz.is-a.dev should work right? (When this PR gets merged)

**Comment by TheBotlyNoob** [comment]
yes, you are correct.

**Comment by RehanPlayz** [comment]
> yes, you are correct.

Oh ok thx, Just waiting for one more review

**Comment by RehanPlayz** [comment]
Would be cool if a maintainer could approve this PR today lol

**Comment by TheBotlyNoob** [comment]
yea

**Comment by RehanPlayz** [comment]
@TheBotlyNoob I got a new WebHost with emails it should work, right?

**Comment by RehanPlayz** [comment]
@mtgsquad Can you please approve this

**Comment by RehanPlayz** [comment]
Can a maintainer please approve the PR

**Review by TheBotlyNoob — APPROVED** [review]

**Comment by TheBotlyNoob** [comment]
> @TheBotlyNoob I got a new WebHost with emails it should work, right?

I think...

**Comment by RehanPlayz** [comment]
> > @TheBotlyNoob I got a new WebHost with emails it should work, right?
> 
> I think...

Oh ok and thx for the approval just need @mtgsquad, @Codeize or @hackermondev's approval now

**Comment by TheBotlyNoob** [comment]
yep

**Comment by RehanPlayz** [comment]
Can a Maintainer please approve this PR, It's been like 4 days :(

**Review by hackermondev — APPROVED** [review]

**Comment by RehanPlayz** [comment]
Thx

**Comment by RehanPlayz** [comment]
@hackermondev Why did the helper workflow action fail

**Pull request merged**
