### PR TITLE
Update nine.json and add email service

### PR DESCRIPTION
**Pull request by NineLEL**

### CODE REVIEW

**Review by TheBotlyNoob — DISMISSED** [review]
👀 
image

**Comment by NineLEL** [comment]
I'm using port 25592 so what should I put?

**Comment by NineLEL** [comment]
Hello, I changed from port 25592 to 80. Could you try it again please?

**Review by hackermondev — CHANGES_REQUESTED** [review]
TXT records are not supported. I think it should be fine without the TXT records anyways.

**Review by MaskDuck — APPROVED** [review]
h

**Comment by NineLEL** [comment]
Is there any left to fix? Or is it fixed?

**Review by hackermondev — APPROVED** [review]

**Pull request merged**
