### PR TITLE
Create cdn-rehanplayz.json

### PR DESCRIPTION
**Pull request by RehanPlayz**

### CODE REVIEW

**Comment by RehanPlayz** [comment]
Why isn't it working?

**Review by TheBotlyNoob — DISMISSED** [review]

**Comment by RehanPlayz** [comment]
> We have to merge this pr first, then it will work.

No, Last time I checked the validation thing failed that's why I asked also why is CNAME records with TXT not possible and my file host wants to add these records (The TXT record need a specific name, How would I do that) https://rehanplayz-is.super-cool.xyz/ktudnaiw49a

**Comment by RehanPlayz** [comment]
> > We have to merge this pr first, then it will work.
> 
> No, Last time I checked the validation thing failed that's why I asked also why is CNAME records with TXT not possible and my file host wants to add these records (The TXT record need a specific name, How would I do that) https://rehanplayz-is.super-cool.xyz/ktudnaiw49a

@TheBotlyNoob How can I add a name to the TXT record

**Comment by TheBotlyNoob** [comment]
Not sure, ask @phenax

**Comment by TheBotlyNoob** [comment]
> > We have to merge this pr first, then it will work.
> 
> 
> 
> No, Last time I checked the validation thing failed that's why I asked also why is CNAME records with TXT not possible and my file host wants to add these records (The TXT record need a specific name, How would I do that) https://rehanplayz-is.super-cool.xyz/ktudnaiw49a

Last I checked, you could use a TXT record with CNAME.

**Comment by RehanPlayz** [comment]
> > > We have to merge this pr first, then it will work.
> > 
> > 
> > No, Last time I checked the validation thing failed that's why I asked also why is CNAME records with TXT not possible and my file host wants to add these records (The TXT record need a specific name, How would I do that) https://rehanplayz-is.super-cool.xyz/ktudnaiw49a
> 
> Last I checked, you could use a TXT record with CNAME.

Oh ok let me try then

**Comment by RehanPlayz** [comment]
> > > We have to merge this pr first, then it will work.
> > 
> > 
> > No, Last time I checked the validation thing failed that's why I asked also why is CNAME records with TXT not possible and my file host wants to add these records (The TXT record need a specific name, How would I do that) https://rehanplayz-is.super-cool.xyz/ktudnaiw49a
> 
> Last I checked, you could use a TXT record with CNAME.

@TheBotlyNoob When I do it with CNAME the validation thing fails

**Comment by RehanPlayz** [comment]
> Not sure, ask @phenax

ok

**Review by TheBotlyNoob — APPROVED** [review]

**Review by hackermondev — DISMISSED** [review]

**Comment by hackermondev** [comment]
What are you using the TXT record for @RehanPlayz

**Comment by uhIgnacio** [comment]
> What are you using the TXT record for @RehanPlayz

[tixte.com](https://tixte.com) file host with custom domain, it needs TXT for check owner

**Comment by RehanPlayz** [comment]
@hackermondev can you approve

**Comment by phenax** [comment]
@RehanPlayz, you cannot have a TXT record over a CNAME record

Ref: https://datatracker.ietf.org/doc/html/rfc1034
> If a CNAME RR is present at a node, no other data should be
present; this ensures that the data for a canonical name and its aliases
cannot be different

**Review by phenax — APPROVED** [review]

**Comment by RehanPlayz** [comment]
> @RehanPlayz, you cannot have a TXT record over a CNAME record
> 
> Ref: https://datatracker.ietf.org/doc/html/rfc1034
> 
> > If a CNAME RR is present at a node, no other data should be
> > present; this ensures that the data for a canonical name and its aliases
> > cannot be different

Oh ok I have no idea what this means "this ensures that the data for a canonical name and its aliases
cannot be different"

**Comment by RehanPlayz** [comment]
> @phenax  How can I add a name to the TXT record

**Comment by phenax** [comment]
@RehanPlayz, I missed that message. This unfortunately is not possible currently as this requires reserving a top level record that isn't unique to your user.

**Comment by RehanPlayz** [comment]
> @RehanPlayz, I missed that message. This unfortunately is not possible currently as it requires reserving a top level record that isn't unique to your user.

Oh ok

**Pull request merged**
