### PR TITLE
Create bxqrn.json

### PR DESCRIPTION
**Pull request by Bxqrn**
# 🌟 Domain Registration Request: `bxqrn.is-a.dev`

## 🚀 Requirements Checklist
I've meticulously ensured my submission meets **all** the criteria listed below. Please review at your convenience:

- [x] **File Format**: The domain file is located in the `domains` folder and follows strict JSON formatting standards.
- [x] **File Naming**: The file is lowercase, alphanumeric, and appropriately named `bxqrn.json`.
- [x] **Website Completion**: My site is fully built, visually polished, and ready for public access.
- [x] **Website Accessibility**: The site is live and reachable at [bxqrn.github.io](https://bxqrn.github.io).
- [x] **CNAME Validity**: The `CNAME` record adheres to guidelines and excludes invalid elements like `https://` or trailing slashes.
- [x] **Owner Information**: I’ve included sufficient owner details, including a reliable email for further communication.

---

## 🌐 Website Link/Preview
Take a look at the live website:  
🔗 [https://bxqrn.github.io](https://bxqrn.github.io)

Here’s a quick visual snapshot:  

Website Preview  
(*You can replace this link with an actual screenshot if desired!*)

---

## 📜 Additional Notes
- I’ve crafted this website with performance, usability, and sleek design in mind, making it a perfect fit for the `is-a.dev` community.  
- If there’s anything else I can provide or improve, don’t hesitate to reach out—I’m more than happy to collaborate further!  

---

### 🎉 Thanks for considering my request!  
Looking forward to joining the awesome ecosystem of `is-a.dev`. 😊

### CODE REVIEW

**Review by DEV-DIBSTER — APPROVED** [review]

**Review by DEV-DIBSTER — APPROVED** [review]

**Comment by CuteDog5695** [comment]
The hell? This is the most professional pull request I've seen for the first time. I appreciate the effort!

**Comment by Bxqrn** [comment]
Thanks LOL!

**Comment by Bxqrn** [comment]
umm i dont see my site it says: bxqrn.is-a.dev normally uses encryption to protect your information. When Chrome tried to connect to bxqrn.is-a.dev this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be bxqrn.is-a.dev, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Chrome stopped the connection before any data was exchanged.

You cannot visit bxqrn.is-a.dev right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by CuteDog5695** [comment]
Did you add your domain to your website repo?

**Comment by Bxqrn** [comment]
yes

**Pull request merged**
