### PR TITLE
IP Update request, Everything on the website is the same just different IP

### PR DESCRIPTION
**Pull request by Kawrrq**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [✅ ] The file is in the `domains` folder and is in the JSON format.
- [✅ ] The file's name is all lowercased and alphanumeric. 
- [✅ ] You have completed your website. 
- [✅ ] The website is reachable.  
- [ Not using CNAME ] The CNAME record doesn't contain `https://` or `/`.  
- [✅ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://github.com/user-attachments/assets/67505ea1-1da7-4818-8f1c-ef839511c6c1

### CODE REVIEW

**Comment by cupglassDEV** [comment]
Wait. Does we have a rule about unblocker, cheat, or something like that isnt allowed on is-a.dev??

**Comment by Kawrrq** [comment]
Where can i read the rules I did not know

**Comment by cupglassDEV** [comment]
Its available on their discord server, or see the official google docs for the full length of rules
https://discord.com/channels/830872854677422150/954684406780551168/1188286982632263802

Heres the google docs:
https://docs.google.com/document/d/194YzIHQY91WVvvQxRxymepzAnL2vHrCFfDpD1XX_flI/edit?usp=sharing

**Comment by cupglassDEV** [comment]
@Kawrrq ik its confusing for non-discord user, imma try to talk to maintainer to add this to the README too

**Comment by cupglassDEV** [comment]
Its mostly a server rules, but i believe there is a rule about that

**Comment by cupglassDEV** [comment]
@CuteDog5695 Am i right, bro?

**Comment by cupglassDEV** [comment]
https://github.com/is-a-dev/register/pull/16702
@Kawrrq Heres the example pull request

**Review by iostpa — CHANGES_REQUESTED** [review]
Are the games and/or apps pirated?

**Comment by Kawrrq** [comment]
no they are not pirated

**Pull request closed without merging**
