### PR TITLE
Create hcp.is-a.dev subdomain for my aaPanel

### PR DESCRIPTION
**Pull request by huygmdvn**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.

### CODE REVIEW

**Comment by Satindar31** [comment]
Unless you want your domain to be hcp-is-a-dev.is-a.dev, change your file name to `hcp.json`

**Comment by huygmdvn** [comment]
http://[2a06:de00:701:1000:a000::f]:8888/aapanel
https://demo.aapanel.com/fdgi87jbn?_gl=1*vq6t7h*_gcl_aw*R0NMLjE3Mjc2MTk5MDEuQ2p3S0NBanc5ZU8zQmhCTkVpd0FvYzAtamZlZHFyT0FTSW5SaldRTnhKbm00U29pNTZiQVVUb0NWODFxbHlYbGhOcjRtR01VaFJpeWt4b0NXNWtRQXZEX0J3RQ..*_gcl_au*MTM2ODE2ODY1Ny4xNzI0MDMwMzI5*_ga*MTk0NDE0MDcxMS4xNzI0MDMwMzIy*_ga_PKXWQERS47*MTcyODU2NDMwMC4zMi4wLjE3Mjg1NjQzMDAuNjAuMC4w (Full demo cuz yh I can't provide my panel pwd)

Why orangc?Its just aaPanel

**Comment by cupglassDEV** [comment]
> http://[2a06:de00:701:1000:a000::f]:8888/aapanel https://demo.aapanel.com/fdgi87jbn?_gl=1*vq6t7h*_gcl_aw*R0NMLjE3Mjc2MTk5MDEuQ2p3S0NBanc5ZU8zQmhCTkVpd0FvYzAtamZlZHFyT0FTSW5SaldRTnhKbm00U29pNTZiQVVUb0NWODFxbHlYbGhOcjRtR01VaFJpeWt4b0NXNWtRQXZEX0J3RQ..*_gcl_au*MTM2ODE2ODY1Ny4xNzI0MDMwMzI5*_ga*MTk0NDE0MDcxMS4xNzI0MDMwMzIy*_ga_PKXWQERS47*MTcyODU2NDMwMC4zMi4wLjE3Mjg1NjQzMDAuNjAuMC4w (Full demo cuz yh I can't provide my panel pwd)
> 
> Why orangc?Its just aaPanel

image
even i cant open it, so thats why the maintainer asks you abt that

**Review by iostpa — CHANGES_REQUESTED** [review]
I honestly have mixed feelings about this, I'm not really sure if we allow aaPanel on main subdomains. @wdhdev is this allowed?

**Comment by wdhdev** [comment]
Don't think this will be accepted unfortunately.

**Pull request closed without merging**
