### PR TITLE
Register toasted.is-a.dev

### PR DESCRIPTION
**Pull request by ToastedDev**
Added `toasted` via the registration website.

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
We don't support Vercel.

**Comment by ToastifyDev** [comment]
> We don't support Vercel.

Sorry, I only just read the docs.

**Review by wdhdev — CHANGES_REQUESTED** [review]
I can't reach your website

**Comment by ToastifyDev** [comment]
Sorry, had to deal with Astro and Railway.

**Review by wdhdev — CHANGES_REQUESTED** [review]
I still can't reach your website

**Comment by ToastifyDev** [comment]
The website is currently hosted on https://portfolio.toastify.tk.

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
