### PR TITLE
Mohannadk28.json added

### PR DESCRIPTION
**Pull request by starrymohannad**

### CODE REVIEW

**Review by phenax — CHANGES_REQUESTED** [review]
CNAME has to be a host name and not a url. If you want a URL redirection, use URL instead of CNAME. If you want a CNAME record, remove everything but the host name.

**Comment by Mohannadk28** [comment]
Fixed It !!

**Review by phenax — CHANGES_REQUESTED** [review]
You've accidentally included a swap file. Please delete it

**Comment by Mohannadk28** [comment]
now

**Review by phenax — APPROVED** [review]

**Pull request merged**
