### PR TITLE
Create subhoboy.json

### PR DESCRIPTION
**Pull request by SubhoBoy**

### CODE REVIEW

**Comment by omxpro** [comment]
You need a real working website for this.

**Comment by omxpro** [comment]
First develop you're website and then make a pr

**Comment by SubhoBoy** [comment]
Do you mean that my website isn't up or doesn't have any content? If it's the latter, I'll upload my files as soon as I get back home.
If it's the former, I'm sorry, I don't know what you're talking about. I can access it at https://subhoboy.github.io

**Review by MaskDuck — CHANGES_REQUESTED** [review]
complete the website, dont leave a placeholder.

**Pull request closed without merging**
