### PR TITLE
Register exoooo.is-a.dev

### PR DESCRIPTION
**Pull request by Exo-OX1564**
Added `exoooo` via the registration website.

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please use a valid record

**Comment by Exo-OX1564** [comment]
> Please use a valid record

Whoops, yeah. Done it, should be at `exoooo.json`

**Review by wdhdev — APPROVED** [review]

**Comment by Exo-OX1564** [comment]
> @WilliamDavidHarrison Please reconsider.

Why's that?

**Comment by WilliamDavidHarrison** [comment]
@e6 I will remove his subdomain, due to his repositories and activity being suspicious.

Thank you for your report.

**Pull request merged**
