### PR TITLE
Update l7neg.json

### PR DESCRIPTION
**Pull request by L7NEG**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.

### CODE REVIEW

**Review by triach-rold — APPROVED** [review]
Reachable and complete.

**Comment by iSk1P** [comment]
> My headphones were at max volume lmao. Nice site though.

xD thx bro

**Comment by L7NEG** [comment]
> My headphones were at max volume lmao. Nice site though.

Yee it's because of the edited video

**Comment by L7NEG** [comment]
I'm just waiting 1 approval for merging

**Review by iostpa — APPROVED** [review]

**Pull request merged**
