### PR TITLE
boolean44

### PR DESCRIPTION
**Pull request by boolean44-repos**

### CODE REVIEW

**Review by MaskDuck — APPROVED** [review]

**Comment by boolean44-repos** [comment]
can i make different pages within my domain ? ex: boolean.is-a.dev/play

**Comment by MaskDuck** [comment]
yeah. feel free to.

**Comment by boolean44-repos** [comment]
this is so cool i cant believe its free forever

**Comment by MaskDuck** [comment]
dont forget to leave it a star!

**Comment by boolean44-repos** [comment]
are we able to get emails with our domain?

**Comment by boolean44-repos** [comment]
?

**Comment by MaskDuck** [comment]
feel free to use improvmx.

**Comment by boolean44-repos** [comment]
how?

**Comment by boolean44-repos** [comment]
i need a place to put the mx records

**Comment by MaskDuck** [comment]
create a new pr.

**Comment by boolean44-repos** [comment]
and add?

**Comment by MaskDuck** [comment]
yeah. 

note: you need to remove cname. if you dont want to remove cname, feel free to create a new file such as `mail.boolean44.json` and fill the mx part in that file, so you would have an email like `hello@mail.boolean44.is-a.dev`

**Comment by boolean44-repos** [comment]
what do i put in the file exactly?

**Comment by MaskDuck** [comment]
like what you did with this file, the only different is you should replace cname with mx.

**Comment by MaskDuck** [comment]
feel free to see my config: https://github.com/is-a-dev/register/blob/main/domains/too-obvious-that.maskduck.json

**Comment by boolean44-repos** [comment]
how do i pick the thing before the @

**Comment by MaskDuck** [comment]
wdym

**Comment by boolean44-repos** [comment]
like i want riley@mail.boolean44.is-a.dev, is that set within improv mx?

**Comment by MaskDuck** [comment]
yes

**Comment by boolean44-repos** [comment]
i added a pr

**Comment by boolean44-repos** [comment]
did it fail?

**Comment by boolean44-repos** [comment]
?

**Comment by boolean44-repos** [comment]
can people with an is-a.dev subdomain also get a runs-on.tech?

**Comment by MaskDuck** [comment]
that service has no affilate with us, it is only similar with us :)) so we and runs-on.tech are entirely different, so you can get both...

**Comment by boolean44-repos** [comment]
can i switch to hanami.run ?

**Pull request merged**
