### PR TITLE
Added and updated himanshu.json file

### PR DESCRIPTION
**Pull request by HIMU-2001**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

himu-2001.github.io/portfolio/index.html

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
You haven’t specified any records.

**Comment by EtherealTheDev** [comment]
And another note you can't include /<file> ; / ; http:// ; https

It needs to be a raw domain for example www.google.com instead of www.google.com/index

**Comment by EtherealTheDev** [comment]
Change, himu-2001.github.io/portfolio/index.html to himu-2001.github.io

**Comment by HIMU-2001** [comment]
Could you now check the file.

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
