### PR TITLE
Request For NS RECORD UPDATE

### PR DESCRIPTION
**Pull request by ArnavBarway**
### Pull Request to Update NS Record for `devarnav.is-a.dev`

**Reason for NS Record Update:**

I'm requesting an NS record update for my domain to streamline my project management and reduce delays:

1. As a GitHub Pages user, I frequently update and experiment with web projects for personal learning and school assignments. Having control over the NS record would allow me to manage my DNS settings directly through Cloudflare, saving time by eliminating the need to make repeated pull requests.

2. With Cloudflare's dashboard, I can adjust DNS configurations quickly to support new projects, subdomains, or security settings as needed, without waiting for approval on each change. This flexibility is important for my dynamic projects and time-sensitive school tasks.

3. I commit to using this domain responsibly and will follow all guidelines, ensuring it remains free of any illegal, inappropriate, or NSFW content. I will also maintain strict control of access to the domain, keeping it secure and private.

Thank you for considering my request. This pull request was crafted with respect to previous examples like @actuallyundefined’s.

### CODE REVIEW

**Comment by wdhdev** [comment]
Sorry, not a valid reason.

**Comment by ArnavBarway** [comment]
bro but why? @wdhdev

**Comment by ArnavBarway** [comment]
I just want to host my many projects in github pages but github pages do not gives me a .is-a.dev sweet looking domain and pull request takes too long to get approved

**Comment by ArnavBarway** [comment]
if the nameservers get approved I can create records fastly

**Comment by wdhdev** [comment]
> I just want to host my many projects in github pages but github pages do not gives me a .is-a.dev sweet looking domain and pull request takes too long to get approved

> if the nameservers get approved I can create records fastly

Over 3,000 people have to open PRs, you can too.

**Pull request closed without merging**
