### PR TITLE
Added abhirockz via is-a-dev-cli

### PR DESCRIPTION
**Pull request by yopremium21**
Added abhirockz via the CLI

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
We don't support TXT verification

**Review by yopremium21 — COMMENTED** [review]
updated cname

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please explain the use of this domain

**Comment by yopremium21** [comment]
> Please explain the use of this domain

Trying to activate google workspace trial account. Adding domain name is mandatory to start trial. I just want to explore working of Google Workspace.

**Comment by WilliamDavidHarrison** [comment]
> > Please explain the use of this domain
> 
> Trying to activate google workspace trial account. Adding domain name is mandatory to start trial. I just want to explore working of Google Workspace.

Unfortunately we don't support domain verification.

**Pull request closed without merging**
