### PR TITLE
Added aj7 via is-a-dev-cli

### PR DESCRIPTION
**Pull request by aj-seven**
Added aj7 via the CLI

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please send a preview of your website

**Comment by Aj-Seven** [comment]
> 

http://me.ajseven.eu.org

**Comment by Aj-Seven** [comment]
This is my website link looks like:
   http://me.ajseven.eu.org it have two A Records.
This is for just preview and in making of the website.
Please review it...
Thanks

**Comment by WilliamDavidHarrison** [comment]
Please actually create a website.

**Comment by Aj-Seven** [comment]
> 

Ok

**Comment by Aj-Seven** [comment]
Mean that is website

**Comment by Aj-Seven** [comment]
Plzz delete my pull requests in your repository..... Plzzz

ajseven

**Pull request closed without merging**
