### PR TITLE
Create testing-domain-9pfs.json

### PR DESCRIPTION
**Pull request by hello-smile6**
I'm trying to figure out what having a domain with this will look like, and testing whether these domains work with [Replit](https://replit.com/).

- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: https://testing-domain-9pfsis-adev.9pfs.repl.co/
- [x] The website is reachable.
- [x] The CNAME record doesn't contain any slash.
- [x] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.

The Replit account for this is [@9pfs](https://replit.com/@9pfs), and it can be used to contact me.

### CODE REVIEW

**Review by MaskDuck — CHANGES_REQUESTED** [review]
seems like i can't reach it.

**Comment by hello-smile6** [comment]
> seems like i can't reach it.

The server sometimes goes down, if you give it about 1 minute to start it should work.

**Comment by WilliamDavidHarrison** [comment]
@hello-smile6 Our service works with Replit. You could maybe find an example in the domains folder.

**Comment by hello-smile6** [comment]
> @hello-smile6 Our service works with Replit. You could maybe find an example in the domains folder.

Okay

**Comment by hello-smile6** [comment]
> This pull request has been marked as stale due to inactivity and will be closed. Comment anything on this PR to prevent it

Why is this getting closed?

**Pull request closed without merging**
