### PR TITLE
Create api.karyakarsa.willo

### PR DESCRIPTION
**Pull request by WilloIzCitron**
for api purpose

### CODE REVIEW

**Review by MaskDuck — CHANGES_REQUESTED** [review]
you fucked up the file name and the description. good job.

file should have json extension and if you have no description just omit it

**Comment by WilloIzCitron** [comment]
i forgor it

**Review by MaskDuck — CHANGES_REQUESTED** [review]
you still fucked up the file name. good job again.

as mentioned above, file name should have json extension

**Comment by WilloIzCitron** [comment]
nice try

**Review by MaskDuck — APPROVED** [review]
okay, optionally starring the repo 

also optionally join the support server (link in readme) to receive service announcement.

**Pull request merged**
