### PR TITLE
Github Pages Domain Verification

### PR DESCRIPTION
**Pull request by TheWongLife**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://thewonglife.is-a.dev/

### CODE REVIEW

**Comment by TheWongLife** [comment]
Ignore the 1st commit (Forgot to add .json extension before), fixed it with the 2nd commit by adding the .json extension.

**Review by iostpa — APPROVED** [review]

**Comment by TheWongLife** [comment]
[like]  Wong, Nicholas reacted to your message:
________________________________

**Comment by TheWongLife** [comment]
[like]  Wong, Nicholas reacted to your message:
________________________________

**Comment by TheWongLife** [comment]
[like]  Wong, Nicholas reacted to your message:
________________________________

**Pull request merged**
