### PR TITLE
Create bilal.json

### PR DESCRIPTION
**Pull request by Bilalbsd**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.

### CODE REVIEW

**Review by wdhdev — COMMENTED** [review]
I can't reach your website

**Review by wdhdev — CHANGES_REQUESTED** [review]
Clicked comment instead of request changes.

**Comment by Bilalbsd** [comment]
The website is now accessible.

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please add more content to your website

**Comment by Bilalbsd** [comment]
Done. It's not great yet but I'll improve it.

**Review by wdhdev — CHANGES_REQUESTED** [review]
Just a small thing as I cannot allow templates, please just update the about me/skills.

**Comment by Bilalbsd** [comment]
It should be good now.

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
