### PR TITLE
Create client.nziie.json

### PR DESCRIPTION
**Pull request by Nzii3**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://client.vnziie-pinghost-v2.pinglik.eu

### CODE REVIEW

**Comment by Nzii3** [comment]
I’m creating this again since MaskDuck said my last PR WAS NOT VIOLATING ANY RULES.

**Comment by Nzii3** [comment]
https://github.com/is-a-dev/register/pull/5218#issuecomment-1509454072

**Comment by Nzii3** [comment]
I’m not using a more secure and safe selling site, it’s paid.

**Review by wdhdev — APPROVED** [review]

**Comment by WilliamDavidHarrison** [comment]
> I’m creating this again since MaskDuck said my last PR WAS NOT VIOLATING ANY RULES.

Sorry about that, I wasn't aware we allowed websites like these.

**Comment by Nzii3** [comment]
> > I’m creating this again since MaskDuck said my last PR WAS NOT VIOLATING ANY RULES.
> 
> Sorry about that, I wasn't aware we allowed websites like these.

Thank you.

**Comment by Nzii3** [comment]
@mtgsquad It was already merged, referring to your comment on my old PR.

**Comment by mtgsquad** [comment]
@Nzii3 I am still puzzled about it. As there is a large possibility of scams. It's okay for now.

**Comment by Nzii3** [comment]
> @Nzii3 I am still puzzled about it. As there is a large possibility of scams. It's okay for now.

I’m not doing any scam things.

**Pull request merged**
