### PR TITLE
Register Subdomain: Dhyan99

### PR DESCRIPTION
**Pull request by D99-1**
Added the domain: Dhyan99

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
You need to have content on your website.

**Review by TheBotlyNoob — DISMISSED** [review]
Your website is empty.

**Comment by D99-1** [comment]
@TheBotlyNoob yes it is empty but I am going to push the changes to the repo in a few days time

**Comment by WilliamDavidHarrison** [comment]
> @TheBotlyNoob yes it is empty but I am going to push the changes to the repo in a few days time

We have to wait until then, since we require you to have content on your site.

**Comment by D99-1** [comment]
Alright I will add content and ask for a re-review I a few days time

> > @TheBotlyNoob yes it is empty but I am going to push the changes to the repo in a few days time
> 
> We have to wait until then, since we require you to have content on your site.

**Comment by D99-1** [comment]
fixed

**Comment by D99-1** [comment]
Added my *mostly* complete site

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please rename your file to: `dhyan99.json` (lowercase)

**Comment by D99-1** [comment]
Should be good now.....

**Review by wdhdev — APPROVED** [review]

**Comment by D99-1** [comment]
So should the site be active?

**Comment by WilliamDavidHarrison** [comment]
> So should the site be active as you have approved the changes?

Not yet. You'll need to wait for a maintainer to merge this PR.

**Comment by D99-1** [comment]
> > So should the site be active as you have approved the changes?
> 
> Not yet. You'll need to wait for a maintainer to merge this PR.

Alright thanks I'll just wait for @TheBotlyNoob to check over it once more and *hopefully* merge :)

**Comment by D99-1** [comment]
hello?? @WilliamDavidHarrison @TheBotlyNoob

**Comment by WilliamDavidHarrison** [comment]
> hello?? @TheBotlyNoob 

Please don't ping the maintainers

**Comment by D99-1** [comment]
> > hello?? @TheBotlyNoob
> 
> Please don't ping the maintainers

There was legit no chance of my pr being noticed, it's now at the very back of the prs

**Comment by mtgsquad** [comment]
> > > hello?? @TheBotlyNoob
> > 
> > Please don't ping the maintainers
> 
> There was legit no chance of my pr being noticed, it's now at the very back of the prs

Well, no. Because I'm a maintainer and I get emails on every activity on every PR. (Watch enabled for this repo)

**Comment by mtgsquad** [comment]
Also in order to get your PRs merged quicker use the discord to just ask, or make it with the register site. Both of those get more priority.

**Review by mtgsquad — APPROVED** [review]

**Comment by D99-1** [comment]
> Also in order to get your PRs merged quicker use the discord to just ask, or make it with the register site. Both of those get more priority.

I used the website to make this pr

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
