### PR TITLE
Updating dibster.is-a.dev

### PR DESCRIPTION
**Pull request by DEV-DIBSTER**
1. Changed description.
2. Adding Twitter handle.
3. Adding MX mail server records.

### CODE REVIEW

**Comment by AbubakarKang** [comment]
You can only have one type of record according to [this](https://github.com/is-a-dev/register/blob/main/docs/maintainers/pr-review.md).

**Comment by DIBSTERYT** [comment]
Oh, I was going off of this [file](https://github.com/is-a-dev/register/blob/7161ba730ef075c92911ab51766dd6cf0b9ead51/domains/oreki.json), which had additional records. If that's the case and I can't have more than 1 record, I'll make a edit tomorrow to remove MX records.

**Comment by AbubakarKang** [comment]
I am not sure if that file is up to date, and it has `Internal Server Error` as well.

**Review by MaskDuck — APPROVED** [review]
uh gud

**Pull request merged**
