### PR TITLE
Register formuna.is-a.dev

### PR DESCRIPTION
**Pull request by FormunaGit**
Register formuna.is-a.dev with TXT record pointing to vc-domain-verify=formuna.is-a.dev,13260821808507d1277b.

### CODE REVIEW

**Comment by FormunaGit** [comment]
Um, I'm a bit new to URL stuff like this so if needed, the thing that vercel gave me is this:
Type    Name    Value
TXT      _vercel   vc-domain-verify=formuna.is-a.dev,13260821808507d1277b

**Review by iostpa — CHANGES_REQUESTED** [review]
We do not support Vercel.

**Comment by FormunaGit** [comment]
What? Why?

**Comment by FormunaGit** [comment]
Oh, nevermind. I'll use another provider then

**Pull request closed without merging**
