### PR TITLE
Register linky.is-a.dev, and delete _discord.grafaffel.is-a.dev

### PR DESCRIPTION
**Pull request by Grafaffel**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

image

### CODE REVIEW

**Review by Omxpro — CHANGES_REQUESTED** [review]
Link not found

**Comment by Grafaffel** [comment]
> Link not found
@Omxpro 

this is the intended behavior. it is a link shortener

**Comment by Omxpro** [comment]
> > Link not found
> > @Omxpro
> 
> this is the intended behavior. it is a link shortener

we still have to see your site

**Comment by Grafaffel** [comment]
it is now updated

**Review by Omxpro — APPROVED** [review]

**Review by DEV-DIBSTER — APPROVED** [review]

**Pull request merged**
