### PR TITLE
BETA: Register sumitrajak.is-a.dev

### PR DESCRIPTION
**Pull request by SumitRajak404**
Added `sumitrajak.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Review by Omxpro — CHANGES_REQUESTED** [review]
404, cannot access site

**Review by SumitRajak404 — COMMENTED** [review]
The site is accessable

**Review by SumitRajak404 — COMMENTED** [review]
Now 
The site is accessable

**Review by Omxpro — APPROVED** [review]
approved but you should change URL to CNAME. it will be better. read https://is-a.dev/docs for more

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
