### PR TITLE
Create sajidportfolio.json

### PR DESCRIPTION
**Pull request by sajidhussaindev**

### CODE REVIEW

**Comment by Sajid-tech** [comment]
seem right

**Review by Sajid-tech — APPROVED** [review]
seems right

**Review by Sajid-tech — COMMENTED** [review]
good

**Review by Sajid-tech — APPROVED** [review]
pretty good

**Review by Sajid-tech — COMMENTED** [review]
good

**Review by sajidhussaindev — COMMENTED** [review]
d

**Review by Sajid-tech — COMMENTED** [review]
done

**Comment by sajidhussaindev** [comment]
done

**Pull request closed without merging**
