### PR TITLE
BETA: Register 1ly4s0.is-a.dev

### PR DESCRIPTION
**Pull request by 1ly4s0**

### CODE REVIEW

**Review by DEV-DIBSTER — APPROVED** [review]

**Comment by wdhdev** [comment]
@1ly4s0 Please don't abuse the report system by reporting your own PR, thanks.

**Comment by 1ly4s0** [comment]
I want to just delete that pull request.

**Comment by CuteDog5695** [comment]
I don't think you can delete merged PRs

**Comment by 1ly4s0** [comment]
So just revert it.

**Comment by CuteDog5695** [comment]
Bro your file is already deleted. But this pull request cannot be removed since its already merged.

**Pull request merged**
