### PR TITLE
feat: update records

### PR DESCRIPTION
**Pull request by fxrysh**

### CODE REVIEW

**Review by AbubakarKang — COMMENTED** [review]
You can't have more records with CNAME.

**Comment by fxrysh** [comment]
> You can't have more records with CNAME.

WDYM? I can only have `CNAME` or the others? Not both?

**Review by MaskDuck — CHANGES_REQUESTED** [review]
unfortunately you cant have any other records if you have a cname as abubakar say, but feel free to create a subdomain such as `mail.farish.is-a.dev` to handle your mail!

**Comment by fxrysh** [comment]
> unfortunately you cant have any other records if you have a cname as abubakar say, but feel free to create a subdomain such as `mail.farish.is-a.dev` to handle your mail!

To do that, just create `mail.farish.json`?

**Comment by MaskDuck** [comment]
yes!

**Comment by fxrysh** [comment]
Alright, in that case I'll close this PR first. Thanks

**Pull request closed without merging**
