### PR TITLE
Update zeptar.json

### PR DESCRIPTION
**Pull request by ghost**
To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [x] You're not using Vercel or Netlify.
- [ ] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: https://zeptar.pages.dev
- [x] The website is reachable.
- [x] The CNAME record doesn't contain any slash.
- [x] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 I've updated my wrong contacts at the owner field. It doesn't really matter if it doesn't get merged but yeah.

### CODE REVIEW

**Review by wdhdev — DISMISSED** [review]

**Comment by Zeptar1069** [comment]
Changed to Cloudflare Pages.

**Comment by Zeptar1069** [comment]
Awating to merge, repo link chaged and hosted on Gitpod.

**Comment by Zeptar1069** [comment]
Changed to Heroku

**Comment by Zeptar1069** [comment]
Expecting no more changes.

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please finish your website

**Comment by Zeptar1069** [comment]
Alright, close this PR for now.

**Pull request closed without merging**
