### PR TITLE
Register Subdomain: joshatticus

### PR DESCRIPTION
**Pull request by JoshAtticus**
Added the domain: joshatticus

### CODE REVIEW

**Comment by JoshAtticus** [comment]
Alright that's better

**Review by wdhdev — APPROVED** [review]

**Comment by JoshAtticus** [comment]
Can't merge for some reason

**Comment by WilliamDavidHarrison** [comment]
> Can't merge for some reason

Only a maintainer can merge PRs

**Comment by WilliamDavidHarrison** [comment]
> Can't merge for some reason

Only a maintainer can merge PRs

**Comment by JoshAtticus** [comment]
> > Can't merge for some reason
> 
> Only a maintainer can merge PRs

Oh github says I can merge when a maintainer approves it for some reason.

**Comment by WilliamDavidHarrison** [comment]
> Any updates?

You just need to wait for a maintainer to merge this PR

**Comment by andrewstech** [comment]
Sorry for the late reply will merge your Pr now

**Review by andrewstech — APPROVED** [review]

**Comment by JoshAtticus** [comment]
> Sorry for the late reply will merge your Pr now

Thank you!

**Comment by JoshAtticus** [comment]
How do I fix this error? 

E40EC9C9-4525-4F81-87C0-8F28E2C0C887

**Comment by WilliamDavidHarrison** [comment]
> How do I fix this error?
> 
> E40EC9C9-4525-4F81-87C0-8F28E2C0C887

Just wait a few minutes for GitHub to issue an SSL and you'll be good.

**Comment by JoshAtticus** [comment]
> -snip-
> Just wait a few minutes for GitHub to issue an SSL and you'll be good.

Alright thank you!

**Pull request merged**
