### PR TITLE
new json

### PR DESCRIPTION
**Pull request by tobiko-dev**
To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [ X] You're not using Vercel or Netlify.
- [ X] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [ X] The website is reachable.
- [ X] The CNAME record doesn't contain any slash.
- [ X] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

### CODE REVIEW

**Comment by WilliamDavidHarrison** [comment]
@ZeraAI you the TXT is a record type, not a note. Put that in the description field.

**Comment by ZeraAI** [comment]
I went ahead and deleted the TXT altogether. Will this new one work?

**Comment by WilliamDavidHarrison** [comment]
@ZeraAI Yes it should.

**Comment by ZeraAI** [comment]
Is there anything else left for me to do? Or should I wait until the merge has been completed?

**Comment by WilliamDavidHarrison** [comment]
@ZeraAI I think that’s it. Just wait for it to be merged. If you want you can join the Discord server: https://discord.gg/PZCGHz4RhQ

**Comment by ZeraAI** [comment]
> @ZeraAI I think that’s it. Just wait for it to be merged. If you want you can join the Discord server: https://discord.gg/PZCGHz4RhQ

how long does a merge typically take? I see some newer than mine that have merged already

**Comment by WilliamDavidHarrison** [comment]
> > @ZeraAI I think that’s it. Just wait for it to be merged. If you want you can join the Discord server: https://discord.gg/PZCGHz4RhQ
> 
> how long does a merge typically take? I see some newer than mine that have merged already

Just be patient.

**Review by MaskDuck — APPROVED** [review]
on behalf of the maintainer team, i apologise for the long wait time.

**Pull request merged**
