### PR TITLE
Update cat.sx9.json

### PR DESCRIPTION
**Pull request by satr14washere**

### CODE REVIEW

**Comment by SX-9** [comment]
Also dont merge yet until i say so

**Comment by SX-9** [comment]
Alr now merge

**Review by TheBotlyNoob — CHANGES_REQUESTED** [review]
:eyes:

we require that you at least have something in your website.

image

**Comment by SX-9** [comment]
Dw its gonna be proxyed to my bot hosting server if its already merge

**Comment by SX-9** [comment]
@TheBotlyNoob

**Pull request closed without merging**
