### PR TITLE
Update azumi.aqua.json

### PR DESCRIPTION
**Pull request by AquaQuokka**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.

### CODE REVIEW

**Review by omsenjalia — DISMISSED** [review]
👍👍

**Comment by TerraPlayz** [comment]
@AquaQuokka i think your pr was already merged. You opened 2 new prs for no reason. Your just creating patch branches

**Comment by AquaQuokka** [comment]
I'm trying to delete azumi.aqua.json but it won't work

**Comment by AquaQuokka** [comment]
Can you do it for me

**Comment by AquaQuokka** [comment]
Everything is weird for me. I saw a notification for your message about spamming pull requests, but I cant find it anywhere.

**Comment by WilliamDavidHarrison** [comment]
> Can you do it for me

Done.

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
