### PR TITLE
Register Subdomain: darshit-shah

### PR DESCRIPTION
**Pull request by dcshah2002**
Added the domain: darshit-shah

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please use a different IP

**Review by dcshah2002 — COMMENTED** [review]
Changed Record type and added domain

**Review by wdhdev — CHANGES_REQUESTED** [review]
404

**Comment by dcshah2002** [comment]
> 404

My bad, Fixed it now

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please finish your website

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please finish your website

**Comment by WilliamDavidHarrison** [comment]
Unfinished website and no response

**Pull request closed without merging**
