### PR TITLE
Reclaiming aayush.json

### PR DESCRIPTION
**Pull request by aayushxr**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://www.aayushrajagopalan.com/

### CODE REVIEW

**Comment by Aayush-Rajagopalan** [comment]
I don't know who OpAayush is, that is not my account.

**Comment by WilliamDavidHarrison** [comment]
> I don't know who OpAayush is, that is not my account.

We mean, you deleted your domain and someone else has claimed it. You need to get the new user to either let you have the domain or not.

**Comment by WilliamDavidHarrison** [comment]
@OpAayush Do you want to give your domain to this user?

**Comment by OpAayush** [comment]
No bro i don't wanna give

**Comment by mtgsquad** [comment]
@Aayush-Rajagopalan We can get a different subdomain sorted out for you. `aayush-r.is-a.dev` could work.

**Pull request closed without merging**
