### PR TITLE
Changed file name from debug.json to satindar.json

### PR DESCRIPTION
**Pull request by Satindar31**
and also some other stuff

### CODE REVIEW

**Comment by Satindar31** [comment]
@TheBotlyNoob pls review

**Comment by Satindar31** [comment]
@hackermondev

**Comment by Satindar31** [comment]
@TheBotlyNoob

**Comment by Satindar31** [comment]
@TheBotlyNoob

**Review by phenax — CHANGES_REQUESTED** [review]
Your record file seems to have a syntax error

**Pull request closed without merging**
