### PR TITLE
Register itsomsarraf.is-a.dev

### PR DESCRIPTION
**Pull request by itsOmSarraf**
Added `itsomsarraf.is-a.dev` using the [CLI](https://www.npmjs.com/package/@is-a-dev/cli).

### CODE REVIEW

**Comment by EtherealTheDev** [comment]
You have nothing in your A record, you need to have a website attached with it

**Comment by itsOmSarraf** [comment]
Will this work ?

https://itsomsarraf.github.io

**Comment by EtherealTheDev** [comment]
Yes but make sure it's a CNAME record and it's only a domain:
{
    "CNAME": "itsomsarraf.github.io"
}

**Comment by itsOmSarraf** [comment]
Will do, thanks

**Pull request closed without merging**
