### PR TITLE
Register wallp.is-a.dev

### PR DESCRIPTION
**Pull request by gregcorp**
Added `wallp.is-a.dev` using the [CLI](https://www.npmjs.com/package/@is-a-dev/cli).

### CODE REVIEW

**Comment by EtherealTheDev** [comment]
Why'd you delete it 💀

**Comment by EtherealTheDev** [comment]
Also your website is down

**Review by wdhdev — CHANGES_REQUESTED** [review]
I cannot reach your website.

**Comment by gregcorp** [comment]
I made the web recheable.

**Comment by gregcorp** [comment]
website *

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
