### PR TITLE
Create rai-ryui.json

### PR DESCRIPTION
**Pull request by nekomekoraiyuu**
### Requirements
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [x] The website is reachable.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### Link to Website

https://nekomekoraiyuu.github.io/

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please finish your website

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please finish your website

**Comment by nekomekoraiyuu** [comment]
Sure xd
should i be closing this pull req? since iam gonna do this abit later
sorry for the inconveniences

**Comment by WilliamDavidHarrison** [comment]
> Sure xd should i be closing this pull req? since iam gonna do this abit later sorry for the inconveniences

Might be a good idea and then later open a new one.

**Comment by nekomekoraiyuu** [comment]
> > Sure xd should i be closing this pull req? since iam gonna do this abit later sorry for the inconveniences
> 
> Might be a good idea and then later open a new one.

Okay then I'll be closing the pull req gonna make one later when finished!

**Pull request closed without merging**
