### PR TITLE
Register maps.vulcanocraft.is-a.dev

### PR DESCRIPTION
**Pull request by VulcanoSoftware**
Register maps.vulcanocraft.is-a.dev with CNAME record pointing to vulcanomap.pages.dev.

### CODE REVIEW

**Comment by VulcanoSoftware** [comment]
I am already waiting 2 days I will be very happy if this will be merged while I am still alive

**Comment by cupglassDEV** [comment]
> I am already waiting 2 days I will be very happy if this will be merged while I am still alive

just **wait**. We're experiencing with high PR request

**Comment by VulcanoSoftware** [comment]
> > I am already waiting 2 days I will be very happy if this will be merged while I am still alive
> 
> just **wait**. We're experiencing with high PR request

If you are on my PR to reply then you can also just click the merge button

**Comment by cupglassDEV** [comment]
@VulcanoSoftware 
> > > I am already waiting 2 days I will be very happy if this will be merged while I am still alive
> > 
> > 
> > just **wait**. We're experiencing with high PR request
> 
> If you are on my PR to reply then you can also just click the merge button

you think im an admin because of my role (Contributor) on is-a.dev??

it literally says CONTRIBUTOR, not ADMIN or MAINTAINER

just chill

**Pull request merged**
