### PR TITLE
Kindly register x.is-a.dev

### PR DESCRIPTION
**Pull request by leofelix908**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

xproject-xi.vercel.app

### CODE REVIEW

**Comment by leofelix908** [comment]
> x.is-a.dev is taken.

that domain isn't pointing to any website, and he got another domain "https://jvideo.is-a.dev/". further his discord isn't available at all, nor any other social media to contact him so I am unable to find him anywhere.
I will use this domain for my all projects and I'll keep it active and maintained. 
if you guys can consider me deserving I'll be really thankful.

**Comment by xTahseen** [comment]
> @leofelix908
> 
> > > x.is-a.dev is taken.
> > 
> > 
> > that domain isn't pointing to any website, and he got another domain "https://jvideo.is-a.dev/". further his discord isn't available at all, nor any other social media to contact him so I am unable to find him anywhere. I will use this domain for my all projects and I'll keep it active and maintained. if you guys can consider me deserving I'll be really thankful.
> 
> No, you still cant. Contact the original owner. Or if the contact was gone, just leave the domain alone


> @leofelix908
> 
> > > x.is-a.dev is taken.
> > 
> > 
> > that domain isn't pointing to any website, and he got another domain "https://jvideo.is-a.dev/". further his discord isn't available at all, nor any other social media to contact him so I am unable to find him anywhere. I will use this domain for my all projects and I'll keep it active and maintained. if you guys can consider me deserving I'll be really thankful.
> 
> No, you still cant. Contact the original owner. Or if the contact was gone, just leave the domain alone

I think you should give domains to the people who need them instead of abondening it. so they can better work on it.

**Comment by leofelix908** [comment]
@cupglassDEV @orangci @Stef-00012 brother it's already deprecated if someone was using then it would have been answered this pull by now. Apart from that everything is clear that neither it is pointing to any website nor anything else. The most important owner is no longer interested and his social media is nowhere. I really like it so I want to use it for all my projects i'll be really thankful if you can consider me.

**Comment by cupglassDEV** [comment]
@leofelix908  
> @cupglassDEV @orangci @Stef-00012 brother it's already deprecated if someone was using then it would have been answered this pull by now. Apart from that everything is clear that neither it is pointing to any website nor anything else. The most important owner is no longer interested and his social media is nowhere. I really like it so I want to use it for all my projects i'll be really thankful if you can consider me.

You didnt read my message??

No, you still cant.
Contact the original owner. Or if the contact was gone, just leave the domain alone

Im not a narssist or whatsoever, but thats the rules, and we can't change it. You need to approach the actual owner so you can claim in

**Comment by cupglassDEV** [comment]
> Uugh, I pinged the dude in the discord server now. I'll wait at least 24 hours or so.
> 
> Also I'd normally not procced to merge this PR, considering the person might be busy IRL. Depends on what the admin has to say though..

hmm thats right. But if the OP still insists us to merge, we will wait the original owner, since u already pinged recently

<sup>tbh, the OP just yaps alot, just speak to the fricking point plss 😭 </sup>

**Comment by cupglassDEV** [comment]
In case if the OP still like a stubborn guy
image

**Comment by cupglassDEV** [comment]
@xTahseen 
> > > > x.is-a.dev is taken.
> > > that domain isn't pointing to any website, and he got another domain "https://jvideo.is-a.dev/". further his discord isn't available at all, nor any other social media to contact him so I am unable to find him anywhere. I will use this domain for my all projects and I'll keep it active and maintained. if you guys can consider me deserving I'll be really thankful.
> > 
> > 
> > No, you still cant. Contact the original owner. Or if the contact was gone, just leave the domain alone
> 
> I think you should give domains to the people who need them instead of abondening it. so they can better work on it.

so why the maintainer just dont accepted it??? that means... it needs the original owner to accept it, or else just abandon it

**Comment by leofelix908** [comment]
> @leofelix908
> 
> > @cupglassDEV brother it's already deprecated if someone was using then it would have been answered this pull by now. Apart from that everything is clear that neither it is pointing to any website nor anything else. The most important owner is no longer interested and his social media is nowhere. I really like it so I want to use it for all my projects i'll be really thankful if you can consider me.
> 
> You didnt read my message??
> 
> > No, you still cant.
> > Contact the original owner. Or if the contact was gone, just leave the domain alone
> 
> Im not a narcist or whatsoever, but thats the rules, and we can't change it. You need to approach the actual owner so you can claim it
> 
> For example #17033. The original AND new owner already get in touch and already agrees to take over the domain, so... READ MY MESSAGE AGAIN, IT DOSENT MATTER

I tried to approach owner but he isn't responding anywhere

**Comment by leofelix908** [comment]
> Uugh, I pinged the dude in the discord server now. I'll wait at least 24 hours or so.
> 
> Also I'd normally not procced to merge this PR, considering the person might be busy IRL. Depends on what the admin has to say though..

thank you so much, we can wait for owner

**Comment by VaibhavSys** [comment]
If a domain is claimed, and someone else wants to claim it, that is not possible, even if the domain is misconfigured or not in use. It can only be transferred with the original owner's consent, or if the contact methods of the original owner are invalid. If the contact methods are valid, the owner is to be contacted there, and on GitHub, and if the owner agrees then the domain can be transferred, and if the owner doesn't agree then the domain cannot be transferred. In case the original owner doesn't respond even after waiting, then a decision is taken to transfer or not on a case-by-case basis.

Currently, @CuteDog5695 has already contacted the original owner, so let's wait for their response.

**Comment by xTahseen** [comment]
> @xTahseen
> 
> > > > > x.is-a.dev is taken.
> > > > > that domain isn't pointing to any website, and he got another domain "https://jvideo.is-a.dev/". further his discord isn't available at all, nor any other social media to contact him so I am unable to find him anywhere. I will use this domain for my all projects and I'll keep it active and maintained. if you guys can consider me deserving I'll be really thankful.
> > > 
> > > 
> > > No, you still cant. Contact the original owner. Or if the contact was gone, just leave the domain alone
> > 
> > 
> > I think you should give domains to the people who need them instead of abondening it. so they can better work on it.
> 
> so why the maintainer just dont accepted it??? that means... it needs the original owner to accept it, or else just abandon it

Instead of this domain being with the needy, you are saying that it should just be left like this, thus, there will be a pile of dead domains. nvm

**Comment by cupglassDEV** [comment]
> > @xTahseen
> > 
> > > > > > x.is-a.dev is taken.
> > > > > > that domain isn't pointing to any website, and he got another domain "https://jvideo.is-a.dev/". further his discord isn't available at all, nor any other social media to contact him so I am unable to find him anywhere. I will use this domain for my all projects and I'll keep it active and maintained. if you guys can consider me deserving I'll be really thankful.
> > > > 
> > > > 
> > > > No, you still cant. Contact the original owner. Or if the contact was gone, just leave the domain alone
> > > 
> > > 
> > > I think you should give domains to the people who need them instead of abondening it. so they can better work on it.
> > 
> > so why the maintainer just dont accepted it??? that means... it needs the original owner to accept it, or else just abandon it
> 
> Instead of this domain being with the needy, you are saying that it should just be left like this, thus, there will be a pile of dead domains. nvm

Read the fricking @VaibhavSys message. u only see mine and just nothing???

**Comment by CuteDog5695** [comment]
@cupglassDEV Stop it please, being mad at people will only make it worse.

**Comment by Stef-00012** [comment]
the owner of the `x.is-a.dev` domain sais that they want to keep it so you can't take it
image

**Pull request closed without merging**
