### PR TITLE
Update api.anshtyagi.json

### PR DESCRIPTION
**Pull request by anshtyagi0**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.

### CODE REVIEW

**Review by mtgsquad — DISMISSED** [review]
Unfortunately, we do not support CNAME and TXT at the same time.

**Comment by mtgsquad** [comment]
cc @andrewstech We might have to look into alternate verification methods.

**Comment by mtgsquad** [comment]
@anshtyagi0 I would prefer you join our discord server to discuss more: https://discord.gg/tFYWYPGyAa

**Comment by anshtyagi0** [comment]
@mtgsquad Please approve now.

**Review by wdhdev — CHANGES_REQUESTED** [review]
We don't support TXT verification.

**Comment by anshtyagi0** [comment]
@WilliamDavidHarrison  removed txt record.

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
