### PR TITLE
Troytech Responded

### PR DESCRIPTION
**Pull request by Tmoneytroyt**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

IMG_0191

Its a games website

### CODE REVIEW

**Review by iostpa — CHANGES_REQUESTED** [review]
Late response but uh, one question.
>Its a games website
Is it games that you've made or is it pirated games?

**Comment by Tmoneytroyt** [comment]
I use my home server as a proxy to redirect to the official game site

**Comment by Tmoneytroyt** [comment]
So I use the games from the direct source

**Comment by Tmoneytroyt** [comment]
No I do not pirate games

**Comment by Tmoneytroyt** [comment]
So no I do not pirate the games

**Pull request closed without merging**
