### PR TITLE
Create keju.json

### PR DESCRIPTION
**Pull request by kejuuu**

### CODE REVIEW

**Review by MaskDuck — APPROVED** [review]
sus

**Comment by omxpro** [comment]
Everything sounds good

**Comment by kejuuu** [comment]
> sus
 or am i ?

**Comment by MaskDuck** [comment]
:mmLol:

**Comment by omxpro** [comment]
Congratulations on merge!

**Comment by kejuuu** [comment]
> Congratulations on merge!

Thank you :D

**Comment by MaskDuck** [comment]
:mmLol: dont forget to join our discord as well, well do tons of fun stuff there

**Comment by kejuuu** [comment]
> :mmLol: dont forget to join our discord as well, well do tons of fun stuff there

Awesome, definitely joining rn

**Comment by omxpro** [comment]
> > Congratulations on merge!
> 
> Thank you :D

NP!

**Pull request merged**
