### PR TITLE
BETA: Register stephen-adeniji.is-a.dev

### PR DESCRIPTION
**Pull request by Praizee**
Added `stephen-adeniji.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Review by MaskDuck — DISMISSED** [review]

**Review by triach-rold — CHANGES_REQUESTED** [review]
Nice website. Reachable and complete, but I don't think they allow vercel or netlify.

**Comment by Praizee** [comment]
> Nice website. Reachable and complete, but I don't think they allow vercel or netlify.

Thanks
Oh okay
So I can't use the domain?

**Comment by CuteDog5695** [comment]
> > Nice website. Reachable and complete, but I don't think they allow vercel or netlify.
> 
> Thanks Oh okay So I can't use the domain?

With Vercel or Netlify, no (but if its URL record then its fine since it just redirects)

**Comment by Praizee** [comment]
> > > Nice website. Reachable and complete, but I don't think they allow vercel or netlify.
> > 
> > 
> > Thanks Oh okay So I can't use the domain?
> 
> With Vercel or Netlify, no (but if its URL record then its fine since it just redirects)

I tried URL record and got this: "invalid url record"
Which record should I have used?

**Comment by CuteDog5695** [comment]
> > > > Nice website. Reachable and complete, but I don't think they allow vercel or netlify.
> > > 
> > > 
> > > Thanks Oh okay So I can't use the domain?
> > 
> > 
> > With Vercel or Netlify, no (but if its URL record then its fine since it just redirects)
> 
> I tried URL record and got this: "invalid url record" Which record should I have used?

It isnt valid because you didnt add https:// to the record

**Comment by Praizee** [comment]
> > > > > Nice website. Reachable and complete, but I don't think they allow vercel or netlify.
> > > > 
> > > > 
> > > > Thanks Oh okay So I can't use the domain?
> > > 
> > > 
> > > With Vercel or Netlify, no (but if its URL record then its fine since it just redirects)
> > 
> > 
> > I tried URL record and got this: "invalid url record" Which record should I have used?
> 
> It isnt valid because you didnt add https:// to the record

😅🤦🏽
I've added it, thanks

**Review by iostpa — APPROVED** [review]
seems good to me now (also nice website!)

**Pull request merged**
