### PR TITLE
Requesting for website addition

### PR DESCRIPTION
**Pull request by hamza8bit**
Kindly add my website to it, which is still underdevelopment and I will publish it soon

### CODE REVIEW

**Comment by WilliamDavidHarrison** [comment]
@hamza8bit The website needs to be finished before you get the domain.

**Comment by hamza8bit** [comment]
> 

Alright, I will get to it.

**Comment by hamza8bit** [comment]
I just updated my site, it still quite old site, but just wondering if it is allowed. Sorry for being hasty, I have recently heard about this site and don't want my name to be taken by someone else, too many Hamza in this world.

**Comment by WilliamDavidHarrison** [comment]
@hamza8bit You should join the discord server and ask a maintainer to merge the pr.

**Comment by WilliamDavidHarrison** [comment]
https://discord.gg/PZCGHz4RhQ

**Comment by hamza8bit** [comment]
> @hamza8bit You should join the discord server and ask a maintainer to merge the pr.

I joined the discord server but not sure whom to ask and I don't see any specific channel intended for it.

**Comment by WilliamDavidHarrison** [comment]
@hamza8bit Ping m^2 in general.

**Review by MaskDuck — APPROVED** [review]

**Pull request merged**
