### PR TITLE
BETA: Register maindak.is-a.dev

### PR DESCRIPTION
**Pull request by masroof-maindak**
Added `masroof_maindak.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
We do not support underscores (`_`) in domain names.

**Comment by masroof-maindak** [comment]
> 

Apologies, I've made the requested change.

**Review by wdhdev — APPROVED** [review]

**Review by wdhdev — CHANGES_REQUESTED** [review]
You will need to register `maindak.is-a.dev` first.

**Comment by masroof-maindak** [comment]
Should be good now... I've shortened my desired username further, could you please have another look?

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
