### PR TITLE
Create mail.sx9.json

### PR DESCRIPTION
**Pull request by satr14washere**
To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [x] The website is reachable.
- [x] The CNAME record doesn't contain any slash.
- [x] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

### CODE REVIEW

**Comment by WilliamDavidHarrison** [comment]
@SX-9 just add ImprovMX to sx9.is-a.dev then you can have yourname@sx9.is-a.dev

**Comment by WilliamDavidHarrison** [comment]
Also it’s failing since you need an A or URL record. CNAME won’t work since it can’t be used with other records.

**Comment by AceyDoCodes** [comment]
> Also it’s failing since you need an A or URL record. CNAME won’t work since it can’t be used with other records.

it worked for me on [my pr](https://github.com/is-a-dev/register/pull/2729)

**Comment by WilliamDavidHarrison** [comment]
> > Also it’s failing since you need an A or URL record. CNAME won’t work since it can’t be used with other records.
> 
> it worked for me on [my pr](https://github.com/is-a-dev/register/pull/2729)

I realised that. But according to the error it is because there is no A or URL.

**Comment by WilliamDavidHarrison** [comment]
Actually it might be because he has spaces in between the brackets for the MX records.

**Comment by SX-9** [comment]
> Also it’s failing since you need an A or URL record. CNAME won’t work since it can’t be used with other records.

Dw i fixed it

**Comment by WilliamDavidHarrison** [comment]
> > Also it’s failing since you need an A or URL record. CNAME won’t work since it can’t be used with other records.
> 
> Dw i fixed it

I thought that might be it, the JSON reference for the records.

**Review by andrewstech — APPROVED** [review]

**Pull request merged**
