### PR TITLE
Update 44.json

### PR DESCRIPTION
**Pull request by 44xo**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.

### CODE REVIEW

**Comment by JustDeveloper1** [comment]
dud
ur not an owner ( @9xN )
ig

**Comment by 44xo** [comment]
> dud ur not an owner ( @9xN ) ig

i am lol, just signed into the wrong account

**Comment by JustDeveloper1** [comment]
> > dud ur not an owner ( @9xN ) ig
> 
> i am lol, just signed into the wrong account

ok sorry

**Comment by 9xN** [comment]
> > > dud ur not an owner ( @9xN ) ig
> > 
> > 
> > i am lol, just signed into the wrong account
> 
> ok sorry

no worries, i am having an issue tho it seems to be redirecting to is-a.dev instead of my site

**Comment by JustDeveloper1** [comment]
because `.is-a.dev` is down

**Comment by CuteDog5695** [comment]
Its more or less that the Admin is changing to a different Cloudflare account (for some reason :/)

**Comment by 9xN** [comment]
> Its more or less that the Admin is changing to a different Cloudflare account (for some reason :/)

whats the expected downtime for this?

**Pull request closed without merging**
