### PR TITLE
Register vrbz.is-a.dev

### PR DESCRIPTION
**Pull request by vrbz**
Register vrbz.is-a.dev with CNAME record pointing to vrbz.ddns.net.

### CODE REVIEW

**Review by omsenjalia — CHANGES_REQUESTED** [review]
Unable to access website

**Comment by vrbz** [comment]
hey, im trying to use this for other protocols not just website hosting, or is there an issue with using the service for this?

**Comment by orxngc** [comment]
@vrbz What other protocols? Please elaborate.

**Comment by orxngc** [comment]
Closing as stale.

**Pull request closed without merging**
