### PR TITLE
Create _github-pages-challenge-bad-boy-codes.semant.json

### PR DESCRIPTION
**Pull request by s3mant**
GitHub domain verification 🙄

### CODE REVIEW

**Comment by andrewstech** [comment]
We have launched an investigation into GitHub pages and ask that you use a different provider at this time.
Cloudflare pages is a good alternative.

**Comment by Bad-Boy-Codes** [comment]
> We have launched an investigation into GitHub pages and ask that you use a different provider at this time. Cloudflare pages is a good alternative.

is there no way to just go with GitHub ?

**Comment by WilliamDavidHarrison** [comment]
This has been fixed: #3445

**Review by wdhdev — DISMISSED** [review]

**Review by wdhdev — APPROVED** [review]
The CI checks might not work correctly because this PR was made before the changes were made, but if it is merged, it will work.

**Comment by Bad-Boy-Codes** [comment]
> The CI checks might not work correctly because this PR was made before the changes were made, but if it is merged, it will work.

so then should I go and make another pr or just wait for a maintainer to merge it

**Comment by Bad-Boy-Codes** [comment]
> The CI checks might not work correctly because this PR was made before the changes were made, but if it is merged, it will work.

so then should I go and make another pr or just wait for a maintainer to merge it

**Comment by WilliamDavidHarrison** [comment]
> > The CI checks might not work correctly because this PR was made before the changes were made, but if it is merged, it will work.
> 
> so then should I go and make another pr or just wait for a maintainer to merge it

@Bad-Boy-Codes Wait for a maintainer to merge it.

**Pull request closed without merging**
