### PR TITLE
BETA: Register jabin.is-a.dev

### PR DESCRIPTION
**Pull request by Jab11n**
Added `jabin.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Comment by 21Z** [comment]
Your github website seems to redirect to another website, You could use an `URL` record pointing to that website instead.

**Comment by jabinstech** [comment]
> Your github website seems to redirect to another website, you could use a `URL` record pointing to that website instead.

My jabinstech.github.io website does not redirect to another website?

**Comment by 21Z** [comment]
> My jabinstech.github.io website does not redirect to another website?

It does not redirect but it asks the person to click on a link that takes to another website
+ I was just suggesting.

**Comment by jabinstech** [comment]
> > My jabinstech.github.io website does not redirect to another website?
> 
> It does not redirect but it asks the person to click on a link that takes to another website + I was just suggesting.

Ah, I see what you mean. Yes, that's temporary until I have the time to make or find a better website to put there.

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
