### PR TITLE
Update community.nziie.json

### PR DESCRIPTION
**Pull request by Nzii3**
Update cname

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.

### CODE REVIEW

**Review by wdhdev — APPROVED** [review]

**Comment by WilliamDavidHarrison** [comment]
Just an FYI, you can use a URL record for redirection.

**Comment by Nzii3** [comment]
> Just an FYI, you can use a URL record for redirection.

@WilliamDavidHarrison What do you mean?

**Comment by WilliamDavidHarrison** [comment]
> > Just an FYI, you can use a URL record for redirection.
> 
> @WilliamDavidHarrison What do you mean?

If you use:

```
"URL": "https://google.com"
```

Will redirect the domain to https://google.com

**Comment by Nzii3** [comment]
> > > Just an FYI, you can use a URL record for redirection.
> > 
> > 
> > @WilliamDavidHarrison What do you mean?
> 
> If you use:
> 
> ```
> "URL": "https://google.com"
> ```
> 
> Will redirect the domain to https://google.com

Oh I didn’t know that, I’ll remember that for future use, thanks.

**Pull request merged**
