### PR TITLE
Create ak.json

### PR DESCRIPTION
**Pull request by AKGaming0001**
To make our job easier, please spend time to review your application before submitting. 

- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [x] The website is reachable.
- [x] The CNAME record doesn't contain any slash.
- [x] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.

### CODE REVIEW

**Comment by AKGaming0001** [comment]
hello, can you review my json please. 😃 ty

**Review by MaskDuck — DISMISSED** [review]
it is linked to another website already. github pages only allows 1 custom domain per page.

**Comment by AKGaming0001** [comment]
> it is linked to another website already. github pages only allows 1 custom domain per page.

Actually i needed this domain, added that one because this wasn't being reviewed, if i remove that one will this be approved?

**Comment by TheBotlyNoob** [comment]
could you make a pr removing the other one, then we can merge this one.

**Comment by AKGaming0001** [comment]
ok gimme a moment

**Comment by AKGaming0001** [comment]
done it's deleted

**Comment by AKGaming0001** [comment]
> could you make a pr removing the other one, then we can merge this one.

btw how much time will it take

**Review by hackermondev — APPROVED** [review]

**Review by hackermondev — DISMISSED** [review]

**Review by hackermondev — APPROVED** [review]

**Pull request merged**
