### PR TITLE
Register Subdomain: austinleath

### PR DESCRIPTION
**Pull request by AustinLeath**
Added the domain: austinleath

### CODE REVIEW

**Comment by AustinLeath** [comment]
This is so awesome. I love the idea behind this

**Comment by WilliamDavidHarrison** [comment]
@AustinLeath The IP adress returns a 404.

**Comment by AustinLeath** [comment]
Yes, i need to setup a reverse proxy on my nginx reverse proxy host > @AustinLeath The IP address returns a 404.

**Comment by WilliamDavidHarrison** [comment]
> Yes, i need to setup a reverse proxy on my nginx reverse proxy host > @AustinLeath The IP address returns a 404.

Oh. Is the website that will be hosted there just your website https://austinleath.com ?

**Comment by AustinLeath** [comment]
> > Yes, i need to setup a reverse proxy on my nginx reverse proxy host > @AustinLeath The IP address returns a 404.
> 
> 
> 
> Oh. Is the website that will be hosted there just your website https://austinleath.com ?

Good question! I am developing a portfolio page that features some of my github projects / other achievements. You can think of it kind of like a resume page

**Comment by WilliamDavidHarrison** [comment]
> > > Yes, i need to setup a reverse proxy on my nginx reverse proxy host > @AustinLeath The IP address returns a 404.
> > 
> > 
> > Oh. Is the website that will be hosted there just your website https://austinleath.com ?
> 
> Good question! I am developing a portfolio page that features some of my github projects / other achievements. You can think of it kind of like a resume page

Good idea, is it static?

**Comment by AustinLeath** [comment]
> > > > Yes, i need to setup a reverse proxy on my nginx reverse proxy host > @AustinLeath The IP address returns a 404.
> 
> > > 
> 
> > > 
> 
> > > Oh. Is the website that will be hosted there just your website https://austinleath.com ?
> 
> > 
> 
> > Good question! I am developing a portfolio page that features some of my github projects / other achievements. You can think of it kind of like a resume page
> 
> 
> 
> Good idea, is it static?

Yes indeed. I don't have time to make it a fancy react app

**Comment by WilliamDavidHarrison** [comment]
> > > > > Yes, i need to setup a reverse proxy on my nginx reverse proxy host > @AustinLeath The IP address returns a 404.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Oh. Is the website that will be hosted there just your website https://austinleath.com ?
> > 
> > 
> > > 
> > 
> > 
> > > Good question! I am developing a portfolio page that features some of my github projects / other achievements. You can think of it kind of like a resume page
> > 
> > 
> > Good idea, is it static?
> 
> Yes indeed. I don't have time to make it a fancy react app

Since it is static, you could use GitHub pages which is free.

**Comment by AustinLeath** [comment]
> > > > > > Yes, i need to setup a reverse proxy on my nginx reverse proxy host > @AustinLeath The IP address returns a 404.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > Oh. Is the website that will be hosted there just your website https://austinleath.com ?
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Good question! I am developing a portfolio page that features some of my github projects / other achievements. You can think of it kind of like a resume page
> 
> > > 
> 
> > > 
> 
> > > Good idea, is it static?
> 
> > 
> 
> > Yes indeed. I don't have time to make it a fancy react app
> 
> 
> 
> Since it is static, you could use GitHub pages which is free.

Indeed, I could also use AWS S3, but I wanted to utilize this really cool project. I could turn it into something advanced, it just might take me a while

**Comment by WilliamDavidHarrison** [comment]
> > > > > > > Yes, i need to setup a reverse proxy on my nginx reverse proxy host > @AustinLeath The IP address returns a 404.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > Oh. Is the website that will be hosted there just your website https://austinleath.com ?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > Good question! I am developing a portfolio page that features some of my github projects / other achievements. You can think of it kind of like a resume page
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Good idea, is it static?
> > 
> > 
> > > 
> > 
> > 
> > > Yes indeed. I don't have time to make it a fancy react app
> > 
> > 
> > Since it is static, you could use GitHub pages which is free.
> 
> Indeed, I could also use AWS S3, but I wanted to utilize this really cool project. I could turn it into something advanced, it just might take me a while

Have you made this project yet?

**Comment by AustinLeath** [comment]
> > > > > > > > Yes, i need to setup a reverse proxy on my nginx reverse proxy host > @AustinLeath The IP address returns a 404.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > Oh. Is the website that will be hosted there just your website https://austinleath.com ?
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > Good question! I am developing a portfolio page that features some of my github projects / other achievements. You can think of it kind of like a resume page
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > Good idea, is it static?
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Yes indeed. I don't have time to make it a fancy react app
> 
> > > 
> 
> > > 
> 
> > > Since it is static, you could use GitHub pages which is free.
> 
> > 
> 
> > Indeed, I could also use AWS S3, but I wanted to utilize this really cool project. I could turn it into something advanced, it just might take me a while
> 
> 
> 
> Have you made this project yet?

- [ ] Not exactly, but now that you mention it, i might just point it to the nginx virtual host for austinleath.com. In which case the code for that site is located at [https://github.com/austinleath/austinleath.com](git austinleath.com). Although i think the repo is private. I would check, but I am away from the computer at the moment (on phone)

**Comment by WilliamDavidHarrison** [comment]
The website has to be completed before you can get a is-a.dev subdomain, so you could point it to your current website and later open a new PR for the new website.

**Comment by AustinLeath** [comment]
Okay yeah let's do that then

**Comment by mtgsquad** [comment]
> Okay yeah let's do that then

Hello, I would consider moving this conversation to the is-a.dev discord server as this is becoming hard to read with all the quotes.

**Review by MaskDuck — APPROVED** [review]

**Pull request merged**
