### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by s3mant**
i messed up a little before in pr 1900

in this update
i added some badges
and centred the banner as well

### CODE REVIEW

**Comment by MaskDuck** [comment]
uh @phenax give me some opinion

**Comment by MaskDuck** [comment]
<p align="center">
GitHub GitHub contributors GitHub closed pull requests
<br/><br/>

is-a-dev banner
</p>
<br/>
**is-a-dev** is a service that allows developers to get a sweet-looking `.is-a.dev` domain for their personal websites.

<p align="center"> <a href="https://discord.gg/PZCGHz4RhQ">Discord</a></p>


## How do I register?
* Fork this repository
* Add a new `domains/your-domain-name.json` file directory to register `your-domain-name.is-a.dev`
* [Read the docs](./docs)
* The PR will be reviewed and merged
* After merging, the changes will take effect within a day
* That's it! Done! Now go show off your cool `.is-a.dev` domain



## Donations
This project is a free and open source service for developers and will stay that way.

Please consider donating to help me keep this running forever!

<a href="https://www.buymeacoffee.com/phenax" target="_blank">Buy Me A Coffee</a>
<a href="https://liberapay.com/phenax" target="_blank">Liberapay recurring donation button</a>




## Similar services
You should also checkout -
* [js.org](https://github.com/js-org/js.org/tree/master)
* [thedev.id](https://github.com/fransallen/thedev.id)
* [runs-on.tech](https://github.com/aakhilv/runs-on.tech)



## Uptime

Uptime Robot ratio (30 days)
Uptime Robot ratio (30 days)

You can check the uptime of the service via [our status dashboard](https://stats.uptimerobot.com/zY4XKIRVzw)




## License
This project is under the [GPL-3.0](./LICENSE) license.

**Comment by Bad-Boy-Codes** [comment]
> GitHub GitHub contributors GitHub closed pull requests is-a-dev banner **is-a-dev** is a service that allows developers to get a sweet-looking `.is-a.dev` domain for their personal websites. [Discord](https://discord.gg/PZCGHz4RhQ)
> 
> ## How do I register?
> * Fork this repository
> * Add a new `domains/your-domain-name.json` file directory to register `your-domain-name.is-a.dev`
> * [Read the docs](./docs)
> * The PR will be reviewed and merged
> * After merging, the changes will take effect within a day
> * That's it! Done! Now go show off your cool `.is-a.dev` domain
> 
> ## Donations
> This project is a free and open source service for developers and will stay that way.
> 
> Please consider donating to help me keep this running forever!
> 
> [Buy Me A Coffee](https://www.buymeacoffee.com/phenax) [Liberapay recurring donation button](https://liberapay.com/phenax)
> 
> ## Similar services
> You should also checkout -
> 
> * [js.org](https://github.com/js-org/js.org/tree/master)
> * [thedev.id](https://github.com/fransallen/thedev.id)
> * [runs-on.tech](https://github.com/aakhilv/runs-on.tech)
> 
> ## Uptime
> Uptime Robot ratio (30 days) Uptime Robot ratio (30 days)
> 
> You can check the uptime of the service via [our status dashboard](https://stats.uptimerobot.com/zY4XKIRVzw)
> 
> ## License
> This project is under the [GPL-3.0](./LICENSE) license.

updated...

**Comment by MaskDuck** [comment]
eh uglier

**Review by s3mant — COMMENTED** [review]
anigned banner sheesh

**Review by MaskDuck — APPROVED** [review]
uh looks good if @phenax doesnt complain about everything ill merge

**Comment by Bad-Boy-Codes** [comment]
> uh looks good if @phenax doesnt complain about everything ill merge



> nvm

btw the way you copy pasted is messed up
change that view

**Review by s3mant — COMMENTED** [review]
<p align="center">
   GitHub GitHub contributors GitHub closed pull requests
   <br/><br/>
   is-a-dev banner
   <br/></p>

   **is-a-dev** is a service that allows developers to get a sweet-looking `.is-a.dev` domain for their personal websites.
<p align="center">
   <br/
   <a href="https://discord.gg/PZCGHz4RhQ">Discord</a>
</p>


## How do I register?
* Fork this repository
* Add a new `domains/your-domain-name.json` file directory to register `your-domain-name.is-a.dev`
* [Read the docs](./docs)
* The PR will be reviewed and merged
* After merging, the changes will take effect within a day
* That's it! Done! Now go show off your cool `.is-a.dev` domain


## Donations
This project is a free and open source service for developers and will stay that way.
Please consider donating to help me keep this running forever!

<a href="https://www.buymeacoffee.com/phenax" target="_blank">Buy Me A Coffee</a>
<a href="https://liberapay.com/phenax" target="_blank">Liberapay recurring donation button</a>


## Similar services
You should also checkout -
* [js.org](https://github.com/js-org/js.org/tree/master)
* [thedev.id](https://github.com/fransallen/thedev.id)
* [runs-on.tech](https://github.com/aakhilv/runs-on.tech)


## Uptime
Uptime Robot ratio (30 days)
![Uptime Robot ratio (30 days)] 
 (https://img.shields.io/uptimerobot/ratio/m787472617-240f4d61a5439a87becb2cf9?label=uptime%20-%20redirections&style=for-the-badge)

You can check the uptime of the service via [our status dashboard](https://stats.uptimerobot.com/zY4XKIRVzw)


## License

This project is under the [GPL-3.0](./LICENSE) license.

**Comment by phenax** [comment]
The information there doesn't seem to be relevant to anyone. Is there a reason to have that on the readme?

**Comment by Bad-Boy-Codes** [comment]
> The information there doesn't seem to be relevant to anyone. Is there a reason to have that on the readme?

yes let the people know how may users used the domains
 i also tried adding the domains director file count
but it didn't work somehow
idk though but it makes the readme better looking ig?

**Review by MaskDuck — DISMISSED** [review]
uh this looks nice but phenax got some comment so when everything is ok feel free to dismiss this, also i got something to ask.
1. is there any reason to break these line?
image
image
2. could you add number of files in the domains folder?

**Comment by Bad-Boy-Codes** [comment]
> uh this looks nice but phenax got some comment so when everything is ok feel free to dismiss this, also i got something to ask.
> 
> 1. is there any reason to break these line?
>    image
>    image
> 2. could you add number of files in the domains folder?

just edit it

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please merge the latest changes into the branch.

**Comment by SemantCodes** [comment]
updated to latest

**Comment by SemantCodes** [comment]
preview:

<p align="center">
    GitHub GitHub contributors GitHub closed pull requests
   <br/><br/>
   is-a-dev banner
   <br/></p>
<h1 align="center">is-a.dev</h1>

   **is-a-dev** is a service that allows developers to get a sweet-looking `.is-a.dev` domain for their personal websites.
<p align="center">
   <br/
   <a href="https://discord.gg/PZCGHz4RhQ">Discord</a>
</p>

<p align="center"><strong>is-a.dev</strong> is a service that allows developers to get a sweet-looking `.is-a.dev` domain for their personal websites.</p>

## Registration
Try out our new fast and easy subdomain registration service [here](https://register.is-a.dev)!

Or via the CI

```bash
  npm install @is-a-dev/cli -g
  is-a-dev create
```  

**Manual Registration**:
- [Fork](https://github.com/is-a-dev/register/fork) this repository.
- Add a new file called `your-domain-name.json` in the `domains` folder to register `your-domain-name.is-a.dev`.
- [Read the documentation](https://is-a.dev/docs).
- Your pull request will be reviewed and merged. *Make sure to keep an eye on it incase we need you to make any changes!*
- After the pull request is merged, please allow up to 24 hours for the changes to propagate.
- Enjoy your new `.is-a.dev` domain!

## Status
You can check the uptime of the service via our [status dashboard](https://stats.uptimerobot.com/zY4XKIRVzw).

[Uptime Robot - DNS](https://stats.uptimerobot.com/zY4XKIRVzw/787472645)
[Uptime Robot - Redirect](https://stats.uptimerobot.com/zY4XKIRVzw/787472617)

### Similar Services
- [is-a-good.dev](https://github.com/is-a-good-dev/register)
- [thedev.id](https://github.com/thedev-id/thedev.id)
- [is-not-a.dev](https://is-not-a.dev)
- [is-really.cool](https://github.com/is-really-cool/register)
- [cluster.ws & wip.la](https://github.com/Olivr/free-domain)
- [js.org](https://github.com/js-org/js.org) (*JavaScript projects only*)

### Donate
If you like this project, please consider donating so we can keep this project running forever!

<a href="https://www.buymeacoffee.com/phenax" target="_blank">Buy Me a Coffee</a>
<a href="https://liberapay.com/phenax" target="_blank">Liberapay</a>

**Review by wdhdev — CHANGES_REQUESTED** [review]
IMO the badges should be moved just below the banner but only have the domains badge and add a PRs open badge and issues opened badge and then remove the rest.

So have these badges in this order:
- Domain count
- Issues open
- PRs open

Also, please resolve the merge conflicts and update the branch as it is 3.8k commits behind and update the similar services to which is on the current README.

**Comment by s3mant** [comment]
> IMO the badges should be moved just below the banner but only have the domains badge and add a PRs open badge and issues opened badge and then remove the rest.
> 
> So have these badges in this order:
> 
> * Domain count
> * Issues open
> * PRs open
> 
> Also, please resolve the merge conflicts and update the branch as it is 3.8k commits behind and update the similar services to which is on the current README.

checkout

**Review by wdhdev — APPROVED** [review]
I cleaned up the code a bit and applied some small changes and tweaks in 53c5247545863540c29d1fb5963e0b46f75589d6.

**Pull request merged**
