### PR TITLE
Register tonix.is-a.dev

### PR DESCRIPTION
**Pull request by antonio-francis**
Added `tonix.is-a.dev` using the [CLI](https://www.npmjs.com/package/@is-a-dev/cli).

### CODE REVIEW

**Comment by tonix-me** [comment]
82218a61-341d-453f-9e48-d5e29f455968.id.repl.co


And 

Domain is tonixe.is-a.dev 



Sorry for my mistake

**Review by wdhdev — CHANGES_REQUESTED** [review]
What is your website for?

**Comment by tonix-me** [comment]
> What is your website for?

Portfolio

**Comment by tonix-me** [comment]
Portfolio can you give

**Comment by WilliamDavidHarrison** [comment]
This website has a login form, clearly not a portfolio.

**Comment by tonix-me** [comment]
> This website has a login form, clearly not a portfolio.

I was makeing the website if you are not interested
Fine.

**Pull request closed without merging**
