### PR TITLE
Register tts.deva.is-a.dev

### PR DESCRIPTION
**Pull request by turbomaster95**
Added `tts.deva.is-a.dev` using the [CLI](https://www.npmjs.com/package/@is-a-dev/cli).

### CODE REVIEW

**Comment by turbomaster95** [comment]
Pls don't merge m.deva.json and tts.deva.is-a.dev.is-a.dev

**Comment by turbomaster95** [comment]
Add txt

**Review by hackermondev — APPROVED** [review]

**Review by hackermondev — DISMISSED** [review]
Subdomain's length must be greater than 2. (`m`)

**Comment by turbomaster95** [comment]
Pls change the m.deva to deva.is-a.dev

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
