### PR TITLE
Register ahmedeldin.is-a.dev

### PR DESCRIPTION
**Pull request by ahmed-eldin**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://ahmed-eldin.github.io/

### CODE REVIEW

**Review by wdhdev — APPROVED** [review]

**Comment by ahmed-eldin** [comment]
the ahmedeldin.is-a.dev domain still isn't working. It's been about 24 hours.

**Comment by WilliamDavidHarrison** [comment]
You need to setup GitHub pages and for custom domain put `ahmedeldin.is-a.dev`

**Comment by ahmed-eldin** [comment]
Just changed the custom domain to ahmedeldin.is-a.dev. When I go to the webpage it redirects me to the is-a.dev landing page. In GitHub Pages it says "DNS Check Unsuccessful. ahmedeldin.is-a-dev is improperly configured." Screenshot below.
Screen Shot 2023-02-21 at 2 56 23 PM

**Comment by ahmed-eldin** [comment]
Screen Shot 2023-02-21 at 3 04 05 PM

**Pull request merged**
