### PR TITLE
Register a domain

### PR DESCRIPTION
**Pull request by MatrixCoder0101**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview
https://goutamkumar.vercel.app/

### CODE REVIEW

**Review by omsenjalia — CHANGES_REQUESTED** [review]
You cannot verify vercel domain with mx. This domain will not work.

**Review by MatrixCoder0101 — COMMENTED** [review]
Now this is correct ?

**Comment by MatrixCoder0101** [comment]
>  You cannot verify vercel domain with mx. This domain will not work.

Sir please review again

**Review by MatrixCoder0101 — COMMENTED** [review]
Sir Please Review Again

**Pull request closed without merging**
