### PR TITLE
Update _github-pages-challenge-thehackerdude1083.thehackerdude1083.json

### PR DESCRIPTION
**Pull request by ShahkerTHD**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://thehackerdude1083.is-a.dev/

### CODE REVIEW

**Comment by TheHackerDude1083** [comment]
Sorry about closing and opening another Pull request but i just want to change the email to a public one.

Thanks,
Shaheer

**Review by devendrakanojiya — APPROVED** [review]
looks good to me

**Review by iostpa — APPROVED** [review]
Seems good to me

**Comment by devendrakanojiya** [comment]
> Seems good to me

@CuteDog5695 Please review and approve my pull request it's been on review required state since 4 days. And I need domain urgently please sir

**Pull request merged**
