### PR TITLE
Create lars.json

### PR DESCRIPTION
**Pull request by Panic3564**
To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: https://larssieboy18.github.io/is-a-dev-website/
- [x] The website is reachable.
- [x] The CNAME record doesn't contain any slash.
- [x] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

### CODE REVIEW

**Review by andrewstech — CHANGES_REQUESTED** [review]
404

**Review by wdhdev — DISMISSED** [review]
No 404 anymore. Redirects to https://www.youtube.com/watch?v=dQw4w9WgXcQ

(nice rickroll)

**Comment by larssieboy18** [comment]
Is something more needed to be done by me? On my end I don't see any errors (anymore).

**Review by omsenjalia — APPROVED** [review]
great rickroll

**Comment by WilliamDavidHarrison** [comment]
Sorry, we can't allow a domain for this.

**Pull request closed without merging**
