### PR TITLE
BETA  Add Subdomain:snowflakeAfk

### PR DESCRIPTION
**Pull request by NyxNoirXD**
Added the domain  snowflakeAfk

### CODE REVIEW

**Review by omsenjalia — CHANGES_REQUESTED** [review]
Invalid TXT records

**Comment by AceyDoCodes** [comment]
> Invalid TXT records 

TXT record can be any string value. You can only have 1 TXT record.
**any string value**
:/ it can be anything
how can it be invalid

**Comment by omxpro** [comment]
> > Invalid TXT records
> 
> `TXT record can be any string value. You can only have 1 TXT record.` **any string value** :/ it can be anything how can it be invalid

Oohh

**Review by omsenjalia — DISMISSED** [review]
TXT records

**Review by MaskDuck — CHANGES_REQUESTED** [review]
can you have some form of actual records instead of some random string?
and also can you elaborate on how will this domain be used/displayed on the online internet? the domains here doesn't seem to work with anything and is just a placeholder (to prevent others to register this domain), which goes against our tos.

also, your file name must be all lowercased. lowercase it.

**Comment by omxpro** [comment]
> can you have some form of actual records instead of some random string? and also can you elaborate on how will this domain be used/displayed on the online internet? the domains here doesn't seem to work with anything and is just a placeholder (to prevent others to register this domain), which goes against our tos.
> 
> also, your file name must be all lowercased. lowercase it.

After you said it he/she still added a TXT record with random string

**Pull request closed without merging**
