### PR TITLE
Update A record to CNAME

### PR DESCRIPTION
**Pull request by Joshua-Noakes1**
Updated A record to CNAME as im changing some Digitial Ocean Droplets i own to Oracle Cloud vms

To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: https://cocogoat.xyz
- [x] The website is reachable.
- [x] The CNAME record doesn't contain any slash.
- [x] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

### CODE REVIEW

**Review by MaskDuck — CHANGES_REQUESTED** [review]
i can't reach the cname. can you give me a url preview of the working website? (pls comment not edit your file)

**Review by wdhdev — CHANGES_REQUESTED** [review]
CNAME not reachable

**Comment by Joshua-Noakes1** [comment]
Sorry, CNAME should be reachable now

**Review by wdhdev — APPROVED** [review]

**Comment by Joshua-Noakes1** [comment]
@MaskDuck just want to follow up with the change

**Review by MaskDuck — APPROVED** [review]

**Pull request merged**
