### PR TITLE
retaliate

### PR DESCRIPTION
**Pull request by ukriu**
no
unblock the filter on the server

### CODE REVIEW

**Comment by iostpa** [comment]
Hi we aint that dumb

**Comment by Satindar31** [comment]
LGTM

**Comment by ukriu** [comment]
> LGTM

too late 😭

**Comment by ukriu** [comment]
This is a joke btw 😭

**Comment by wdhdev** [comment]
We don't appreciate users wasting our maintainer team's time. Unfortunately I will have to block you from the organisation and your domains will be removed promptly.

**Comment by Satindar31** [comment]
> We don't appreciate users wasting our maintainer team's time. Unfortunately I will have to block you from the organisation and your domains will be removed promptly. (just kidding, maybe)

Your maintainers are drunk(just kidding, maybe)

**Pull request closed without merging**
