### PR TITLE
Create maninder.json

### PR DESCRIPTION
**Pull request by github4maninder**
Add MX Records and more user info, 

Reviewer, Please See That All Things Are Right!! :)

### CODE REVIEW

**Comment by github4maninder** [comment]
@TheBotlyNoob & @mtgsquad Please Review This 👍🏻

**Comment by github4maninder** [comment]
@hackermondev kindly review this PR

**Comment by github4maninder** [comment]
@EpicGamer007 can you assist me with this request

**Comment by EpicGamer007** [comment]
@github4maninder , I am not sure why you pinged me but there is a backlog of domains wanted (there is a 156 issues at the time of writing). I do not have write access and I am not in the organization so I cannot do anything. The only thing you can do at this point is wait.

**Comment by github4maninder** [comment]
@phenax , hi can you assist with the review of this PR

**Review by phenax — APPROVED** [review]

**Pull request merged**
