### PR TITLE
add email with new mx records :)

### PR DESCRIPTION
**Pull request by hackermondev**
Support for MX records has been added!

### CODE REVIEW

**Comment by phenax** [comment]
@hackermondev, [please read my comment on the PR](https://github.com/is-a-dev/register/pull/1093#issuecomment-913497225). It mentions that CNAME cannot be used with any other record types. You can either create a new subdomain or use A record if possible.

**Comment by hackermondev** [comment]
@phenax, I can't get it to work.

**Comment by phenax** [comment]
You will have to remove the CNAME record from the file

**Comment by phenax** [comment]
Please take a pull from the main branch and push again

**Pull request closed without merging**
