### PR TITLE
BETA: Register hazelnut.is-a.dev

### PR DESCRIPTION
**Pull request by HazelNutHoney**
Added `hazelnut.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
I cannot reach your website.

**Comment by TheMrRedstone** [comment]
How do I add the website I used the is-a.dev dashboard to register the domain?

**Comment by TheMrRedstone** [comment]
> I cannot reach your website.

How do I add the website I used the is-a.dev dashboard to register the domain?

**Review by HazelNutHoney — COMMENTED** [review]
Changed from railway CName to Github Pages CName

**Review by wdhdev — APPROVED** [review]

**Pull request merged**
