### PR TITLE
BETA: Register mr.bhardwaj.is-a.dev

### PR DESCRIPTION
**Pull request by rohanbhardwaj205**
Added `mr.bhardwaj.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Review by Omxpro — CHANGES_REQUESTED** [review]
cname cannot contain /, you need to work bhardwaj.is-a.dev before making mr.bharadwaj.is-a.dev

**Review by rohanbhardwaj205 — COMMENTED** [review]
Updated CNAME

**Comment by Omxpro** [comment]
> Updated CNAME

the site isnt accessable

**Comment by rohanbhardwaj205** [comment]
It is accessible now

**Comment by rohanbhardwaj205** [comment]
> > Updated CNAME
> 
> the site isnt accessable

the site is working now

**Review by Omxpro — APPROVED** [review]

**Review by iostpa — APPROVED** [review]

**Comment by rohanbhardwaj205** [comment]
I have got the domain **bhardwaj.is-a.dev** but I requested for **mr.bhardwaj.is-a.dev** How can can I use this feat domain to setup my requested domain.

**Comment by Omxpro** [comment]
> I have got the domain **bhardwaj.is-a.dev** but I requested for **mr.bhardwaj.is-a.dev** How can can I use this feat domain to setup my requested domain.

use **mr.bhardwaj.is-a.dev** whenever using the domain insted of **bhardwaj.is-a.dev** they will both work the same way

**Comment by rohanbhardwaj205** [comment]
bhardwaj.is-a.dev is not working. It's redirecting to the official is-a.dev homepage.

**Pull request merged**
