### PR TITLE
Added json file

### PR DESCRIPTION
**Pull request by g-pratik**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.

### CODE REVIEW

**Comment by piotr25691** [comment]
wtf is happening over here

is .is-a.dev experiencing a PR raid?

**Comment by g-pratik** [comment]
> wtf is happening over here
> 
> is .is-a.dev experiencing a PR raid?

Hey man no,
We took session for our developers to encourage them on how they can do this and now they are doing it :)
 its for them to have more opportunities in career and learning how they can have their own presentation websites for their skills

**Comment by piotr25691** [comment]
> > wtf is happening over here
> > is .is-a.dev experiencing a PR raid?
> 
> Hey man no, We took session for our developers to encourage them on how they can do this and now they are doing it :) its for them to have more opportunities in career and learning how they can have their own presentation websites for their skills

it looked kinda sus for accounts created 2 weeks ago to all go create dozens of PRs but ok

**Comment by 1986webdeveloper** [comment]
> > > wtf is happening over here
> > > is .is-a.dev experiencing a PR raid?
> > 
> > 
> > Hey man no, We took session for our developers to encourage them on how they can do this and now they are doing it :) its for them to have more opportunities in career and learning how they can have their own presentation websites for their skills
> 
> it looked kinda sus for accounts created 2 weeks ago to all go create dozens of PRs but ok

This is our developers. you can check list of PRs. 

https://github.com/is-a-dev/register/pull/5317
https://github.com/is-a-dev/register/pull/5318
https://github.com/is-a-dev/register/pull/5319
https://github.com/is-a-dev/register/pull/5320
https://github.com/is-a-dev/register/pull/5321
https://github.com/is-a-dev/register/pull/5322
https://github.com/is-a-dev/register/pull/5323
https://github.com/is-a-dev/register/pull/5324
https://github.com/is-a-dev/register/pull/5325
https://github.com/is-a-dev/register/pull/5326
https://github.com/is-a-dev/register/pull/5327
https://github.com/is-a-dev/register/pull/5328
https://github.com/is-a-dev/register/pull/5329
https://github.com/is-a-dev/register/pull/5330
https://github.com/is-a-dev/register/pull/5331
https://github.com/is-a-dev/register/pull/5332
https://github.com/is-a-dev/register/pull/5333
https://github.com/is-a-dev/register/pull/5334
https://github.com/is-a-dev/register/pull/5335
https://github.com/is-a-dev/register/pull/5342
https://github.com/is-a-dev/register/pull/5343
https://github.com/is-a-dev/register/pull/5344
https://github.com/is-a-dev/register/pull/5346
https://github.com/is-a-dev/register/pull/5347
https://github.com/is-a-dev/register/pull/5348
https://github.com/is-a-dev/register/pull/5349
https://github.com/is-a-dev/register/pull/5350
https://github.com/is-a-dev/register/pull/5351
https://github.com/is-a-dev/register/pull/5352
https://github.com/is-a-dev/register/pull/5353
https://github.com/is-a-dev/register/pull/5354
https://github.com/is-a-dev/register/pull/5355
https://github.com/is-a-dev/register/pull/5356
https://github.com/is-a-dev/register/pull/5357
https://github.com/is-a-dev/register/pull/5358
https://github.com/is-a-dev/register/pull/5359
https://github.com/is-a-dev/register/pull/5360
https://github.com/is-a-dev/register/pull/5361
https://github.com/is-a-dev/register/pull/5362
https://github.com/is-a-dev/register/pull/5363
https://github.com/is-a-dev/register/pull/5364
https://github.com/is-a-dev/register/pull/5365
https://github.com/is-a-dev/register/pull/5366
https://github.com/is-a-dev/register/pull/5367
https://github.com/is-a-dev/register/pull/5368
https://github.com/is-a-dev/register/pull/5369
https://github.com/is-a-dev/register/pull/5370
https://github.com/is-a-dev/register/pull/5372
https://github.com/is-a-dev/register/pull/5373
https://github.com/is-a-dev/register/pull/5374
https://github.com/is-a-dev/register/pull/5375
https://github.com/is-a-dev/register/pull/5376
https://github.com/is-a-dev/register/pull/5377
https://github.com/is-a-dev/register/pull/5378
https://github.com/is-a-dev/register/pull/5379
https://github.com/is-a-dev/register/pull/5380
https://github.com/is-a-dev/register/pull/5381
https://github.com/is-a-dev/register/pull/5382
https://github.com/is-a-dev/register/pull/5383
https://github.com/is-a-dev/register/pull/5384
https://github.com/is-a-dev/register/pull/5385
https://github.com/is-a-dev/register/pull/5386
https://github.com/is-a-dev/register/pull/5387
https://github.com/is-a-dev/register/pull/5388

**Comment by g-pratik** [comment]
> > > wtf is happening over here
> > > is .is-a.dev experiencing a PR raid?
> > 
> > 
> > Hey man no, We took session for our developers to encourage them on how they can do this and now they are doing it :) its for them to have more opportunities in career and learning how they can have their own presentation websites for their skills
> 
> it looked kinda sus for accounts created 2 weeks ago to all go create dozens of PRs but ok

This is our developers. you can check list of PRs. 
https://github.com/is-a-dev/register/pull/5317 https://github.com/is-a-dev/register/pull/5318 https://github.com/is-a-dev/register/pull/5319 https://github.com/is-a-dev/register/pull/5320 https://github.com/is-a-dev/register/pull/5321 https://github.com/is-a-dev/register/pull/5322 https://github.com/is-a-dev/register/pull/5323 https://github.com/is-a-dev/register/pull/5324 https://github.com/is-a-dev/register/pull/5325 https://github.com/is-a-dev/register/pull/5326 https://github.com/is-a-dev/register/pull/5327 https://github.com/is-a-dev/register/pull/5328 https://github.com/is-a-dev/register/pull/5329 https://github.com/is-a-dev/register/pull/5330 https://github.com/is-a-dev/register/pull/5331 https://github.com/is-a-dev/register/pull/5332 https://github.com/is-a-dev/register/pull/5333 https://github.com/is-a-dev/register/pull/5334 https://github.com/is-a-dev/register/pull/5335 https://github.com/is-a-dev/register/pull/5342 https://github.com/is-a-dev/register/pull/5343 https://github.com/is-a-dev/register/pull/5344 https://github.com/is-a-dev/register/pull/5346 https://github.com/is-a-dev/register/pull/5347 https://github.com/is-a-dev/register/pull/5348 https://github.com/is-a-dev/register/pull/5349 https://github.com/is-a-dev/register/pull/5350 https://github.com/is-a-dev/register/pull/5351 https://github.com/is-a-dev/register/pull/5352 https://github.com/is-a-dev/register/pull/5353 https://github.com/is-a-dev/register/pull/5354 https://github.com/is-a-dev/register/pull/5355 https://github.com/is-a-dev/register/pull/5356 https://github.com/is-a-dev/register/pull/5357 https://github.com/is-a-dev/register/pull/5358 https://github.com/is-a-dev/register/pull/5359 https://github.com/is-a-dev/register/pull/5360 https://github.com/is-a-dev/register/pull/5361 https://github.com/is-a-dev/register/pull/5362 https://github.com/is-a-dev/register/pull/5363 https://github.com/is-a-dev/register/pull/5364 https://github.com/is-a-dev/register/pull/5365 https://github.com/is-a-dev/register/pull/5366 https://github.com/is-a-dev/register/pull/5367 https://github.com/is-a-dev/register/pull/5368 https://github.com/is-a-dev/register/pull/5369 https://github.com/is-a-dev/register/pull/5370 https://github.com/is-a-dev/register/pull/5372 https://github.com/is-a-dev/register/pull/5373 https://github.com/is-a-dev/register/pull/5374 https://github.com/is-a-dev/register/pull/5375 https://github.com/is-a-dev/register/pull/5376 https://github.com/is-a-dev/register/pull/5377 https://github.com/is-a-dev/register/pull/5378 https://github.com/is-a-dev/register/pull/5379 https://github.com/is-a-dev/register/pull/5380 https://github.com/is-a-dev/register/pull/5381 https://github.com/is-a-dev/register/pull/5382 https://github.com/is-a-dev/register/pull/5383 https://github.com/is-a-dev/register/pull/5384 https://github.com/is-a-dev/register/pull/5385 https://github.com/is-a-dev/register/pull/5386 https://github.com/is-a-dev/register/pull/5387 https://github.com/is-a-dev/register/pull/5388

**Review by wdhdev — APPROVED** [review]

**Comment by piotr25691** [comment]
> > > > wtf is happening over here
> > > > is .is-a.dev experiencing a PR raid?
> > > 
> > > 
> > > Hey man no, We took session for our developers to encourage them on how they can do this and now they are doing it :) its for them to have more opportunities in career and learning how they can have their own presentation websites for their skills
> > 
> > 
> > it looked kinda sus for accounts created 2 weeks ago to all go create dozens of PRs but ok
> 
> This is our developers. you can check list of PRs. #5317 #5318 #5319 #5320 #5321 #5322 #5323 #5324 #5325 #5326 #5327 #5328 #5329 #5330 #5331 #5332 #5333 #5334 #5335 #5342 #5343 #5344 #5346 #5347 #5348 #5349 #5350 #5351 #5352 #5353 #5354 #5355 #5356 #5357 #5358 #5359 #5360 #5361 #5362 #5363 #5364 #5365 #5366 #5367 #5368 #5369 #5370 #5372 #5373 #5374 #5375 #5376 #5377 #5378 #5379 #5380 #5381 #5382 #5383 #5384 #5385 #5386 #5387 #5388

that's a big team right here

**Comment by 1986webdeveloper** [comment]
This is 10% of our team @piotr25691 😆  we plan to launch big on YCombinator soon 🔥

**Comment by F1repup650** [comment]
> > > > wtf is happening over here
> > > > is .is-a.dev experiencing a PR raid?
> > > 
> > > 
> > > Hey man no, We took session for our developers to encourage them on how they can do this and now they are doing it :) its for them to have more opportunities in career and learning how they can have their own presentation websites for their skills
> > 
> > it looked kinda sus for accounts created 2 weeks ago to all go create dozens of PRs but ok
> 
> This is our developers. you can check list of PRs. 
> https://github.com/is-a-dev/register/pull/5317 https://github.com/is-a-dev/register/pull/5318 https://github.com/is-a-dev/register/pull/5319 https://github.com/is-a-dev/register/pull/5320 https://github.com/is-a-dev/register/pull/5321 https://github.com/is-a-dev/register/pull/5322 https://github.com/is-a-dev/register/pull/5323 https://github.com/is-a-dev/register/pull/5324 https://github.com/is-a-dev/register/pull/5325 https://github.com/is-a-dev/register/pull/5326 https://github.com/is-a-dev/register/pull/5327 https://github.com/is-a-dev/register/pull/5328 https://github.com/is-a-dev/register/pull/5329 https://github.com/is-a-dev/register/pull/5330 https://github.com/is-a-dev/register/pull/5331 https://github.com/is-a-dev/register/pull/5332 https://github.com/is-a-dev/register/pull/5333 https://github.com/is-a-dev/register/pull/5334 https://github.com/is-a-dev/register/pull/5335 https://github.com/is-a-dev/register/pull/5342 https://github.com/is-a-dev/register/pull/5343 https://github.com/is-a-dev/register/pull/5344 https://github.com/is-a-dev/register/pull/5346 https://github.com/is-a-dev/register/pull/5347 https://github.com/is-a-dev/register/pull/5348 https://github.com/is-a-dev/register/pull/5349 https://github.com/is-a-dev/register/pull/5350 https://github.com/is-a-dev/register/pull/5351 https://github.com/is-a-dev/register/pull/5352 https://github.com/is-a-dev/register/pull/5353 https://github.com/is-a-dev/register/pull/5354 https://github.com/is-a-dev/register/pull/5355 https://github.com/is-a-dev/register/pull/5356 https://github.com/is-a-dev/register/pull/5357 https://github.com/is-a-dev/register/pull/5358 https://github.com/is-a-dev/register/pull/5359 https://github.com/is-a-dev/register/pull/5360 https://github.com/is-a-dev/register/pull/5361 https://github.com/is-a-dev/register/pull/5362 https://github.com/is-a-dev/register/pull/5363 https://github.com/is-a-dev/register/pull/5364 https://github.com/is-a-dev/register/pull/5365 https://github.com/is-a-dev/register/pull/5366 https://github.com/is-a-dev/register/pull/5367 https://github.com/is-a-dev/register/pull/5368 https://github.com/is-a-dev/register/pull/5369 https://github.com/is-a-dev/register/pull/5370 https://github.com/is-a-dev/register/pull/5372 https://github.com/is-a-dev/register/pull/5373 https://github.com/is-a-dev/register/pull/5374 https://github.com/is-a-dev/register/pull/5375 https://github.com/is-a-dev/register/pull/5376 https://github.com/is-a-dev/register/pull/5377 https://github.com/is-a-dev/register/pull/5378 https://github.com/is-a-dev/register/pull/5379 https://github.com/is-a-dev/register/pull/5380 https://github.com/is-a-dev/register/pull/5381 https://github.com/is-a-dev/register/pull/5382 https://github.com/is-a-dev/register/pull/5383 https://github.com/is-a-dev/register/pull/5384 https://github.com/is-a-dev/register/pull/5385 https://github.com/is-a-dev/register/pull/5386 https://github.com/is-a-dev/register/pull/5387 https://github.com/is-a-dev/register/pull/5388

#5334 is me, and I'm not a part of your team. Did you just pick a range?

**Pull request merged**
