### PR TITLE
Register skieyen.is-a.dev

### PR DESCRIPTION
**Pull request by SkieyeN**
Register skieyen.is-a.dev with CNAME record pointing to skieyen.github.io.

### CODE REVIEW

**Review by iostpa — CHANGES_REQUESTED** [review]
Site not accessible, please give a preview of your website.

**Comment by SkieyeN** [comment]
I am bit new to github, I have created domain in github settings pages and I got challenger page code and txt code..  Not sure which one I should give on CNAME.

**Comment by SkieyeN** [comment]
_github-pages-challenge-SkieyeN

**Comment by SkieyeN** [comment]
_github-pages-challenge-SkieyeN
.skieyen.is-a.dev

**Comment by CuteDog5695** [comment]
I meant that I needed a preview of your website.

**Comment by SkieyeN** [comment]
Try this domain and website.. kiran-xyz.kesug.com

**Review by iostpa — CHANGES_REQUESTED** [review]
Needs more content imo.

**Comment by SkieyeN** [comment]
> Needs more content imo.

What information do you required

**Pull request closed without merging**
