### PR TITLE
Add prettier workflow according to #17103

### PR DESCRIPTION
**Pull request by ghost**
#17103

### CODE REVIEW

**Comment by cupglassDEV** [comment]
Heres the docs on the cli command heheheh

https://prettier.io/docs/en/cli.html

**Comment by cupglassDEV** [comment]
@wdhdev ill need to check first, in case of smth 😁

**Review by wdhdev — CHANGES_REQUESTED** [review]
Are you able to make it commit using the @is-a-dev-bot account, using the `BOT` environment variable (a GitHub PAT token)?

It is likely that using the default actions user will fail due to branch protections.

**Comment by cupglassDEV** [comment]
> Are you able to make it commit using the @is-a-dev-bot account, using the `BOT` environment variable?
> 
> It is likely that using the default actions user will fail due to branch protections.

Hmm, maybe using this, but point it to `register`

image

**Comment by cupglassDEV** [comment]
tbh this is one, and only solution i found

**Comment by cupglassDEV** [comment]
Updated

**Review by wdhdev — DISMISSED** [review]

**Review by wdhdev — APPROVED** [review]

**Comment by cupglassDEV** [comment]
yey

**Pull request merged**
