### PR TITLE
Update lungustefan.json

### PR DESCRIPTION
**Pull request by lungustefan**
## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.

### CODE REVIEW

**Comment by lungustefan** [comment]
> ## Requirements
> Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.
> 
> Please note that we reserve the rights not to accept any domain at our own discretion.
> 
> * [ ]  The file is in the `domains` folder and is in the JSON format.
> * [ ]  The file's name is all lowercased and alphanumeric.
> * [ ]  You have completed your website.
> * [ ]  The website is reachable.
> * [ ]  The CNAME record doesn't contain `https://` or `/`.
> * [ ]  There is sufficient information at the `owner` field.
> 
> ## Website Link/Preview

I didn't complete this image bc it exists, it just an update

**Review by iostpa — APPROVED** [review]
Same discord username, checks out.

**Comment by CuteDog5695** [comment]
> > ## Requirements
> > Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.
> > Please note that we reserve the rights not to accept any domain at our own discretion.
> > 
> > * [ ]   The file is in the `domains` folder and is in the JSON format.
> > * [ ]   The file's name is all lowercased and alphanumeric.
> > * [ ]   You have completed your website.
> > * [ ]   The website is reachable.
> > * [ ]   The CNAME record doesn't contain `https://` or `/`.
> > * [ ]   There is sufficient information at the `owner` field.
> > 
> > ## Website Link/Preview
> 
> I didn't complete this image bc it exists, it just an update

Ba coaie, nu trebuie sa trimiti de 2 ori.

**Comment by lungustefan** [comment]
> > > ## Requirements
> > > Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.
> > > Please note that we reserve the rights not to accept any domain at our own discretion.
> > > 
> > > * [ ]    The file is in the `domains` folder and is in the JSON format.
> > > * [ ]    The file's name is all lowercased and alphanumeric.
> > > * [ ]    You have completed your website.
> > > * [ ]    The website is reachable.
> > > * [ ]    The CNAME record doesn't contain `https://` or `/`.
> > > * [ ]    There is sufficient information at the `owner` field.
> > > 
> > > ## Website Link/Preview
> > 
> > 
> > I didn't complete this image bc it exists, it just an update
> 
> Ba coaie, nu trebuie sa trimiti de 2 ori.

Ce mai conteaza :)

**Comment by CuteDog5695** [comment]
Ai dreptate...

**Comment by lungustefan** [comment]
@wdhdev you broke PRs :)

**Comment by Stef-00012** [comment]
> Ai dreptate...

~~as always he never does anything good fr fr~~

**Comment by lungustefan** [comment]
> > Ai dreptate...
> 
> ~as always he never does anything good fr fr~

~💀~

**Comment by lungustefan** [comment]
@Stef-00012 approve changes also let's get it approved by everyone lol

**Review by Stef-DP — APPROVED** [review]

**Comment by Stef-00012** [comment]
> @Stef-00012 approve changes also let's get it approved by everyone lol

there

**Comment by Stef-00012** [comment]
oh wait

**Comment by Stef-00012** [comment]
willy fixed it as soon as i merged it lol

**Comment by lungustefan** [comment]
Lucky

**Pull request merged**
