### PR TITLE
Remove domains using Vercel/Netlify

### PR DESCRIPTION
**Pull request by wdhdev**
The domains that are being removed in this PR use either a Vercel or Netlify A record or CNAME record. This PR **doesn't** affect domains using Vercel or Netlify through a `URL` record.

The removed domains in this PR use a CNAME record like: `"CNAME": "abc.vercel.app"` or an A record like: `"A": "76.76.21.21"` so therefore they are removed.

### CODE REVIEW

**Comment by WilliamDavidHarrison** [comment]
> @WilliamDavidHarrison can you ping the people and wait for their response before doing this?

Will do in future.

**Comment by WilliamDavidHarrison** [comment]
> > > @WilliamDavidHarrison can you ping the people and wait for their response before doing this?
> > 
> > 
> > Will do in future.
> 
> ...
> 
> i meant: do it now

Oh.

**Comment by WilliamDavidHarrison** [comment]
Users mentioned below, your domains use unsupported services and may be at risk of removal. If you want to keep your domain please either use a `URL` record (e.g: `"URL": "https://abc.netlify.app"`) so you can keep your domain and your domain will continue to work or specify a different record.

An alternative to Vercel/Netlify is [Railway](https://railway.app), so you can always check that out and use that instead.

<details>
<summary>Mentions</summary>
@daniel-shuy 
@ezedinff 
@iamsdas
@LejhandG
@Dam-Cup-O-Java
@nirlep5252
@opensourze
@shalomscott
@skdhg
@windowscmd
@xMdb
@yummyweb
</details>

(I pinged the user that edited the file originally as some people's usernames have changed)

**Comment by LejhandG** [comment]
You can delete my domain

**Review by WindowsCmd — APPROVED** [review]

**Review by twlite — APPROVED** [review]

**Review by xMdb — APPROVED** [review]

**Review by thatjar — APPROVED** [review]

**Comment by WilliamDavidHarrison** [comment]
As the users have had more than a month to respond, with all of the users actually responding agreeing to have the domains removed, we will be removing all of them.

**Pull request closed without merging**
