### PR TITLE
Added emtyfayVia is-a-dev-cli

### PR DESCRIPTION
**Pull request by Emtyffx**
Added emtyfayvia the CLI

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
404

**Comment by Emtyffx** [comment]
Updated url

**Review by wdhdev — APPROVED** [review]
Still 404.

**Review by wdhdev — CHANGES_REQUESTED** [review]
Didn't mean to approve

**Comment by WilliamDavidHarrison** [comment]
Succeeded by #4424

**Pull request closed without merging**
