### PR TITLE
Emtyffx patch 1

### PR DESCRIPTION
**Pull request by Emtyffx**
[PATCHED] Updated cname

### CODE REVIEW

**Review by omsenjalia — CHANGES_REQUESTED** [review]
CNAME cannot contains HTTPS and /

**Review by omsenjalia — COMMENTED** [review]
This was actually right but you had to add email

**Comment by Emtyffx** [comment]
Thanks for commenting. I didn't work with domains names before

**Review by wdhdev — APPROVED** [review]

**Comment by Emtyffx** [comment]
Thanks

**Pull request merged**
