### PR TITLE
BETA: Register namkun.is-a.dev

### PR DESCRIPTION
**Pull request by beocaca**
Added `namkun.is-a.dev` using the [dashboard](https://manage.is-a.dev).

### CODE REVIEW

**Review by MaskDuck — CHANGES_REQUESTED** [review]
incompleted website, site should have more content

**Review by triach-rold — CHANGES_REQUESTED** [review]
Reachable but incomplete.

**Review by triach-rold — APPROVED** [review]
Website is reachable and not incomplete- should be a pretty good website after you add content :)

**Comment by beocaca** [comment]
image
image
@triach-rold please help me review this

**Comment by triach-rold** [comment]
I would review it, but I honestly have no idea how Baccarat works :(

**Comment by triach-rold** [comment]
UI seems to work fine though, seems responsive enough and the design's pretty fine.

**Review by MaskDuck — DISMISSED** [review]
I don't think `a.namkun.json` name is allowed, please change it to something that has 2+ characters in each component please (e.g. `aa.namkun.json`)

**Comment by beocaca** [comment]
@triach-rold @MaskDuck tks

**Comment by beocaca** [comment]
@MaskDuck  @DEV-DIBSTER any problem please ?

**Review by iostpa — APPROVED** [review]
seems fine to me now

**Pull request merged**
