### PR TITLE
adi is a dev registration

### PR DESCRIPTION
**Pull request by mobi35**
### Requirements
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [x] The website is reachable.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### Link to Website

https://stryfe200fps.github.io/portfolio/

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please remove the /portfolio from your CNAME record.

**Review by wdhdev — DISMISSED** [review]
Site is on `/portfolio`

**Comment by stryfe200fps** [comment]
changed the site to https://stryfe200fps.github.io

**Review by wdhdev — APPROVED** [review]

**Review by stryfe200fps — APPROVED** [review]
is it possible to merge?

**Comment by WilliamDavidHarrison** [comment]
@andrewstech LGTM?

**Review by MaskDuck — APPROVED** [review]

**Pull request merged**
