### PR TITLE
Changed redirect

### PR DESCRIPTION
**Pull request by AquaQuokka**

### CODE REVIEW

**Review by wdhdev — APPROVED** [review]

**Comment by AquaQuokka** [comment]
Uh guys

**Comment by AquaQuokka** [comment]
I think that https://azumi.aqua.is-a.dev is missing an SSL certificate.
image

**Comment by AquaQuokka** [comment]
and apparently the connection timed out.

**Comment by WilliamDavidHarrison** [comment]
> I think that https://azumi.aqua.is-a.dev is missing an SSL certificate. image

It might be an issue with your service

**Comment by AquaQuokka** [comment]
image
It works fine if I access it directly instead of through https://azumi.aqua.is-a.dev/

**Pull request merged**
