### PR TITLE
Create elnexreal.json

### PR DESCRIPTION
**Pull request by pundang**
## Requirements
- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Link to Website

elnexreal.github.io

### CODE REVIEW

**Review by omsenjalia — CHANGES_REQUESTED** [review]
Please finish and build an actual website.

**Review by wdhdev — CHANGES_REQUESTED** [review]
Please make a website

**Comment by elnexreal** [comment]
I've completed my website, its a bit trashy but the important thing is that i have it

**Comment by elnexreal** [comment]
NVM IS BUGGED... FIXING IT

**Review by wdhdev — DISMISSED** [review]

**Comment by WilliamDavidHarrison** [comment]
Closing and reopening to fix checks.

**Review by omsenjalia — DISMISSED** [review]
Great website

**Comment by elnexreal** [comment]
> Great website

Haha i cant load custom assets in git but locally

**Review by wdhdev — APPROVED** [review]

**Comment by TerraPlayz** [comment]
@WilliamDavidHarrison remove email feild as it's not being used

**Comment by TerraPlayz** [comment]
nevermind

**Comment by TerraPlayz** [comment]
William come to discord

**Comment by WilliamDavidHarrison** [comment]
> @WilliamDavidHarrison remove email feild as it's not being used

Checks will fail without.

**Pull request merged**
