### PR TITLE
Requesting Subdomain

### PR DESCRIPTION
**Pull request by satr14washere**
Hi, im requesting the subdomain `chat-with.sx9.is-a.dev`

### CODE REVIEW

**Review by MaskDuck — CHANGES_REQUESTED** [review]
filename ends in json
also badly formatted
also cname being uppercase plz

**Comment by SX-9** [comment]
Now?

**Review by MaskDuck — APPROVED** [review]
not sus

**Comment by SX-9** [comment]
Finaly ty

**Pull request merged**
