### PR TITLE
Register Subdomain: pmint05

### PR DESCRIPTION
**Pull request by pmint05**
### Requirements
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [x] The website is reachable.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### Link to Website

http://pmint05.github.io/ (My website is under maintenance)

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
Sorry, you need to have content on your website.

**Comment by pmint05** [comment]
> Sorry, you need to have content on your website.

I've just updated my repo, please check again. Thank you!

**Review by wdhdev — APPROVED** [review]

**Comment by pmint05** [comment]
> > Sorry, you need to have content on your website.
> 
> I've just updated my repo, please check again. Thank you!

@WilliamDavidHarrison What's the next step I need to do?

**Comment by WilliamDavidHarrison** [comment]
> > > Sorry, you need to have content on your website.
> > 
> > 
> > I've just updated my repo, please check again. Thank you!
> 
> @WilliamDavidHarrison What's the next step I need to do?

Wait for a maintainer to merge your PR.

**Review by MaskDuck — APPROVED** [review]

**Pull request merged**
