### PR TITLE
Add emails

### PR DESCRIPTION
**Pull request by TheBotlyNoob**
needs #1126

### CODE REVIEW

**Review by mtgsquad — DISMISSED** [review]

**Review by mtgsquad — APPROVED** [review]

**Review by hackermondev — APPROVED** [review]

**Review by phenax — COMMENTED** [review]
Let's keep this PR for later. Do not merge it. We don't want to increase the attack surface immedietely after releasing a new feature.

**Comment by AcaiBerii** [comment]
bump

**Review by MaskDuck — APPROVED** [review]

**Comment by WilloIzCitron** [comment]
hmm this pr is 9 months ago, it was incomplete

**Comment by mtgsquad** [comment]
> hmm this pr is 9 months ago, it was incomplete

@WilloIzCitron at this point, this PR may not be merged, considering we already have a discord server up and running for support.

**Comment by WilloIzCitron** [comment]
Ok

**Review by wdhdev — APPROVED** [review]

**Review by wdhdev — APPROVED** [review]

**Comment by WilliamDavidHarrison** [comment]
@phenax Is this going to be actually implemented or can this just be closed?

**Comment by WilliamDavidHarrison** [comment]
I'm going to assume this isn't going to be implemented due to security reasons and also the PR has merge conflicts.

**Pull request closed without merging**
