### PR TITLE
Update nziie.json (update website details - renamed repo) 

### PR DESCRIPTION
**Pull request by Nzii3**
To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [x] The website is reachable.
- [x] The CNAME record doesn't contain any slash.
- [x] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

### CODE REVIEW

**Comment by Nzii3** [comment]
I changed my repo name so my website is down until the pull request is merged.

**Comment by Nzii3** [comment]
Huh? It wasn’t merged.

**Review by MaskDuck — APPROVED** [review]

**Review by MaskDuck — CHANGES_REQUESTED** [review]
ooops wait

can you get the github account `Nziie3` to approve this pr before i can merge this?

**Comment by Nzii3** [comment]
@MaskDuck So should I just create a new file for it with a new pr or just do another commit?

**Comment by Nzii3** [comment]
Hello…?

**Comment by Nzii3** [comment]
Oh f*

**Comment by Nzii3** [comment]
@MaskDuck Done.

**Comment by Nzii3** [comment]
@MaskDuck Hello…?

**Review by MaskDuck — APPROVED** [review]
sorry, i forgor to check followups

**Pull request merged**
